nfsPVC:
  nfs:
    shareName: shares/lacc/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - lacc.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - lacc.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
      GitHubOAuthenticator:
        oauth_callback_url: https://lacc.jupyter.cal-icor.org/hub/oauth_callback
