nfsPVC:
  nfs:
    shareName: ucsc/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: University of California, Santa Cruz
          logo_url: https://communications.ucsc.edu/wp-content/uploads/2021/04/2021-Logo-Do-2.jpg
          url: https://www.ucsc.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - ucsc-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - ucsc-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - abrsvn@ucsc.edu
          - jusimons@ucsc.edu
