nfsPVC:
 enabled: true
 nfs:
   serverIP: 10.183.114.2

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal-ICOR Workshop Hub
          url: https://cal-icor.org
          logo_url: https://cal-icor.org/assets/logo-trans.png
        designed_by:
          name: Cal-ICOR
          url: https://cal-icor.org
        operated_by:
          name: Cal-ICOR
          url: https://cal-icor.org
        funded_by:
          name: California Learning Lab
          url: https://callearninglab.org

  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
      resources:
        requests:
          # FIXME: We want no guarantees here!!!
          # This is lowest possible value
          cpu: 0.001
          memory: 3Gi
        limits:
          memory: 3Gi

  hub:
    initContainers:
      - name: templates-clone
        image: alpine/git:2.40.1
        command:
          - /bin/sh
        args:
          - -c
          # Remove the existing repo first if it exists, as otherwise we will
          # error out when the pod restarts. /srv/extra-templates-dir is an
          # emptyDir volume, so it is *not* cleaned up when the pod's containers restarts -
          # only when the pod is deleted and cleaned back up.
          # We also mount the emptyDir in `/srv/extra-templates-dir` but
          # clone into a *subdirectory*, as the mount itself is owned by
          # root, and git freaks out when that is the case. By putting
          # the repo in a sub directory, we avoid the permission problems.
          - |
            echo "Cloning git repo ${GIT_REPO_URL} into /srv/extra-templates-dir/repo";
            rm -rf /srv/extra-templates-dir/repo;
            git clone ${GIT_REPO_URL} /srv/extra-templates-dir/repo
        env:
          - name: GIT_REPO_URL
            valueFrom:
              configMapKeyRef:
                name: hub-custom-templates-config
                key: GIT_REPO_URL
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/extra-templates-dir
    extraContainers:
      - name: templates-sync
        image: alpine/git:2.40.1
        workingDir: /srv/extra-templates-dir/repo
        command:
          - /bin/sh
        args:
          - -c
          - |
            handle_sigterm() {
                echo "SIGTERM received, terminating...";
                exit;
            }
            trap handle_sigterm SIGTERM;

            echo "Starting template sync...";

            echo "";
            echo "Info about local git repo to be synced:";
            (
                # set -x causes commands run to be printed, helping log readers
                # understand what the generated output is about. set -x is
                # configured within a subshell to just print info about the
                # specific chosen commands and avoid printing info about running
                # "echo", "sleep", "set +x", or similar commands.
                set -x;
                git remote -v;
                ls -lhd /srv/extra-templates-dir/repo;
            )

            echo "";
            echo "Syncing local git repo /srv/extra-templates-dir/repo against origin's branch $(GIT_REPO_BRANCH) every 5 minutes...";
            while true; do
                git fetch origin;
                git reset --hard origin/$(GIT_REPO_BRANCH);

                # signal handling can only be done between sleep calls, so this
                # shouldn't be reduced to the otherwise equivalent "sleep 5m"
                for i in $(seq 300); do
                    sleep 1s;
                done
            done
        env:
          - name: GIT_REPO_BRANCH
            valueFrom:
              configMapKeyRef:
                name: hub-custom-templates-config
                key: GIT_REPO_BRANCH
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/extra-templates-dir
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: repo/templates
      - mountPath: /usr/local/share/jupyterhub/static/extra-assets
        name: custom-templates
        subPath: repo/extra-assets
    extraConfig:
      01-custom-theme: |
        # adds a JupyterHub template path and updates template variables

        from z2jh import get_config
        c.JupyterHub.template_paths.insert(0,'/usr/local/share/jupyterhub/custom_templates')
        c.JupyterHub.template_vars.update({
            'custom': get_config('custom.homepage.templateVars')
        })

    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - denero
          - denero@berkeley.edu
          - yijunge
          - rylo
          - sknapp
          - felder
          - balajialwar
          - gmerritt
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - jonathanferrari@berkeley.edu
          - jonathanferrari
          - fraser@berkeley.edu
      # GitHubOAuthenticator:
        # allowed_organizations:
          # - berkeley-dsep-infra
          # - cal-icor
        # scope:
          # - read:org
    # loadRoles:
      # cal-icor staff
      # cal-icor-staff:
        # description: Enable admin for cal-icor staff
        # this role provides permissions to...
        # scopes:
        #   - admin-ui
        #   - admin:groups
        #   - admin:users
        #   - admin:servers
        #   - read:roles
        #   - read:hub
        #   - access:servers
        # this role will be assigned to...
        # groups:
        #   - course::1524699::group::all-admins
    # initContainers:
    #   # There's another sidecar, specified in `secrets/staging.yaml` and `secrets/prod.yaml`
    #   # that keeps this up to date. https://github.com/jupyterhub/kubespawner/issues/468
    #   # should help us move that back here.
    #   - name: templates-clone
    #     image: alpine/git
    #     args:
    #       - clone
    #       - --depth=1
    #       - --single-branch
    #       - --
    #       - https://github.com/cal-icor/jupyter-hub-homepage
    #       - /srv/repo
    #     securityContext:
    #       runAsUser: 1000
    #       allowPrivilegeEscalation: false
    #       readOnlyRootFilesystem: true
    #     volumeMounts:
    #       - name: custom-templates
    #         mountPath: /srv/repo

  singleuser:
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: base-pool
    storage:
     type: static
     static:
       pvcName: home-nfs-v3
       subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G

  #custom:
  #  group_profiles:
  #
  #    # Example: increase memory for everyone affiliated with a course.
  #
  #    # Name of Class 100, Fall '22; requested in #98765
  #    course::123456:
  #      mem_limit: 4096M
  #      mem_guarantee: 2048M
  #
  #    # Example: grant admin rights to course staff.
  #    # Enrollment types returned by the Canvas API are `teacher`,
  #    # `student`, `ta`, `observer`, and `designer`.
  #    # https://canvas.instructure.com/doc/api/enrollments.html
  #
  #    # Some other class 200, Spring '23; requested in #98776
  #    course::234567::enrollment_type::teacher:
  #      mem_limit: 2096M
  #      mem_guarantee: 2048M
  #    course::234567::enrollment_type::ta:
  #      mem_limit: 2096M
  #      mem_guarantee: 2048M
  #
  #
  #    # Example: a fully specified CanvasOAuthenticator group name.
  #    # This could be useful for temporary resource bumps where the
  #    # instructor could add people to groups in the bCourses UI. This
  #    # would benefit from the ability to read resource bumps from
  #    # jupyterhub's properties. (attributes in the ORM)
  #
  #    # Name of Class 100, Fall '22; requested in #98770
  #    course::123456::group::lab4-bigdata:
  #      - mountPath: /home/rstudio/.ssh
  #        name: home
  #        subPath: _some_directory/_ssh
  #        readOnly: true
