
nfsPVC:
  nfs:
    shareName: jupyter/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - jupyter.cal-icor.org
    tls:
      - hosts:
          - jupyter.cal-icor.org
        secretName: tls-cert
  proxy:
    https:
      enabled: false
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    loadRoles:
      cloudbank-pilot-hub-users:
        services:
          - cloudbank-pilot-hub-users
        scopes:
          - list:users
          - read:users
  scheduling:
    userPlaceholder:
      enabled: false
