nfsPVC:
 nfs:
   shareName: shares/jupyter/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - jupyter.cal-icor.org
    tls:
      - hosts:
        - jupyter.cal-icor.org
        secretName: tls-cert
  proxy:
    https:
      enabled: false
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 80Gi
    resources:
      requests:
        # DataHub often takes up a full CPU now, so let's guarantee it at least that
        cpu: 1
        memory: 1Gi
      limits:
        memory: 2Gi
  scheduling:
    userPlaceholder:
      enabled: false
