nfsPVC:
  nfs:
    shareName: shares/jupyter/staging

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal-ICOR Workshop Hub
          url: https://cal-icor.org
          logo_url: https://cal-icor.org/assets/logo-trans.png
        designed_by:
          name: Cal-ICOR
          url: https://cal-icor.org
        operated_by:
          name: Cal-ICOR
          url: https://cal-icor.org
        funded_by:
          name: California Learning Lab
          url: https://callearninglab.org

  scheduling:
    userPlaceholder:
      enabled: false
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    https:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - staging.jupyter.cal-icor.org
    tls:
      - hosts:
        - staging.jupyter.cal-icor.org
        secretName: tls-cert
