nfsPVC:
  nfs:
    shareName: shares/jupyter/staging

jupyterhub:
  hub:
    initContainers:
      # There's another sidecar, specified in `secrets/staging.yaml` and `secrets/prod.yaml`
      # that keeps this up to date. https://github.com/jupyterhub/kubespawner/issues/468
      # should help us move that back here.
      - name: templates-clone
        image: alpine/git
        args:
          - clone
          - --depth=1
          - --single-branch
          - --
          - https://github.com/cal-icor/jupyter-hub-homepage
          - /srv/repo
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: custom-templates
            mountPath: /srv/repo

  scheduling:
    userPlaceholder:
      enabled: false
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    https:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - staging.jupyter.cal-icor.org
    tls:
      - hosts:
        - staging.jupyter.cal-icor.org
        secretName: tls-cert
