# Volume definition to set up a NFS volume for JupyterHub to store users' home directories.
# this is only used when deploying this chart for the first time, and is not used when the chart is upgraded.
# This is because PVs cannot be modified after they are created, so any changes to this file after the first
# deployment will not be reflected in the PV that was created by the first deployment.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-home-nfs
  namespace: jupyterhub-home-nfs
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteMany
  nfs:
    # TODO: Replace this with the address of the in-cluster NFS server created by JupyterHub-Home-NFS
    server: 34.118.238.48
    path: /
  mountOptions:
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - soft # We pick soft over hard, so NFS lockups don't lead to hung processes
    - retrans=2
    - noresvport
  storageClassName: "standard"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-nfs
  namespace: jupyterhub-home-nfs
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jupyterhub-home-nfs-home-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 1M
