apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prometheus-data-2025-04-10 
spec:
  storageClassName: "ssd"
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: prometheus-data-2025-04-10 
    namespace: support
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/cal-icor-hubs/zones/us-central1-b/disks/prometheus-data-2025-04-10
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: support
  name: prometheus-data-2025-04-10 
spec:
  storageClassName: "ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
