jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:2jW15Iwnvrvp87D70cMzwclZD2cDhRF84g==,iv:d4CXEI0wxrBYUNY361jEXi52rbQhHUjE0W1IrMW2i8Y=,tag:muW3Wjwxidne6gwUyyJy5Q==,type:str]
                #ENC[AES256_GCM,data:fAE0nsbnUGuHUFrWzOsd,iv:rHjYFnRpFQZNTcWtgcmrtp+TXWKeTflzAhjeXFitpnA=,tag:9VJQNchofZ2O/KPEFEcnXA==,type:comment]
                #ENC[AES256_GCM,data:qiaLmjeMdS5J63jLsaEVlMEDIBt/Ty2n8x+KaeGnxgh4XnOhNEFcA/BGxMyI9J3Wr/g4Ptrlgx0KfeuJqhpO6wE195n2YzGp,iv:NhASDj5/6UrS9XkThI8C+5oCI2EklO85sZUcqX9q4SA=,tag:87tc4mTvS6v2P0EXtYRaJg==,type:comment]
                #ENC[AES256_GCM,data:FV1ThaMn9NkRwqTMhGytUWMQQLBuSNvdwOHQ3KIQ9g==,iv:5D8HC+eZOgZTHLYlQYdLoPJSHboMpWLz15J0Q6MfHFE=,tag:XhKvvq+mj77SmXeY57XCRQ==,type:comment]
                #ENC[AES256_GCM,data:u9LlhqX2385z51XYsEedAoD0oPZSHcTRVLCUhbTHASxJpO5C47AoEU91VQ/ZdczVRtFHamN8pg==,iv:3DzNzJ3kLD/0Fb098Iyv430e+1CiSfkXX5jAIii06ZQ=,tag:wiOK8nC4UWMKENI4ggGJAA==,type:comment]
                #ENC[AES256_GCM,data:yHKXHBfxqRarg4M=,iv:x2VEhfVFVDlo7W67s/ubQk2mrueErseGrCrwX8ajL4k=,tag:Uo6CPdCyogERdgk6hIb8EQ==,type:comment]
                #ENC[AES256_GCM,data:1+7S1MdT5iPZFcWydCr/tUVZCwuzgLW8nvHY,iv:0CCXuWi+j07URO6bs31m9VndaNnyTns5wb2StYZqfXo=,tag:tg7LAyWr7lQuupvpn8a0Pg==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/5a15f4ad-7248-4011-968c-1595888ce007
          created_at: "2025-02-24T23:07:14Z"
          enc: AQICAHjfGHM7bUxlerxo7xU+GaCIqAiNcpUP+WvvZVLCeHISxQFrxpi+7GjO5iuq/K0/5uMXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVQ4lzulbv657bhk1AgEQgDvOF/5L9BJEaPq26BFR5G4JaT3oTQjCD/knL6EMUMZ45Pxsd1VHrznimq+bNAFf1JtYZqFWrugOpPuONg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T20:44:10Z"
    mac: ENC[AES256_GCM,data:e6PhhsCUU6fI511T8JFTyRFK3uaSm3ob4EHHo33vnuIhwVUDI5Us5y+eiSJXXsN+lrB8dXTpErIPh1h+cqMbkU+hu9/RL/aSJqPNlQpleVmcp4EOegCdzBat4S0GB+Ox4VaBs/7/fCZxuzapYY2OCs/dW5QO6Qzwf95dATAp5wo=,iv:nbdGPCJwdeRe/ahfkjaUQATIUS8SWE/iqF2GlIYwiwk=,tag:9qkZ21JTYK/7Ha6VVjgljg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
