jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:6OlJXmd1C5YKWIlGlQNJzayD09XzP8x/Xg==,iv:qpteRmzVzImU+NWtDR6E7BQS7IfIKG8lMH7qLqksLPM=,tag:e6mqHDiJCSMaYiXfbsMmAw==,type:str]
                #ENC[AES256_GCM,data:wodqMTZYhvbFdVwI51aO,iv:aaFLyTBbSN4T+C5jDebp0qQwsP/pOmtzDodu8ojP67A=,tag:HorsB/378qq5MhVl3R0hPw==,type:comment]
                #ENC[AES256_GCM,data:Trme+LYRW37xdvVYJ8fUMyzmoRC47wSs6GUrQ3TvfrE9wyHfWLLE1nWOikV9BDErxehiM4WR99McreHg+a83hjcP2yJKVedX,iv:w9vGfF7YcfKPT/HOHtfyFnHdMxj6aSt4dTvMmLf43L0=,tag:45XEDYYdtRZl+/aU9vk+Yg==,type:comment]
                #ENC[AES256_GCM,data:FXrHaivlLtEqRVfDMS6LhEjBO6jVXiYSeKhCNfQJhA==,iv:KA4JRHnCE+sS+E5eGTQsZ2C45OEKgeOp/NkjVZK8CqM=,tag:H3BFzbdOujC1qjyNS9yskA==,type:comment]
                #ENC[AES256_GCM,data:qMr5W19otv7rBelr9POGhQ8gf+3/mrJlPSJVkBOPPQCVAq4BuIB7G9+sqGdUQscrrjhZlBFX7w==,iv:KUvW3FIDv/TpMv1MVrjyxoQo4dWS4GX6B4T+MxboGxE=,tag:fvB7vAJUV8ZiGo3cK/pURg==,type:comment]
                #ENC[AES256_GCM,data:/BAZ1XCB835rDbs=,iv:eP+kN1E6oTJOW0WUu2ATdU8fv80zL55EpzqqmY2ho/A=,tag:AaC2ycLGAUBmJvOwrP1IuA==,type:comment]
                #ENC[AES256_GCM,data:lef50zVhUL/hFu2ebKBa8Z/GQJMneTpudSg3,iv:8+1p5N0urgGXXXObeiuwG7wxqS5ZdWaqZ04Kuixpyb8=,tag:66h65H2w44YIEXAPeDlbgA==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/9c28321e-eb64-49d9-a0f9-30c50f9b0214
          created_at: "2025-03-11T18:40:32Z"
          enc: AQICAHhndPrOpg8p3dk1k+xmm13F+N1/BavujEV499t6yDc5OAEi+lYeUc5dSwFfUz27ILIYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMS5xOmZbYn4yBcZwGAgEQgDvyko2l3winr7n++iXqAARxV61wk0IxNtzs/V8EBIqozNgE58IeJr9hfZqX3rnyeCnNERnY+PaAOFKaTg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-11T18:40:32Z"
    mac: ENC[AES256_GCM,data:ywNpNzCG4EZcMRh2tY/LM9YcjMjVguMIVkL6jzb1cl+9jenRpjFJyhORUIKpcQXsYtHu5efXhAWKhUR7J57LZEEqufXOnFX+uKLjbB4JZpbz9oXHp/XQVNoo4Y8TgGoXoiaVDP10HV+gjk/P5xuQgPyYhXFc0yk4awfQo2X2MuI=,iv:Iznw7pF6Ur9C4qhBYV+bocxvysKsQtyIvYLdrqdIFmo=,tag:LcxTa5qklAIa4vyl0N3CcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
