jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:yjIrSj5Jb1kMKD25NxmcXSFyfw+rlVXnqA==,iv:iLLeUDd7CiNwqsOQHqbjuLnvFzRCv0RaMeV0RUWoHzU=,tag:q74tLPXHXrWgdxeG4qKmoA==,type:str]
                #ENC[AES256_GCM,data:x49OStcy5am/Rtct+y8Q,iv:/sLPoJ+U6J1BQGMX4535O1szQHoNsSlRbr4Zh/hXi2E=,tag:tkdn6hIffIlu4/dSkx4Esg==,type:comment]
                #ENC[AES256_GCM,data:6z3i5x0G+TU5CMCDwfdJ7GiGXMv+YxCXUdkinbJSsnnav0D+hV5H6UBDJ7+UW/nGimWcLgoh9eBoglkRnjzEBuRA0vsp83tA,iv:jIZ+PQUNwradQzW2pyYvEMQpc8Cf5lQE6OBiJKQFagc=,tag:KASbCCQJxFKNlT7TGDdL/A==,type:comment]
                #ENC[AES256_GCM,data:YOsAV1T50PZ4sab8SrUEB1UMMfVA42UNIX1+SGBA4g==,iv:DuW2y1l1d5Yw7sZuFYyo8bxDcp+TmJq3LMJa1q6XLmQ=,tag:A23nf/apbwMFokHe2sIFkA==,type:comment]
                #ENC[AES256_GCM,data:73zM2kMWgWnW/1Qrj/4Q2wFPJguE7sKSfIUGkAI1PLvyZs52rR5Hyj35i3xPIv2/2rn0eW6J6w==,iv:+euUgqXzCCM6XPlT2OMWGHHWZAHSjOPqd08Afql63Sc=,tag:l/M/v2bN0vOSTNeynHBOCQ==,type:comment]
                #ENC[AES256_GCM,data:+7lP7G2YbEb03P4=,iv:GVtzSPKjyn8pUjNagDiXYneZDgG/Qavl3kf1W5E+K6E=,tag:PJUW57ZvfR0HCrAUPLwYiA==,type:comment]
                #ENC[AES256_GCM,data:lSz/mCtvu/XRYRSLjjYE5PJ8KnDY3kX/FVVI,iv:+OXaU31cGd7U43TEClmnHrKUquQbQ2TsoHyFe9BSuM0=,tag:Ygzm29Gn8zuJjkc+ZxbhmQ==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/5a15f4ad-7248-4011-968c-1595888ce007
          created_at: "2025-02-24T23:08:36Z"
          enc: AQICAHjfGHM7bUxlerxo7xU+GaCIqAiNcpUP+WvvZVLCeHISxQHbGVIgAS68UMFaXHGxBpTPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjxySCO/JLc4afEdSAgEQgDt9hl3j8Hl+Gv3s49BXW/zuMCMouARdJCqo43xYU8WLhRRVZORDk+/sfZrph9/I7ub5HFcy04hs8SnmtA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-27T20:44:25Z"
    mac: ENC[AES256_GCM,data:UwoODFM6mZiuCwpQhdzXSMgniGO2XQ8giaTb6+NVKeZiRwxORxVIeMcykOgaVhULzXuVga7Pia28gywVNIQZ+AWcebaWZbjsqAK3X+VWJGkYxWJoxfVbjyGJMWfnwlkTlG2K3RQAghEP4UKD4TEdglEmffp3notWKMJUKnWIax8=,iv:G13gb43t4ZigHTY70NEAX3h4Zn8BeHnBdmw34ebgoBg=,tag:TpAo+XiNmu1flYEDJeFXgA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
