# add labels for code changes
python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'

R-code:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.R'
      - '**/*.r'

bash:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.sh'
      - '**/*.bash'
      - '**/postBuild'

dockerfile:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'

# add labels for non-singleuser image config changes
configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'configs/**'
      - '**/requirements.in'
      - '**/dev-requirements.txt'
      - '**/requirements.txt'
      - '**/runtime.txt'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'

template:
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/template/**'

# changes to hub images
hub-images:
  - changed-files:
    - any-glob-to-any-file:
      - 'images/**'

# images
images:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.png'
      - '**/*.svg'

# add labels to docs
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.txt'
      - '!**/apt.txt'
      - '!**/dev-requirements.txt'
      - '!**/requirements.txt'
      - '!**/runtime.txt'
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE'

# add build-infra label to any .github changes
build-infra:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '!.github/ISSUE_TEMPLATE/**'
      - '.gitignore'

issue-templates:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/ISSUE_TEMPLATE/**'

# helm chart infra
helm-config:
  - changed-files:
    - any-glob-to-any-file:
      - 'chartpress.yaml'
      - '**/Chart.yaml'
      - 'support/*.yaml'
      - 'hub/*.yaml'
      - '**/.helmignore'

# support systems
support-deployment:
  - changed-files:
    - any-glob-to-any-file:
      - 'support/**'

# grafana panel backups
grafana:
  - changed-files:
    - any-glob-to-any-file:
      - 'vendor/grafana/**'

# jupyterhub deployment
jupyterhub-deployment:
  - changed-files:
    - any-glob-to-any-file:
      - 'hub/**'

# add hub-specific labels for deployment changes
'hub: dvc':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/dvc/**'
'hub: jupyter':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/jupyter/**'
'hub: csuf':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csuf/**'
'hub: csum':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csum/**'
'hub: csulb':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csulb/**'
'hub: csueb':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csueb/**'
'hub: csus':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csus/**'
'hub: csumb':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csumb/**'
'hub: csula':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csula/**'
'hub: csusj':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csusj/**'
'hub: folsomlake':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/folsomlake/**'
'hub: fresno':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/fresno/**'
'hub: csub':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csub/**'
'hub: ucsc':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/ucsc/**'
'hub: usc':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/usc/**'
'hub: csufresno':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csufresno/**'
'hub: csun':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csun/**'
'hub: chicostate':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/chicostate/**'
'hub: csusonoma':
  - changed-files:
    - any-glob-to-any-file:
      - 'deployments/csusonoma/**'
# 'hub: demo':
#   - changed-files:
#     - any-glob-to-any-file:
#       - 'deployments/demo/**'
# 'hub: sage':
#   - changed-files:
#     - any-glob-to-any-file:
#       - 'deployments/sage/**'
# 'hub: gpu-demo':
#   - changed-files:
#     - any-glob-to-any-file:
#       - 'deployments/gpu-demo/**'
