# add labels for code changes
python:
  - '**/*.py'
R-code:
  - '**/*.R'
  - '**/*.r'
bash:
  - '**/*.sh'
  - '**/*.bash'
  - '**/postBuild'
dockerfile:
  - '**/Dockerfile'

# add labels for non-singleuser image config changes
configuration:
  - 'configs/**'
  - '**/requirements.in'
  - '**/dev-requirements.txt'
  - '**/requirements.txt'
  - '**/runtime.txt'
  - '**/*.json'
  - '**/*.yml'
  - '**/*.yaml'

template:
  - 'deployments/template/**'

# changes to hub images
hub-images:
  - 'images/**'

# images
images:
  - '**/*.png'
  - '**/*.svg'

# add labels to docs
documentation:
  - any: ['**/*.txt',  '!**/apt.txt', '!**/dev-requirements.txt', '!**/requirements.txt', '!**/runtime.txt']
  - 'docs/**'
  - '**/*.md'
  - 'LICENSE'

# add build-infra label to any .github or circleci changes
build-infra:
  - any: ['.github/**', '!.github/ISSUE_TEMPLATE/**']
  - '.gitignore'

issue-templates:
  - '.github/ISSUE_TEMPLATE/**'

# helm chart infra
helm-config:
  - 'chartpress.yaml'
  - '**/Chart.yaml'
  - 'support/*.yaml'
  - 'hub/*.yaml'
  - '**/.helmignore'

# support systems
support-deployment:
  - 'support/**'

# jupyterhub-home-nfs chart
jupyterhub-home-nfs-deployment:
  - 'jupyterhub-home-nfs/**'

# grafana panel backups
grafana:
  - 'vendor/grafana/**'

# jupyterhub deployment
jupyterhub-deployment:
  - 'hub/**'

# add hub-specific labels for deployment changes
'hub: dvc':
  - 'deployments/dvc/**'
'hub: jupyter':
  - 'deployments/jupyter/**'
'hub: csuf':
  - 'deployments/csuf/**'
'hub: csum':
  - 'deployments/csum/**'
'hub: csulb':
  - 'deployments/csulb/**'
'hub: csueb':
  - 'deployments/csueb/**'
'hub: csus':
  - 'deployments/csus/**'
'hub: csumb':
  - 'deployments/csumb/**'
'hub: csula':
  - 'deployments/csula/**'
'hub: csusj':
  - 'deployments/csusj/**'
'hub: folsomlake':
  - 'deployments/folsomlake/**'
'hub: fresno':
  - 'deployments/fresno/**'
'hub: csub':
  - 'deployments/csub/**'
'hub: ucsc':
  - 'deployments/ucsc/**'
'hub: usc':
  - 'deployments/usc/**'
'hub: csufresno':
  - 'deployments/csufresno/**'
'hub: csun':
  - 'deployments/csun/**'
'hub: chicostate':
  - 'deployments/chicostate/**'
'hub: csusonoma':
  - 'deployments/csusonoma/**'
# 'hub: demo':
#   - 'deployments/demo/**'
# 'hub: sage':
#   - 'deployments/sage/**'
# 'hub: gpu-demo':
#   - 'deployments/gpu-demo/**'
