creation_rules:
  - path_regex: deployments/.*/secrets/.*
    gcp_kms: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
  - path_regex: support/secrets.yaml
    gcp_kms: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
