jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:7//zTEJqYq8i0LSLqiC4C5aA0WDIugxSjmcoWddplxDAIHeQF9WUEqWBNap+n62M/N1L,iv:5TFH3TfWIqMPCEIuBqgjrKfVSUTRjYn8P6PiIlZ5gvw=,tag:+7c5unLkBoc/Dr8hKAutkA==,type:str]
                client_secret: ENC[AES256_GCM,data:6EyYtT0Q5gVhA9rhvw9mhbgos1sz5rMYydjWSWvQuxOGH27qemr958AskLcbN5jiQrKO2x9kP8TKHS4ZfnnM5bipKsHqEUn8P/GdWHUkC4wktVoZPio=,iv:Dw/EJspJ1ES4GqvilkWH1AN8ff2S+4FL9eghl52NCZc=,tag:UrcqziOeDGo6RmY9oHtSMQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-16T18:00:50Z"
          enc: CiQA471gatStZ3BiCSuF3EsOKLcwfrX7TrQnR/q5v0dvzO56zMMSSQA0woZQKtY1TO3gYXrImTSIQmSUIZ5TVvvznDuTJKEDDZQrEg3dBNuMY4nzOwIG6j0AYGMg1KuaV9ITBFzDhE10ZpLzeRpZDrU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-16T18:00:50Z"
    mac: ENC[AES256_GCM,data:QiQFJMvuMd7oy4mIZNDws8JoAkscMLFEI5QJZSuIMpz7ZtCp9FsabyB5q3bm6HSOcVeOvux1CSogN92YSEDRro6vsZ6vtFLgYVmcmvvdxxhcCfWbWOCg5CiDRP//4iSb9AyJBYqdYTROgzuldJ4PLIgU7+jabiYrKb3ap7539eU=,iv:GdhH4Ft6cFx0AzOTJU4jRhucN87B+S+DwHDyxTfkcu0=,tag:JEOZp5NzFGM/5Rr20XV7vw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
