jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:DyLGBWmzNbU76YxkmI0nS0VMj7lrevApoUUMtOHhoNarRb8U8qCAaB/xUQFYlb5/AqA=,iv:FkEa8JG9iY7gEolvoHLBHnT+P+yzHoyg2m901c+4gPY=,tag:TeRHk3nzHFP3LGzbbFYIsg==,type:str]
                client_secret: ENC[AES256_GCM,data:UeQ8+l9dAT+ou4HHWho0ntgA5N+q1yla+ddTi9Z/66c74hN5Ra/d80TOjGIzIgTLQKsedSTsdxzxCyA07hulVaaqtGN1Uzo3Z8PzCN4FSepefBR6o7s=,iv:EpfmdKg/eb1pb2YsywWlf3gJFt6WCrluns34nnR+I5g=,tag:XKcdA6oPq4/3YwwH/ucp/w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-16T18:00:50Z"
          enc: CiQA471gaolayfgOmZuQZ3mPNvd8fkrQQ8Ibp0tkdh8xHihUvsoSSQA0woZQYhMc4rSCRvC75smSOfS6wYTTzwpg509qyV/p2mm8TRpdr92M/XMZPGZUbhNDhqm9MrNqUw5sgkRwLoudi0xLuD7SLRE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-16T18:00:51Z"
    mac: ENC[AES256_GCM,data:dJ9gS9Jg12TbSOXohaSCIfSfjafvhvcuNe4TNouhYmxxIfPqCv+KphvDeMTrh9NE/xH+dLAHun/XCXAi732msQ/AN+PGpKuM8JvxNhnb0R1dXAC6qpsD3IE/8VKjrhzaiIjCBTTyeP1ZHlvFZAiKWxQCJGrnlNAbXhGgH7HG12o=,iv:tCjP9Z2ZYK7Pq+dbPMiXzPCJzbHe8P9hf8BbeMgdgjc=,tag:24rnBgzG4V0Pr7KX7TJemw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
