nfsPVC:
  nfs:
    shareName: shares/ucla/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - ucla.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - ucla.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://ucla.jupyter.cal-icor.org/hub/oauth_callback
