jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:k2wXrTFL2t/Z+2xRawXHu5JQDhRLfWKRApO/zI08RK5EYhCPFOF0uNOE1QfWtH7UjiaP,iv:rLlk5aGblIOZHnoBQxW/Cdz0Jxp7mrd1sPHotdPNl9Y=,tag:k2P+1u51V2TRmKrDBaP/Mw==,type:str]
                client_secret: ENC[AES256_GCM,data:gYH6l51OQHdq3hLuwaOpITnn1YLiEABHSqzXN7gsBg7eGOh1XMj7bW0nZF2D6l9kGu9lcCNVdsr+CzmATbgxPhEvoDUC7850176OMxe7kw3wJdApZ+Q=,iv:G54xiHxbm0U54SlflZM4dvjuIRcvjVRWJK7WXJJitTs=,tag:u6r9YsvKN1LHdOAI6k1fkQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-27T23:54:23Z"
          enc: CiQA471gasdbmkycrFrMP4xff8tfs5Oblw7QF109n2cZ/tGtjCQSSQA0woZQzqPm6gCHhQHEp+kXrgPyUkHCUezlS4RVTJ314RhaQj7i2LE8Tj207Mm9xXgFE6YsJnt83L31DsmbWF0uCqnagVHo+HA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-27T23:54:24Z"
    mac: ENC[AES256_GCM,data:2g67XmFrQDr1bVdBXLeHTL3+Tqafm79K6mMt5UbNIJRSw1L02CQGLstc4B94R17h/gvOmfE5UZh2tm6aJbBz66YM4a8I2O2alDDpYnc1IfW2uK/f/P+hvOer/OWW4+5+m8+Kxwas+CIuQZjLHemoHRb7VDEdj0bJwmqGp4HUhpo=,iv:v3v/vjnpvrFHQqGaEQHixVAWVudUhjCM2qYR1bGdqUQ=,tag:l4Yoxx5GUC0FAqm2lZTpwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
