jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:XpjTALrvasOxdzs07HXAHQuqTUU6ro5t9Hz2CCIF6nQs2pNEpNhk49McpEcF8RswcXhc,iv:eoPkvA17hs2q+qCz4CtJ6EhXu1worQhEqkR54BhDVzg=,tag:Glebnmtkl9+mXzuGIIMceQ==,type:str]
                client_secret: ENC[AES256_GCM,data:cHRO4zeGvOhWhLx1cdJ52WFsroORa0lMwBHq+8OXlQMdAUSVbIma0fn2IYkraqbuUE/B1UCbw1M4hqZ8ovjNDWlLzM8/bcGxPCgFUJbtfW62vgO35e4=,iv:2BOzaTflyjg1hPeXcsBTeSstYuwosUAKaudyG72yeAs=,tag:HRIKIG1DpJwMAnCbEhJ2EA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:JEW+ZS+IPmR5bs4TyZNWt2elR8jQmZp4lgBVXPGz5/p+vrY5E3+86CKnEbqA5B85xfGxr8Ol9H40sxuui6JAAA==,iv:LhXRCTl6/Sk8Okyl8YbvkQxBiSAax0y352MbQD83gzc=,tag:Tl+vdeZFQn3L9gRw51iXAA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:21Z"
          enc: CiQA471garcPpF+boZFooJjLK+nyQwSICV7x8hf4C6ndRC57QccSSQAtv98xllYIphBYXOUAlXrF4sqd3TiAdpzowg+sEAUNfDIUMdWrxfCDJ0Zq7hLzXevWqMnVUY2Cwug5fb8UjAAEzy2X7tPga6E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:22Z"
    mac: ENC[AES256_GCM,data:ib/vb1ED3J+8UYrWqupxUiAOMTMrIGgJNXFMQmQMdQEjL/WVZf64FjHqfLBEqwc6p/GFzwhw5CgYw9FfMZYzbVqug3Pd7svyXR7wdaD+px02lsL92SZtbEu11WIjhNxOJoHerSXodPQQeFzkgBXNFlUbEKxtiBlMP4BJ12ft2mc=,iv:CsMYqMf9SXrdqsuOc7PbJsVqJIyn02Am0+VjTYDRmW8=,tag:Ks9UAzqbItmWutIJHNIL3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
