jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:sAfCM1rS/t3bFPgKJnAd/o+Os3Mbds0mhdcBJbykl8OHTnneSkR38fiOKihkTvIqG0w=,iv:L/S+SKVNaFlfDZpSA4AM7zvkd3Gk1xaNownd2NiT9xI=,tag:jR7YouNqU3kVrxpikID96A==,type:str]
                client_secret: ENC[AES256_GCM,data:znfDhVcgo/qlIObWeRud+FBFf8fuDPgG9AvHHErpp6Xt0HLjkx7V2DcBOu3KGqLC/5Nr+/Ks4X0nsZyvFS8LzftiBPykAB3fK7nXdmrX23Xt/REx8EA=,iv:mCa8KB1GgJOOaLBACn1IO1bA2HiTYhiy73GEzMnJMhY=,tag:7QUkj6ehEoEzrhEiH8+xXA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:qaPIBD3FMYPelpEnIui4FVNpUNwtNeI2rg+wwdaS4xNEQ3cOrl6PL8qPHqeC+Euz+3knylrtTjj+LN8hb/qRhQ==,iv:UEg0iruOjegIfY82zfQudj8JktAuJePMRHSJKmWoSII=,tag:kCzPsjaysHMyYtSkx/Xgmg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:23Z"
          enc: CiQA471gagpRniioHk7mE4v3t4iCqgjbUyfS3/vLiHVxFHVFSiYSSQAtv98xYVVUF1THcis+tVSb4p6ZAuUciHOvFkn48MBx2/bZAHpEyHPI+A6l/J/aj7uo3tmxBEwr27Hlh/r4jJjI3IY4aLP5oyQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:24Z"
    mac: ENC[AES256_GCM,data:WY8m4zUMhCE7kARuaXzZOk284ZxdofsxYZIha8BnByzz1X9SJi70eOixcIvz9hBTD4Jp0Y6Sppevj7QbHFGoVroot+qAx3eBqoM01Ag0oQqZ2tNvUU1I7i0P+0Obx0r7/7gYl66i6B68dYB2m3cazovLm0MbHJfg/aT5dzgkZZE=,iv:T+YLfvl28dWaWKE9vvtcfRnhGTN95iPOEz9nIbk1ijA=,tag:mq08jHuDV0f4OJ8C4DfHBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
