jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:wgpASQGfyljT4mmd7DbdtP1XtR6A903N7zcWk+5KWPgIg4G+9tNqbJ8kFjKbRQb7kpE=,iv:bVwpLIbBdHdSXn8H4BrTRKVCjPK8QIvf6z6tEmWinSI=,tag:ZdanspVsG0Btu6zQsVWMAw==,type:str]
                client_secret: ENC[AES256_GCM,data:kZPt83/Pum/km4cEn37kLytqqxkmfDI1wEQg5ulCHSeb70N/2/UrpldnzoSNn4HanxTqtuABn6zOcq1gkkxuBLwKieOZX6YAHSylElJiG5TLixyp2Js=,iv:0+kwws9f7JYnwxzO0AVjeQWJ0/hwBA8426pIkmoGIhY=,tag:cROTinCcskgeqWHwI3hs0Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-27T23:54:24Z"
          enc: CiQA471gag8QAePJM2f/pbSPP5un6XQCSxoebBvgv9JoW62IOoASSQA0woZQYMruewuVawL9YOKZiqX5WTPYvvVyDIFpTum3oXTWvHHybyaXh8THmNJsbxZW02UKSQEVpKJU3E7RNEmFntX5d/Z1T1I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-27T23:54:24Z"
    mac: ENC[AES256_GCM,data:206KxVIHW5io2ROAMaYcYrqVtId2EtnJkSt2msB4Af+kOaEeYroHiJ0MX0G15xUCVb/OcARGER6icSUeeceszOBqyedAtgeTRt03TCALdtatHzuHfsWwNyoYM8EBrdh+JXdDWVijKfjrJA+cXLEckGcF/72rpHVOkGAKGEud4q4=,iv:SyfaOkkSLVxSd0pZiZLP/1+ckIXYKDa2mQdRq8kZ5tQ=,tag:Mhf0jMDj4PUCoPrn5d3Gow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
