jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:upsx/RVZ0HAIICUV8RMNpTzc+YKU/3wf/6gr32yGetihUBSLXxXVkVTADbH8yNmu+/Oj,iv:RI6eLOy/U/CtnfAgSyU/XIwU/rB0XFS1FCcRqiagejk=,tag:jZ3GemKRv72yfeskIPYN7Q==,type:str]
                client_secret: ENC[AES256_GCM,data:WMfIoKHmWLyHT25sS80ii66OujCqvA6Cq33su86FXno6FkJ5OAlmr8tc2n49MdPDFCn7VhNw8Efbm136VqQCcE/D7zsyzs2nHioKns17w1oXzRX259E=,iv:882C4z9GyfgtDnhGn5N1tXK9H34CeFWzndagzfI1wdU=,tag:64yb+plmGbYJizKTxkassA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:LsrdAVuYtSG8R3ydrG5HiHsow5kc3401/Vww5tcG9CPfryX6xyQEXnvji+G09b8hmyDKwOFb099sz4vg/ykuFw==,iv:bzY/4dGNSdAJd0TBnHdnhLaNs2CYLhVXTEt9n//lF/4=,tag:Hh/x4BjM3Jj3LUJUtuECAQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:52Z"
          enc: CiQA471gaqgvBter40fVx/38BfJN8g8PG3UVPD/PP6owgxs+elISSQAtv98xZWubxGMFfxmc280/Tp3QC0dPZ1KjPyb8F6M2HBHlIYwbzq1otzcD2kv0E+v+fDvZ2jMVhujrtXawVGdNRWbSLY65FvA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:53Z"
    mac: ENC[AES256_GCM,data:hddpRTMiDN60A/YUF+BjFAnAqlx5WDZqHeSWCtsZ4Zeq8gC9gPcY7eNoNa7XD0EWx+aoHbWbQRFS7h/aMvKCp5l0Oz07KtW/PRFuMrPwLaBt1qsTiY5VTs6imvoc3CPDnkokZ9RfmGy4GgY42H5MS+gbDoULWPT1eV2IqfD7paY=,iv:jC+VBa0J2MBaRRy8N5irS0hvzb7W2W03TiVlbTsXw7c=,tag:JTS73Agw7AcQppQdfIUhiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
