jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:mEPhc/zyrR+DogmtbIm7fAHKw1dGY+UA6ccCYfpvjKn+lUnjvfjCStwxNzDzRd/OaWWD,iv:Mrx+3uU7u3tx+xwFq+OAr39iyNj//rDHftOLvUSft2Y=,tag:FFVxuXCAhGgK3A7kw/4jtg==,type:str]
                client_secret: ENC[AES256_GCM,data:g1sXlBFT5tHt6DoNxxucqbW4ELiJwAI7QmYaUSCIA4zBNuwMlOY7hRWYOONoCASGSiYdhCzBuCctCY5c1C5M9SpasOn2WipoR7MaSLkhEJvGDxILWhA=,iv:BPHiI+FQ3iN5L+g9UoN/7cpeZGfYMqj/HUExoi9kpMk=,tag:oi3sbF31cGCNbNOnvtnCsQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:15:19Z"
          enc: CiQA471gard4JnZa+Vc08nbYWK0flJUlETqXu5Aryeq1sSjYhl8SSAA0woZQsSbIIam4z1VIBOvThdaSGRDQkr5lss8abGgnyS7gEr5pMiwNnNvKS/p0+9sYAV19vat4gzFIc1JwFWWEhVBvokV2kQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:15:19Z"
    mac: ENC[AES256_GCM,data:OIjamknj8yBPcG16HpnDdM9btsOVKnxMO4WdhFQF352LWpjEjH4fJ/aKqjQjd7UaXWKp1yzx0nFn1nRX9cFD2qkuQuzIFb9B9APSXtBygTM5IUbHpxyhuygHwqjYye8OqWIPDGbwmRnJaZuizC1inkiVznk4/89sxc67wl2ea2Q=,iv:6RfwiR0t5gpS88xNwf9iCKazLj0C8qmtcwydpOjQ04w=,tag:nCFBc+MYPBpZkhqhLb2lHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
