jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:0+378GpG6PC4g++wgfYjLl4FJ/4bH3J1Ma6uolMBcCKyE+Lmyl2uNoRbkQkM9sscV/Xx,iv:UkqWWxh2xJ5WKh4Qc5wAmG9n+okZkjb9K64cqxU3JyM=,tag:PaHcGATCq0XTDmx578zPgw==,type:str]
                client_secret: ENC[AES256_GCM,data:ML9CSPuu5mFLzhJDaJN64jTV0/TfQPZ41l+mDrPWLhL2iXhW46Tk2zk5qZG8K22bIJAsw/pXaVVfq4Y12MejyuVVkLZJnHEg28whSz0jgWufQoJUP5o=,iv:NP8zVKHWagKatcryMyRGSuY14Qn6BQ2fd1QVYe2wVNA=,tag:x5VQ0H6LD6OWE9xyo9aSnQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:15:20Z"
          enc: CiQA471gaq/Iw7c+cvWkzhPKZdALyaahALTiYQV1U9CBenGrlBESSQA0woZQrHbkoJyXHMIiVBTKW1UWzoVOAu/1yemdZX0e4xInAp/6YLh3lYIew1Q/4oFnY6zhuSwxfBmjF9zL65FjC8gBNp4e47U=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:15:20Z"
    mac: ENC[AES256_GCM,data:WLAkfAL+O9pXr36wCmO7ZFAJZt9XCyPs8g2preBitOdEQPHUr343CqnS7zSWDGGq1s1/XeyP2Oml5k9h8yOvxf2A3tAuf9IfNPYfSAFGTnnG1QePRWbqC1GAvDzrdoALsBcyt328NMsNqe4713Ct2vjx1SJlH8Zzlq83Rye1xDo=,iv:SKKzFGvI+1ODSbsLvHppktP+t0LLxo/cXarO+EZ96Pg=,tag:B00e705R1CwgJJrw7o4y1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
