jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:fGXvF+4fIjz6iBNPlkyrcr/5RSttbVrDrUfNyj4ATxPrcIaMQwCU9268g3x1CLUXBe7x,iv:BE7KtjsM0LW/9QUZEL1PdYQ0mX4jykXsAInG1QB68Ss=,tag:/NWOxgKcYeT4Ho/hR3Q4gw==,type:str]
                client_secret: ENC[AES256_GCM,data:FhKuBZfDqXEdtRSqGyw6TZSVZkNKuB0kTk6gmhtljUQ/G1HNLAMPtJCJsr783ZDIId/qyVJ4RVKZuz0067hco8KxXOkyWeGsJAZpUpkFuryoga8p4TI=,iv:NTYvG5hQUHtQd0FuGHCx5CyZfZ95SH3uadBezYURENc=,tag:bdWVcBh2KVLgcz9YpCf95A==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:tnNXUhvbh5kfHNa8YQqM2qxDLssLmSKvVYGiUfIIyAHrqnyTFR8ExEt/yEdkSvpXxmmZS5Vq9V+0ABMyRsYQpQ==,iv:BFhONuUiBt1ZLP/ynce3e4OXWy1c/sz6XhOKd2RSogY=,tag:rV38rre44g/YWObguuv6UA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:54Z"
          enc: CiQA471gaomRV6a1I54V5gP83jcAK4m5J5IewyHUXhKBaFu2ro0SSQAtv98xTw9p76EyavXSa2V+tbE6AGisJMbgJsV17jtAS3Ogby21Zn1L3qqim2MtSON5tzb7SGnrBvrSaOS49+G1d9PPKDSf1xg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:55Z"
    mac: ENC[AES256_GCM,data:yc4jXcgL79/p1uSSpBvcVDFqn/n0+0AJ+RW+ku0TGrQpZEgheAWR6YVCh8eW10suKDRqIjw/f21MySsBoQPME2B149Tr66T8IM6U84E1wFztfHVlRDvdpVXtJOEt0RCaUAimaZjfxebVqj0M9H+GjJaiwe4odJi5I9cJZnQq784=,iv:K/eoSdRpXngxMLKq6RQR3V+ZkulPwlWPiul1d4CxkEc=,tag:16NpIzgRqtAkRYl4GQOQ2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
