nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.183.114.2

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal-ICOR Demo Hub
          logo_url: https://cal-icor.org/assets/logo-trans.png
          url: https://cal-icor.org
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2025-12-22
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - jedwin321@berkeley.edu
          - denero
          - denero@berkeley.edu
          - yijunge
          - rylo
          - sknapp
          - felder
          - balajialwar
          - gmerritt
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/java-user-image
      tag: ee5edaf8759d
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Tell code where to display GUIs
      # The VNC /desktop link must be opened already for this to work
      DISPLAY: ":1.0"
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: base-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan/shared
          subPath: _shared
          readOnly: true
    memory:
      guarantee: 2G
      limit: 2G
