nfsPVC:
  enabled: true
  nfs:
    serverIP: 34.118.238.48

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal-ICOR Demo Hub
          logo_url: https://www.cal-icor.org/images/logos/cal-icor.png
          url: https://cal-icor.org
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-06-30
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - jedwin321@berkeley.edu
          - denero
          - denero@berkeley.edu
          - yijunge
          - rylo
          - sknapp
          - felder
          - balajialwar
          - gmerritt
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-python-image
      tag: 77544a41cd51
      # name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/java-user-image
      # tag: 109b5f8ca22b
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Tell code where to display GUIs
      # The VNC /desktop link must be opened already for this to work
      DISPLAY: ":1.0"
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: user-pool-2026-07-07
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 2G
      limit: 2G
