nfsPVC:
  nfs:
    shareName: demo/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - demo.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - demo.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 1Gi
