jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:tyDkWI1MteMnnn9CrkjGMwcmkM78oqVV5ppHOqsyruXs9LvOuerk1A6izau63BV8Ldiu,iv:CM0o1IPQL+4HsdOMlawZzWks3iEu0NA6hVwimZSFm/I=,tag:CVnTm0iwowI4rP2NB03lJQ==,type:str]
                client_secret: ENC[AES256_GCM,data:MYDMuBnSP1TebYEddYSwoJoFWLL0oMpZ2htVDD5gHzBz+24nfnA+Iqq83ZcwaKphpAcC7GV+lMhEFLixlK5bU4pyOdd46SR/ZqaDfiihfJX7JEAxlKE=,iv:zbIl6MnV/BYvquhyVfEQDDQlFgH3f+dsRbx70MSj928=,tag:Lu6NezzGRDmjo+kU4wcAnA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:06:11Z"
          enc: CiQA471gau2R/jyo/5WIhXr4yTIoGPH2qCkrqzS/8eIlLa4GMPkSSQA0woZQgQqwGPtldCRfoWwaI0ErS6YNgc1vBMJ/ZIJubgHhAtypXgVBH0zFk0wJzbuAgj37FwL4cIiCWzLj2ttynLcFlY4X6Z8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:06:12Z"
    mac: ENC[AES256_GCM,data:WtMASUzCexG1l+tIuka8x/kkOMKLnoPJq1e4nLalyj/daft4i3dqRJb+GhCvtivJiIydtk/tL2UMdNG6OBUDVCsA/Yxq92fTKxTgtoZ5WYOAnPyZQpZbrDk1ZSn6Nh5LQMSE1vbakb1aMxLC1qbLm36fzihbhpxDiHYdW/ceD64=,iv:lFetZaWAzKSCMui1bWTGY6uLPpg4r020PliOq2m668Y=,tag:buQ3R9GuNbm0JZ0fw75LAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
