jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:uWSpL6bPbKEjuctkmjA3fr2KrYuhjdZODIMQeDTlc3yXEsqcDXyl/gfpMw+IV1DJXJkm,iv:8VSWeikNjBfR03t1GlSImQA6LfdD2pt+2zbHeuhZRpQ=,tag:mf/Y8VvModCpI3XSM5E46g==,type:str]
                client_secret: ENC[AES256_GCM,data:i12TLI3nnhFGl2jOTb8SOMrwswf0BIl29dceyYx/pMtGAEuLufmX27aB9bfG8YLCFiIDkExf1evCXlyXdzJ54Ph7gv3kUErimwjgEKBAZhXEt7Gy32o=,iv:dAZa4wYRzdIi5iCK1H5dx/JvEiWrNNXz3DSEjLBpikw=,tag:jM6F6D2qppdiznnHHXXJIA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:q7IbyqTKPvjgsPEooZm9Bfy8j8M0w9dW2MWhsEBxTScF1zR2njYfneRqM4xKFDjSVG5czKl14THVszfFSA//jg==,iv:Lfpqe0v+p9jW8Zy8uzhPSWvQQWVCGRLT1aJFw1on8rU=,tag:6+ZSM7JgwhuuRf+K7YOVZg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:49Z"
          enc: CiQA471gajA5fmxK0u8Q4JB4pxd7G7jkPQabLruUyfgImI0WeGISSQAtv98xMsb3PuV2I9ZdMxvU2oMlJ+w0u6JorD5ojWP9K5RK//6PBSvfVI83nI0Mp/JsA9V9jZit8I4pYoHxd4nKRMDWm2uRIk8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:49Z"
    mac: ENC[AES256_GCM,data:HfMR6FL1yTQzuweesv8TBUPq+BaK+IEo9+YhG2naCdXEgK/IpyEvwLmab1TpP/6szdAPycogwI2r3zhmcSw2jEgm9ggfXKRv6KpnRdq3KqKFFDj58Vkq/W/QtyfD3Fox+VdAzvxNrhtZA4FWnNYLh5wnzGbd0hE/wlEAno+J/Iw=,iv:fDo/6dED6Xr35B646XW5Ha9t3wvrf35wLnMz/MWP9JY=,tag:yHU5/pibF6f65iLrhXt3mQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
