jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:8Mcds3rhhl07P5s3oGFFz142wC+M749q5r2bzmIcznpyY3tXfKJWjZsJaeIvVTXZGlTD,iv:OcHl6SQrYtA23u/HJaPmb05bvRxfbmb2Z/zeibiSdGs=,tag:Am3KifP2gs64hmNMGXHWxg==,type:str]
                client_secret: ENC[AES256_GCM,data:9m09uJ9TtfORr6w+7GAq8Bss1+euYVpR8zuEa1kDG8lAA/bwlwIkXyz3N/u5oPI94pbHCdJL2khI3eY6hxYRgooc1inK4VBtANjL4FgFrRVFoOxWv38=,iv:38lGZ+OhhC9IFzt0RM4EI1UrNgG4vuiMQZkEQBQ+NrQ=,tag:dKs3TLA5TwWIwP+dkegeLg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:2M/RDgUf5lUwW24+62MTumZjnq/qFliW83W1QPNbDBhs2AyHMc0JVPLcuE+AwsNl7ZLd9DU2JOytI3IL1T3Enw==,iv:dcA9dwwqOkgqxADZ+S8gecwGvQYmhnLHI9zXVtTTEtU=,tag:q7NrQHXCy/MQ8pBOMxZ9Cw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:51Z"
          enc: CiQA471gaqaey2lnzzJubf6qLl87SAu8XXh6dvJcsSB7m2hz+1wSSQAtv98xNOtxJCYgcKzpq7S9Es1jUPcGAnCYcvYUZskzGM8ZsTI1RWuplJ53PNSU1O8qA4tYkhvfNm52hZDkaRyQv+jGWopjPIU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:51Z"
    mac: ENC[AES256_GCM,data:Mmtdd5uXhTnPDzSsipzdaBXEEwN/BFQjV8griT7+8cF+JpTGim24U4fXVWf5bkABCrd0XcFc5GOinfCyqOeutHMswEqasXbb5tOLv9L3whUllIOpzGMseCBzyIeA2mkgW6luZ2mzMzZcaiV8gRSlrfV848oWKiWtxT8ZV2wx/cc=,iv:zwNFEB+64XfwbH9JmnjngKCyHUTbgYd4zym5HMty+hk=,tag:/FpmfQGa8vHM3pXv2H1zNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
