jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:UvtqsjGQ1aReoyy8ViFfe6EWQdFCgsXgnT8SyzblBJ2C0qf+0ivRQQjlVQ9cqudUIMVU,iv:EgUAJAmoprhLsqaJA8DG35nwlBQhyQZTP9TfdmkbSVE=,tag:WNWnfLuyLCF8Ff5K1kf92g==,type:str]
                client_secret: ENC[AES256_GCM,data:pqo7CNuB/K+WlbRVMD/I6+bA1HgNGffwBKl/Jh4zDj5RTVUjOs9cLHTNXn5v/OlrzCX2OqiCP/XQwklfTdcPR+T9QO3xcU4KlP+ohpd+Th27VMt09CA=,iv:MNXblxmIYynl0W5rjUyFi6JVNMGeZn9a2ReqE1Ei3Jw=,tag:esRH1RYMXEBvSW5MakVeCQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:06:12Z"
          enc: CiQA471gatf6D9fp4f0rdT1p/KgmK7aZZVYso1mzyS0SbL24l6USSQA0woZQyLWn+IJWaX27vBq+BlI5aUu5EjIOZQzDnwTbag+vJDqm4/63AOzHY38x1o17p/gd7f8n4VRfrfkexORqZXgrA5rFxGI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:06:12Z"
    mac: ENC[AES256_GCM,data:eBilgizyTbIHrSS71XfM7nmDk847hVTp22XvGWdiA9JNxJwJYPFOSZrDaE8CFqXpqBwdhQR09b7X4WtK7tPWYopUnYOgnYLh5saGigeiUuzAf4i0dNjlAkBGE0OBKULcxn64qvugoMlu93FntkJXDHU5EFc7w1RGKLtesEHjW1I=,iv:ULEpVYCm1L9gK2uyL42Grf64Pawr7G9DhlCZ6ASzCDw=,tag:8CF+L4R1GspkFCdoBTwCXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
