jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:esf/sfF0K0AmjeptUggs2PdqeyTZFGTEtkNdDXjmB+olCV3BCTkmU5NDx6uH93wkG0c=,iv:3EzlfRWFt5B8XNDiucS15rZpVlOpSj1M19HVg5uFKks=,tag:TMz1BoBICzrBg9yf7SShvw==,type:str]
                client_secret: ENC[AES256_GCM,data:YXK5qOFgIGNn5/UpU88luOLQl955qBy+Y22hafouUVgBPSMedGTONygLrSA/y279J7X9uOHKkDcIAVY2mDT/8Stx6MG92V0sebPUjuChsMrhQzX3I2g=,iv:nsmCrDCpMAB4slj7vMXlg8csmw8iuryNDg1ehkG5QZA=,tag:VeGnSj9q8ksuV0bVAjk5Jg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:03:28Z"
          enc: CiQA471gauemJINaC63pU1Vjd4s1sWQJKJNHQQoE7DZiPh6BhjQSSQA0woZQGJINmDcr7QBPnB/L1htWlRxlf4kQrbxt8Wtk1oH3uvTLwaBOmIdYxTSVnxM0wv0OdciEocgc+0YyCzy7W1aRQFQQPUw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:03:28Z"
    mac: ENC[AES256_GCM,data:rHW0QkAuIbcZlJOvIQ7+/YlJn5iq3d/yxwkn2eY7uZc9+Nhht+4tpx2xBI4RNgbtOELTSX2zSh6Trlc25Lbg4QD/k8EKpbfRy/VhsMJUh+U5nx01L/1TzxICMI2Mfi0cXOXymgSNYMNdFEWSX7i0luKvoSnTOUAaoF90glINX/8=,iv:FygxCxq3O9o3M/gEvMzamg3hjI0Pg3xqlFfpBQlKIYg=,tag:mDxPOkrSBNxv69Lj6E3H4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
