jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:FWOPLkC5PmMsx8FpwpLJrcmBtD1FCInmZ41/7ksQK3gxKFHaRPp1EG25rgZgrSW6dAk=,iv:m6rmfx+iFEzHoHq4ImR9AbEm8XSCgEOilzQqjM698eY=,tag:1oPgCfX2QxdEMuDNB96KRw==,type:str]
                client_secret: ENC[AES256_GCM,data:tOqRkysxCuaIb0LOsUqnj4rLmexEoj+EACS6D5BRVjwBWwClJiCmpwIfDU7wNcHqKQiZAVr7Sb6XF1SK7ZxxpsVZglcN6Aa34DNOaBiMx2gVAUYTH3Q=,iv:PCVG/wK5Itu/mJSZZXaf+JiMTsyfjOpJSMZGW7BIZ4I=,tag:XhofUEV6dooWFKmrxdTlQA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:5cp7G44kVTGlPflsPW7qZlDTBtjWi/RgyWRKpC0bKS1w4KdX6C8gsHFEnzaheV3GbH426wXrAGkJiIB/JzdSag==,iv:cFj9TmIcbvT5ZliMi/8S4wgXvE7a13BFNQskctYJ598=,tag:WEo3tLwzouiaji1vI2Bq5w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:41Z"
          enc: CiQA471gaoQ7ewc0zUsJo43uOfkmLmQFnhE9i2Yq1znAIUcZVjgSSQAtv98xz9AZxXG3WEDeoUZvPWIGu8N+iX7FwyiRn6zoCS67mhXD6KyhRro7ltfraPRJlHGvCr77AXxch1+v20iCIozrrjAYZh8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:42Z"
    mac: ENC[AES256_GCM,data:Y/xJpZPN0ftjJ92p8fzItMjZdahYEtE92fmYHTn2bGBS4qxf70YFL8LZw4pvThRC2cFMCUYkByyblF50TXvpk//CKXo3AIxDnMMYoh0QCUQFupvB27RfwcAT4FNhggq8mw/LIR60u7BiSgsra2PfWEY6QuwHx12qKf+9QOglOB8=,iv:3OZ9vMd2XGfYvnEzMVvMBKYXXk5a2AlSEnAbTnU7Bok=,tag:+oLFLvSd7wej4qu1FJ75hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
