jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:RllvHvzcwzGf1qLP5f3q8f5SlpEPBYwCOMcAmTVqBoOERMiHNZkZjoGhE26JLQN/d0Nv,iv:qUeY+xT0EBDpcan1cgSXKtRg1hTKb2tsIRL03toZLp8=,tag:sNWr1uFIgf5tZMIoRQF26w==,type:str]
                client_secret: ENC[AES256_GCM,data:aPYhw2WqA2ttsTjoW/AEUs0yOrDTfikLmspAj5QLdfcKfKHpJauTFQRT06s00ZY8TJzvetku65HZzkcRatKkz3jZUlrzr9gs7aGSzNagQCJvBqygvng=,iv:Hb5rN+1ZHwHe/Wb/BiDIpZRGya+Oa+UBFqJDMCgkbSY=,tag:NO2eSTSqZTObCcZv7P00oA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:03:28Z"
          enc: CiQA471gamV2uRA+Ohc87k15/w5Z3cCvCuvXyI2W51gsmNTAT4gSSQA0woZQZijKm69aiasdI1JI8iWMnRXdJQYnZb5h84eNvOyc1RKVxuPPwXhT0two7PL8hTyOQ+mYO7eFhte++p3K3q4TGCyDDp8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:03:28Z"
    mac: ENC[AES256_GCM,data:mvGxN8PEUpPflEdLauhf1MgwUaia+vmYAk1rkgtCmaFM5I80HBqru3iZDwIu3YcR3HJf1lmpcKfEFk1Aj1c9qWMrjdhHLOQlHyIe/z+4uIPELHxBmhCHUWD58WlA4awJiZsYO1dPDpuP1E5TTFcLiYKD0/Oc8guE05jV6AhHVNg=,iv:8yeYOIC9e6JQq5J7ypWmEuYlcodLcDkQiwpIgtYYbYE=,tag:3igIw3vq7B6Sj+e+eHVjOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
