jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:3Jh7XECBY95VwJFEJGJipUF/xGzHkrsdD6CvPtM9bfxRv3Br7MuKTdPlQb62GzaIIWIS,iv:q+9E3aV98qCaqeY2i9/VuX5cPvrYHVfZzzO/N9ZSsJU=,tag:sifD7l0A/N5CZib93zd+XA==,type:str]
                client_secret: ENC[AES256_GCM,data:ZisZCw2LB6NL1pM1W82G9p1h2ml1KtiSEFLyeRmttOnep6tQX7l4RjKF/kxaW4SsGKk7vWaZ0ctRA4WuoK6Nv17p3ze42Ka+lAS9fAikLdl0+jgQtwk=,iv:+B/uwX7AIbWAwvNK8d2n8wduPexmlrg4UXL6mi8Fsp8=,tag:VuVb526pPHrswwF5h1aC2Q==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:qpnnfq9MZWegjzcK4bYuyFVc/U6X4aOIABksaVHBwmGAM9DD1ScRyvLgu1PMnkyKelL3ZQX7qKV1ferUIsA+UQ==,iv:a3Is7qolUBuRbQJjk7jG6OU34+2usbnuDCpnyf1XMLY=,tag:/EBzHQ9t7pxXkQO29s+hyA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:43Z"
          enc: CiQA471ganMcl8Qt5BRdVlPsbLfqaAeRIhkomZ3fIGN1drDT3D0SSQAtv98xdWqvT7LE5MDXtidQ/W2E0ly5j5WZZ/9RmLHFlumhGRYuh3SPxWtXX5zp9XweRgrjrgCPlBI1Z7aV6FF5kqbdw8E3n1o=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:44Z"
    mac: ENC[AES256_GCM,data:I71F6pjumv3OHxanqGtXYSQ5KOm+EiZoBH9qR+NoaoPoN2Mqt9JPDfMTY+QsaNDsbyE4FjU8gl4xDeMjAexHC54ltjV2ahCEonXwHjRLyjmwhWSNW6hhfd8daz+6BZDEOxsins772nmeH7iK4eciCsDeVuMmR0Ye+WhUZcn0Zuk=,iv:/j6Gajvr2RYBGaIKh3rguigToac6tfNBcFSAms7fXdY=,tag:48KZUIXymfaiWKcKEHiHFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
