jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:x+WLxpBQqCOebZINUEmZCSvm6crDN6O6PQP8gAlpj72JAwYg/r0wmp+9rHxBPSOE5RtR,iv:X9ay0GQPm3jBkLuAa9YWgC/FZdwqc7bJgT3xBmVS1io=,tag:gk96Qf/E+f8EKQ/918wQ6Q==,type:str]
                client_secret: ENC[AES256_GCM,data:KCwyGqv42RkYO4CRUy3LzenxovWi3t+MQIWIltArPHMyQl2tQ2mew9p6zPK39LinB9zyOZGzowvK8RR0WzLHM+WQKDrf9lBRG6r5y7wg/Baf5Bl5Q3o=,iv:I1w9KlSc7B8R5w7DLX09975QofUAwcp3+up2mJDeZG8=,tag:mz2bubgES5rnCCOZ54cAZQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-26T23:41:44Z"
          enc: CiQA471gasrqRME0MIIIKncEtxqz49PWCuS7EhcJ3qiU+WCGd+4SSQA0woZQIdn4aMbQ04tByHrjwNwGmNUNsxLEm/RIefNTIm/92CX6gZBYfyIGpU5LlkpzaUKvWLqUX/kKV8RP0W+V4qq/WSuDvDc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-26T23:41:44Z"
    mac: ENC[AES256_GCM,data:qwwqSMyKmwXQYe/ZfZOm/0zNBbAKotAZrPQx8tBQvAT33cNbJ46fBh0FBELFHAzs+YiWZqQtcgGhXyaHHDXmUYRys8hrSH2MFuwdjSrK02Ifd4IWH0xVULETBd1FanA3vDdKPlwOhASQJ/QOqkVVWzgy837rtM+OEd0sDuqlCO4=,iv:shAoSjI8eJxTaOUHvJVrmTZUCuw1ZYqPcjh6bCNQ3Dc=,tag:m9DsP0n/AqRgUx/wwWjhfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
