jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:vg/3d7UDXRP5bV//Ci68DCK8VfygeR1DdLYitZqAdFWzvQg2kdWGbpUap0A4Sv7VOo/E,iv:8Uq5t1QTOR1NggqM7ycdb9oHLsDczL+VxBH9sjDuLzI=,tag:0+ySvRaMCMtt1xcEOH8n7Q==,type:str]
                client_secret: ENC[AES256_GCM,data:oABa/TI5E9FMpLF4tY9+Mx91OYpO+ZawOa2jy4j4L7xOyt9vVDrDe1kBA578IlCtaFWQ12riUiVLEBJgoQ+7UY4bZxVSuGyN1hQO7b3BF+Lz+dDHBo8=,iv:QuNg7SgTdXSrYNHalAlxZGqhyiMcet6mUjc1L8xAr6w=,tag:5ySv1JVNkgPsIOdIXTLrOw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:qXEFgawNc0JOGZuMuG2oTSUG2Enuv0NmMScZxOPL5T6NTP7D8yW83I57kW02Y4CjVWQsBxbIYEyxuhmCo1s8ZQ==,iv:qoqMx4fwNoT1ef6fGpG1iPomU398hKpEiTzTyC06RG0=,tag:eijLmdz6MFWK5FlvBrRXmQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:35Z"
          enc: CiQA471gatcRCV0fvYjj2oq/r2mn09iYJPXiSYlmty2CXV/wYsISSQAtv98xDnXLHIVEvG/MwIA6YXnqWFxac8Hbh3ewe0V13cxXKToZ/6wFnWGtW016yqZl2tF9+ljvOg7pU/HMg4/TDCf6+RvFCCQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:36Z"
    mac: ENC[AES256_GCM,data:rknALeL7MTIMEeFNT39caFuqxdKrl+4ieLW4BFQgfPOnmAEv7IHLZ0Kz9c8wygWXJPc3jOmqqKrtD9Ng5sBHxtSeG62cV8EVmWG7ypyUOZBr5H77vTJFI6CGqpnB26eoGiApCv6uIZOy/yypGGD7nWQZ7/KxgXHpIqhkNMSHY0g=,iv:0Q5+mxmQoxN9tj8hcEcrEf5WejRZAtO9dkHVbP/a+ZM=,tag:gcPtG4Ahgm5S4U/d0znoDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
