jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:5emjMAVChN1V54WlpEtvvD09+GaN+I5vIxcxmkvcMsJGbHFun4BlfqCufaNx4xDZqWQ=,iv:13NGkIhsSwIrlvCxD5P69eMJrRiRje2xo0KUYk55wTA=,tag:AC3R0+BMN1M5/Lt8ToeHaQ==,type:str]
                client_secret: ENC[AES256_GCM,data:AxPonTJiudPJIKu1PBj3DgZ8FBVvgxWBscIwtWX8oLiMTitu+UMR1fKgGNZvn8yNnPNTV0eDNYNmO763rbbi7BcIL3ZOE9YlR1X2Br2z+5JzqQ9+YGs=,iv:hTAUu5y/EXS6saC4aPYaCFhhdsdkcBI5Lp+30QlC6HA=,tag:9k4IxynIndPlEvwQ2yyDWw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:2Sljv0cwKnMNPbS15a5ZEh7T3tSPp/6A1mHmgq1SzwG0J5fH0dr1Aap5i/kLCUGHHYApDrBoA46eNCuPxTbC8A==,iv:RmsaH3j0JuC9yV9BBjdo1j9UlLbIElbvrjyNKNwhf9o=,tag:+D6NjoKVbIYcoWQ5BdtgxQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:37Z"
          enc: CiQA471gagKkAnNCKT0BEnypg0ZQYnFyn5IL7ULklIK2owsGLLYSSQAtv98xpcvyCykqLxKsR2zGuTGgA+lQdxhlkPYkDAuv/jtp8Pg1HwT4ymHWGLVVuF/V65vyzac55YjH6qDOmdev84yPQk9BI7M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:38Z"
    mac: ENC[AES256_GCM,data:2MSBuCGT4KYHK0p8iQgFdluaLznvyUV2T5OmvOaX62+MTedC05za+YYKi3czWRogkTKRlW80SJEieDvtDHEC17yX9iCvHoe3QX5ZcJMPzN+upWcUUWmvIqRMvpqJlJl/MkDOT4824pJjeHUOgGXrm2DRQLvvMHXuxEaqIfL19ZU=,iv:G1vvidKNhTfwnpIyWiDp6HwBkWoIPsvc9NhNtOENVlY=,tag:9TANA8wNeW/ZpFguRM8RJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
