jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:A4um9i+STem2tYLrq+0TTWXsbHjpgQKIc3S7ZjX6/nlS/L6fYB1yn79tbMBFAoQgYLc=,iv:9qjMj0cgxCGHkPU4pQ1X1MonpPMb0FYoEvIExLWqAgM=,tag:u/P3Vl0GjJUtd3pb6cPwuA==,type:str]
                client_secret: ENC[AES256_GCM,data:9QjvMTyznZiA09Kgk49b7wsv/HSQY+omPaCdWVZP6OZCNJbqOIUSZrxKj5YlpmMl4049hWdwhRB2LZj6ykkX56HTravxuX+Lh2+BLvunWb8WqQMGOV4=,iv:4HPevaH2zGU0kgz7GesnlWElZeB48UfgopVhgRjKgIU=,tag:CEBMmLRb1uMrggaVXhR4/A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-26T23:41:44Z"
          enc: CiQA471galFRbA70RkYGmkqNsE5VJ2nYkIXM3QhlgKwZtdkEnD0SSQA0woZQeKZiTx8NF+kBZnDAXfF7FhTGKXu43uwWOkX+S96060Jl7UGZyMTrYFEuXttYykNv+X+g9OdMSDSvozqbBOwm7lN/Pf0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-26T23:41:44Z"
    mac: ENC[AES256_GCM,data:gdTYdukdqPXRX6CkjDEvvwU5exe6xpx/7qBXvUd+pNuY5JFhxGFUwBM5BE4l+AoNoI8SWRvVaLZgZViHx5w3H2YLf4ArMq/wk8UWwNt2cUXvbVq0Dc3mMWaqfYZLq73EDWqKnp/TM2RbRx8iDEX/VnpMT0xeNAf2H5wYeIuUgyA=,iv:GAAkr9spTXdyh3CyrGovNvZg4iEKbEJYt+pMOmEJUUs=,tag:+jeqkg52BAUoCTezT5yiQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
