jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:uIf9ark/IatDKB/536O5g+39CbNHCCgEpQ==,iv:KaxZkfXuRupprWrQwXrJGFTjmNQczlKzKpSwSoA95Bk=,tag:gPcHH6tLFnEbSPTqCMeJSQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:PXaQ3oLWwmSTJ8Fo6aH00oJi4P7Tfwtb79ZUkojbiVDbYw18Tct7JafbJEFOkwHColxBikesE82SaLkvKd5uYA==,iv:IHVJ4VMefhqCzb+GmAl12v5aolYQcsb0GhCbVTixR+o=,tag:JWGwANfXEfBGfLaF/dspmg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:24Z"
          enc: CiQA471garM3a7vqsDBpsLoVqbbPL17rC3Izz6Y41wYQCVuSZV8SSQAtv98xCIztRUPdKg/meg1nC6NZ8jqxRb/fdcivsKNxp3RnYDLQkGMiRYqHtJGp0BKDBY076XYzxRfXWvva2YapuYhZF5nBJ0o=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:24Z"
    mac: ENC[AES256_GCM,data:kCELLJDiXdZQNK0RIGHuaHTeVsgh3jhR3evVsRrT7ydLPqjkxPsj+TL7a53pfB8xq0J6PUrqXz3oDMEZ/7kAm3iW7U1t0vk4pqIu+sHu6GYd8TivR9XXO7yjET1/uXg8gxZ0o1Rqk405sOUElOOfUnCoERYVST3bIm8eWgkkfdY=,iv:7sMrosKD+n4qChxxf6dpMZsLgScGZUcUR7QawbWpoT0=,tag:mQW3sZPJ8/Y12IMqa/fwCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
