jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:+XxQ,iv:+ff5fWFRJNtEn9gzzzToCC6P667gqcj2SdSHIIqywS4=,tag:+xI8Lw9ETuFJVVoxK0OZDg==,type:str]
                client_secret: ENC[AES256_GCM,data:H9N8,iv:mUxiwPU3+dMXvkUrBWgF8flBG96gT4U+LsFElG3QTK0=,tag:BPs1mCENI4TIZugC85fg6A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-18T01:18:32Z"
          enc: CiQA471gar2zgf5IFvB42ruiPjh5j+iegvcpskQ4mUoq8Nsyhm8SSQD9se/ObMkwzFT0ClpYqvvvsCg/JTIUi42fhnDhJrAndMUROzRcjtpLhWYLs7bhz1UlNd2FlskWLQw0vG0TtPzqXsRumGCsXHE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-18T01:18:33Z"
    mac: ENC[AES256_GCM,data:8hX4J2+HXvnwC0KukDBrUr6zJnrXMJ1xUB50+jxEAKIimQcCpAOtCAvO8+fycTrfBEmYtQFELZ7Px+sAb4O0uungbtxkX6Df83jDISPyEqXmh5i095aUOeS7+EvZqbjKQ7S4GVk+CksUCa3zeryCnC8EPRghl0T0HkQguN2c5JA=,iv:jYcbXzyG7ZrVwTJ/Gv+UzXfWCc32Qek77yMgmvpdoaA=,tag:3R1Dks7EijI5HIA87ki/qQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
