jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:1WZivU1M7UpuXat7MiafTpyPDlP1uf/1aA==,iv:ITxM33a8n4oFoGiqKWvL003OcK2s2bTst0yItHhYS6U=,tag:v09BSxLUyAoLnR+vgeGccQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-18T01:18:32Z"
          enc: CiQA471gar2zgf5IFvB42ruiPjh5j+iegvcpskQ4mUoq8Nsyhm8SSQD9se/ObMkwzFT0ClpYqvvvsCg/JTIUi42fhnDhJrAndMUROzRcjtpLhWYLs7bhz1UlNd2FlskWLQw0vG0TtPzqXsRumGCsXHE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-18T01:22:07Z"
    mac: ENC[AES256_GCM,data:qMkB1qvoorS6GMnfiVIhPanscXmn6g1ZZRO4Gw81sHinVlEUcssKBg4j7gCSgGQs8kdCvWQNYc8b/hE7aTAoPDaQv4kxbMq5foftAO6CwHCIL5sYnIbQVX1qctGSpwj0BqEE+IteYNQM9Nh8DyhAgGxAGnJquidVx0bjYyqWEWw=,iv:BNMsPFH8RkBD0653OuAeDeOaBgTRNV1JolNKNEI44TM=,tag:+ntYFXf7j7VPIm9Y20kcKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
