jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:gv/g7PJCArGEGqKoF2p6pSWOx8AECPTP5Q==,iv:esCJo09aK+2BnsbHEqx7nyadk4t6/2Ueci2WTOMkJtE=,tag:z5mfgAaiX8bu1VTQFwTeOQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:wUQAG4umDDc0KMQEnOxnXcrGoNT9OmRiWLjCWdzjkDhi7fRQcmu+qPVy/13vjqzgz+wmPDkRPrfCQPUJsh6VnA==,iv:Ps/r+j0SsJyj8pR/GF0WMbXhFpobNFyu4YMbGc+2eUA=,tag:Nn8xLsmyRHqtIRZUMSLa8Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:26Z"
          enc: CiQA471gap/jG/mcF0y7asUO0dGsrj70901K7eGP6JGe16u3Ym8SSAAtv98xhf86bTZAVneQ/7J8ocPBvoJctso9ycCHFKftJNor9njrTfc4dDmIOrTFMlmQgpwVQ9iOJovHWiByWUrumY0uTCAWvw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:26Z"
    mac: ENC[AES256_GCM,data:vEwPH2Qm+ZnzTSvs6CU/d11olRRLX7lKcb/LYv+ILgreCOhlm+235QwYpuVeaSpdqsJhsEtMnlBdbqkAe3i20//aG5RPfvly44qe9BE1YsERHidW1WU+Dh3McC5WZ8StNvkMZkDkIR7V1Rf7Rjc3IjjqkvNznzhRNE6LhRON9hI=,iv:2ob6FA3pNuwfc9zN78xeCNUu1Q7ooboiWPeb0Danpx0=,tag:CiZK2ibCZzg5Tg2uG6TV0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
