jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:pHlu,iv:l2JvMqfRoWxFJV9N0FI7lqE884A/e48wNDSsnyDS7jw=,tag:B1Pg6/I/tcnLIY7ofIMi2Q==,type:str]
                client_secret: ENC[AES256_GCM,data:9vyP,iv:Btj9oU5eThxAkQKvwhWwQc6bSWRo3BAMCOIgZ2ksZ2k=,tag:Vfwj1+68luBUEbzmvEE2ig==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-18T01:18:33Z"
          enc: CiQA471gauqnrzlCc/pWIfWtLxncTVLrevTa0cVS5hQKwCCq0lQSSQD9se/OkAjWiM4rcLV5B7eWsJD6W6BF9cQ7oz4CXYlUwnhBP35jsBn9RVRcuR+rYTZopUh1QNm15hyLCLLW7L7IRkBBTNm3EtM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-18T01:18:33Z"
    mac: ENC[AES256_GCM,data:4t6TAcs1IXCDyzMD05WnNEGmTz+rRYEe6BiJFtMeIAVJswyU3IjHGTH6kK9Mn+WDaE5teoBZz0cJ28qbsnnrorAIfHquTDN06D5BQBBpo3kvlPTqeR5Ny47YeYEYqFPysYZHjggrre7xRYo8ukga0oKjK7yofK0X4M4cvJSOMVg=,iv:kKMKfkL1VISTeRoM1R7oReEhFMqccWLTf0x4k0h1ka8=,tag:1aEKuBO5yzFWlohWWGaspA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
