jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:GJDd1DhkDCA5U3Ij6imO7802aAEigDO45A==,iv:w2VwJHX6TXVINpanAShC3vEQwwzZ5av0TFNcn7kxoNM=,tag:xEb/4zlysUcPWfybGeTxHQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-18T01:18:33Z"
          enc: CiQA471gauqnrzlCc/pWIfWtLxncTVLrevTa0cVS5hQKwCCq0lQSSQD9se/OkAjWiM4rcLV5B7eWsJD6W6BF9cQ7oz4CXYlUwnhBP35jsBn9RVRcuR+rYTZopUh1QNm15hyLCLLW7L7IRkBBTNm3EtM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-18T01:22:14Z"
    mac: ENC[AES256_GCM,data:56xNMxseQkl2onOqpn9PnLcNv+nE9eZYyLSFF60SrUKxFF4rSW6zru+IhEqf/oAnIq5tsHxhskMSRrbE57vKmx3RtYnCR/YFzjGtj4++jBIAmylb3n7EywGcFMcjv42eKkEBaI2Hi1ByWU9xUe0wIrHoDT9xBtBPdowoAF9D+lw=,iv:Jb3ik6fcGngrgPehj7aJFyMvhmYlPi5hhf9aiEs+Ivk=,tag:3tZ/oKHDPQgkYYnxmrqm8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
