# nfsPVC:
#   nfs:
#     shareName: TBD
jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: false
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  proxy:
    https:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - staging.jupyter.cal-icor.org
    tls:
      - hosts:
        - staging.jupyter.cal-icor.org
        secretName: tls-cert
  hub:
    db:
      pvc:
        # prod stores logs, so let's make it big
        storage: 10Gi
