nfsPVC:
  enabled: true
  nfs:
    serverIP: {{cookiecutter.hub_nfs_server_ip}}
  {% if cookiecutter.hub_type == "rstudio-base" %}
  dirsizeReporter:
    enabled: false
  {% endif %}
jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "{{cookiecutter.landing_page_branch}}"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: {{cookiecutter.institution}}
          logo_url: {{cookiecutter.institution_logo_url}}
          url: {{cookiecutter.institution_url}}
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-03-05
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-03-05

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-03-05
    config:
      JupyterHub:
        authenticator_class: {{cookiecutter.authenticator_class}}
      {{cookiecutter.authenticator_class_instance}}:
        {%- if cookiecutter.authenticator_class == "cilogon" %}
        allowed_idps:
          {{cookiecutter.idp_url}}:
            default: true
            username_derivation:
              username_claim: "email"
            {%- if cookiecutter.allow_all == "true" %}
            allow_all: true
            {%- elif cookiecutter.idp_allowed_domains %}
            allowed_domains:
              {%- for domain in cookiecutter.idp_allowed_domains.split(',') %}
              - {{ domain.strip() }}
              {%- endfor %}
            {%- endif %}
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
        {%- elif cookiecutter.authenticator_class == "github" %}
        allowed_organizations:
          {%- for org in cookiecutter.allowed_organizations.split(',') %}
          - {{ org.strip() }}
          {%- endfor %}
        scope:
          - read:org
        {%- endif %}
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          {%- for email in cookiecutter.admin_emails.split(',') %}
          - {{ email.strip() }}
          {%- endfor %}
  singleuser:
    image:
      {%- if cookiecutter.image_name and cookiecutter.image_name != "" %}
      name: {{cookiecutter.image_name}}
      tag: {{cookiecutter.image_tag}}
      {%- else %}
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 748e36cdd4f5
      {%- endif %}
    {% if cookiecutter.hub_type == "rstudio-base" %}
    defaultUrl: "/rstudio"
    {% endif %}
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
        {% if cookiecutter.hub_type == "rstudio-base" %}
        jupyter-shiny-proxy:
          mountPath: /etc/jupyter/jupyter_server_config.py
          stringData: |
            c.JupyterShinyProxy.site_dir = "ShinyApps"
        {% endif %}
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: {{cookiecutter.pool_name}}
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
      {% if cookiecutter.hub_type == "rstudio-base" %}
      extraVolumeMounts:
        # RStudio can't write session files to anywhere except ~/.rstudio -
        # only way to change that is by setting $HOME. So instead, we just
        # bind mount a fresh directory on top of ~/.rstudio!
        - name: home
          mountPath: /home/jovyan/.rstudio
          subPath: '{username}/.r-hub-rstudio'
    {% endif %}
    memory:
      guarantee: 512M
      limit: 1G
