nfsPVC:
  enabled: true
  nfs:
    serverIP: {{cookiecutter.hub_filestore_ip}}

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "{{cookiecutter.landing_page_branch}}"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: {{cookiecutter.institution}}
          logo_url: {{cookiecutter.institution_logo_url}}
          url: {{cookiecutter.institution_url}}
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2025-12-22
    config:
      JupyterHub:
        authenticator_class: {{cookiecutter.authenticator_class}}
      {{cookiecutter.authenticator_class_instance}}:
        {%- if cookiecutter.authenticator_class == "cilogon" %}
        allowed_idps:
          {{cookiecutter.idp_url}}:
            default: true
            username_derivation:
              username_claim: "email"
            {%- if cookiecutter.allow_all == "true" %}
            allow_all: true
            {%- elif cookiecutter.idp_allowed_domains %}
            allowed_domains:
              {%- for domain in cookiecutter.idp_allowed_domains.split(',') %}
              - {{ domain.strip() }}
              {%- endfor %}
            {%- endif %}
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
        {%- elif cookiecutter.authenticator_class == "github" %}
        allowed_organizations:
          {%- for org in cookiecutter.allowed_organizations.split(',') %}
          - {{ org.strip() }}
          {%- endfor %}
        scope:
          - read:org
        {%- endif %}
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          {%- for email in cookiecutter.admin_emails.split(',') %}
          - {{ email.strip() }}
          {%- endfor %}
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: ea7960107f5b
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: {{cookiecutter.pool_name}}
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
