nfsPVC:
  nfs:
    shareName: shares/csusj/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - csusj.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csusj.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
        CILogonOAuthenticator:
          oauth_callback_url: https://csusj.jupyter.cal-icor.org/hub/oauth_callback
