nfsPVC:
  nfs:
    shareName: shares/evc/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - evc-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - evc-staging.jupyter.cal-icor.org
  hub:
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://evc-staging.jupyter.cal-icor.org/hub/oauth_callback
