jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:iiBTtYEIhl9GYTaOW3I2tRPnUmzdRlazTKWw9hKfV0w2Tp8m0fk9pJuivXofWBEkwXoG,iv:Oxaob0Dg7Azbzp3l6WhdKRgDbqchcrmmfRQPQ2T6mZk=,tag:c/Z4FJNpsLnfJFUyjUze1Q==,type:str]
                client_secret: ENC[AES256_GCM,data:SJRJaS37ASYAkXqrBwncijctFZb3PS5Ycm+JIZIJ+3t5Q+KtiXarjCglbPtC92tZuj4ilsdh5vajUkDJ9OnQGXX5YISnjCT964pJVwJ8GruCLnjhu/s=,iv:Ufonl+e/WBsUb9oPUJmnwww+ibbpMQKodeiq78De+Vs=,tag:4Miqw+tTsyKUvIev8SjKiQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-23T23:49:09Z"
          enc: CiQA471gai+m3V8XXmwzptcA2ErbzD2HMc2qBfEXLbqCaXOKqxgSSQA0woZQNSwVHNYwjD/kniH7YPOahqerjM/PFSR4Nh+bAcgQVC6qxiMHJSDkqxLaq6uW98j7tPznLAar+Emw5NYmvS+iLbBe4ds=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-23T23:49:10Z"
    mac: ENC[AES256_GCM,data:DkHfetRZdYFcvBjV46t6EBPchBahGlN0r2dIrECtOF2OcwUqCPFc8PNpDxw7kDvZE8EQGCdBBTjyCXqzxZKOAfPPFtGVznVelv3l/CA4oqv4i5ugqxD4db+ZatlyGrkgj5CQNu7t/n4oT3uq/aTxojReZmgDDFmIjjpRDkd4ciA=,iv:KGjPn7KpJqBKu9WNu66RM7WZPgF23tm8zDMRS2nRqts=,tag:Met+0uJfbhTbH9luVaOJzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
