jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:xsGNuSgP5fgVSFzPZOoGi+eESz1ULyPMXdkMb6SSx02TDQ2csnsT4dTP/S+Y9fyi0kKp,iv:n9FLzbzwPIns3H8lHTSNodRQcAVMcOVaTOgPA1fP2Xw=,tag:UoNlNdxKSbqe4pQPqkzoCg==,type:str]
                client_secret: ENC[AES256_GCM,data:4mhxQ+a7fDConagR9JPk9JwoWdcfCgVpcVZsL5HuUdNjIoAQ7PEgnxsMS64uz1NUles59ft2Pn82Uyifsg3jju/AC3L7e6e1l2Blfhq8QYRAWYEmYg4=,iv:pVNRJzmpbg/fkZgRxZfzpeOrA4whiFzxRr+JCvjqoGk=,tag:0Zhrrr8PnBOiTU6YafIIPQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:QOBBIZDOnWcpMfTyhrjx4Wa3nhl70SnDyxdPoG4tGeyMmO0Bt3fixH5i3RQ0YplVxbwf75rj5HBqXHlfKy6/DA==,iv:ZB9+upgkw0YX7fWd1+Xj+N6ZOejMEpqSEKa1TOQuju0=,tag:DPJBCJ22/rtbcfSMSGq6IA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:12:42Z"
          enc: CiQA471gamt9BUbBFokBYUjenquouUtPRAqHDFlXpbWU09SHcD0SSQAtv98xWqtYzb7FkOAZ6EbNFAg/BYupcJQMtzFkxgU1VOpceBpOXYd0x7ly7lKvz9agUpnxX5Nln/UFLjHARs71GnQ5Zjh4Xsg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:12:43Z"
    mac: ENC[AES256_GCM,data:HoL4y/Z4t9qbx186rXHwru1Gm+4RmBoksR46q/ATwllX+8aKGnEpg0M3ekNMdCcCpaf7nG2I4TZhI3KSrDOV5mLT/dyc0r2yzujTzc4NZ/HqgyitmVJSbJ5B6n7deBcGSVzBrfn7nRjvA9N726L9TBuS7evb/cA4pq8NZDGPLfM=,iv:Z7eTB48TkOYEpylxwqjmXCg2yVJf8GYIR07Td4RXzQ8=,tag:Bk6HmMxJXkrhDQmdWUQxHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
