jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:VE8B/03v/fWSPzDHIdVok3qYqjl9m2dEFsOX2Lagi10DJwIsfgzUfc9DcHN7tiOfsCSv,iv:Uth+Ge5Uf4+iFYTFFVRt6Mf4AoRWcHbqM3vTKaQeMCU=,tag:GEkWvv4gkMvoPTDU33LYeQ==,type:str]
                client_secret: ENC[AES256_GCM,data:2FAQIWTVCwPII5UDsTPmmKVzEgwOF9XS5/M24HVHAY+RYoLeNxGonK5NcBbSD5uXGeJwE3n02F1iGH/Eh26W0+iXVmiaEhZniztx2Mc2DJIJ+qJ3EXs=,iv:/ihiYC9wBmR+5rYr+D27kRNthSFWRXxM40N1+GUS1K0=,tag:oPTlBzVdBso6FM98DccH5A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-23T23:49:10Z"
          enc: CiQA471gar10rEESg/TVP9NGSzr5TE4ud/BfFiO2cgmf76ZO+/gSSQA0woZQXJ8+Uai9ZdU81hNadSrIqS7INnNnB3Yw9fLVlXGZ7cRFYekPbA18o4TlZvZPtryRJaSNNy7tMEi13P4WRmkPiR9Jvqs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-23T23:49:10Z"
    mac: ENC[AES256_GCM,data:jZymtLLITMV4K4IypgmfBIdmoNhJK/y3hKU2rV2tAj4kQAxOcCa1G7fr0al2d8ViQGUhS0jecUGyTB7ttYLIeQqiaDdjAy86BZBIstw4fpXSZNgBv1B0ZSorjuChwDWl2SwsxTXAjAeVJZ/XcffU+vm8/Y+xtalqnkkteh84zfc=,iv:1LxaJiY2QnRbML+YP1Ryg/0609L15RQfCzGpQ18D4Go=,tag:mYmny5lIdR2ArAhyPJgXKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
