jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Q8xKdIF9CIE9+KNcSEvVe16VvLa/pp8qpJOz3S0V9FaKO7ihnIM2Bi16T+ULCCPTkXkJ,iv:xVeVioxgGz666Nlsd4igvBgnMZ/QWux8/rSw8qphhM8=,tag:8eTzrPkO5Ri8jRwS5tAj2g==,type:str]
                client_secret: ENC[AES256_GCM,data:+rkv6MiseHyxzYw0f3Z/w4PXHbwhHKJ0xRuIT1rGd6TfQDkS2G3mgpVJX9ldmhvEt9tj84rHM7l/BHHlgV7G2h7dRzSpxF/kEg4RYs18XcmZMC630Vs=,iv:VuyiSrApJy2eU1IaguP/x3HgmkJN82bk5Ajn4dnNJqs=,tag:NURM+/pmoHsXR6FcVhZ7kA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:lCVVVm7mQpGWv0KH+83+SIhHCjWQ7MNy6wBlrdfpmlpRMqsPfrNVgf4FtmJm5PjYXIoIfm0dZB3c0rddnc4CnQ==,iv:GXSpe4JXPuppoumxoBdOZHaTHnSr+Jq05FAtp7nAsWM=,tag:Ua/UPNug/ODjYM0QUlYx7Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:17Z"
          enc: CiQA471gavLFpDFQntm2cEL7zZ+IrxqxrlTUQbw/ogDHX1qQQgISSQAtv98xkeUtoz8vih7ylyULO7zZ9vkYo2gVOh9gUeQIsaaJOX28A/66F12v2c4Du4nkphXp+vK6H933QfIFlTVhJ3x/CbjLUI4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:17Z"
    mac: ENC[AES256_GCM,data:42F/dF4rJdyyPkEbaNZqMcRdv/eFVuXZkJAExGwma2E7wPwhtTL7nMd4bkH3n1RWT1m7cMHt/bUdpV5p2Md3GKGk85cep/JdoE5r/ZnkOvd7f7vKmRtOtEuRDvSwRAG3hIUx5FdJkjTyZI9g1KMrVJQUlBTBzUjXKIOZS5kSBJc=,iv:tY7cyGtztIYxA+qcog5N7tEXPCrffBYert0CYZld7rc=,tag:I0cNKR2l0Vecce/0eHL2rQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
