name: CPU Request
description: Raise more CPU for students in your class
labels: "support"
assignees:
- sean-morris
- shaneknapp
body:
  - type: dropdown
    id: hub_url
    attributes:
      label: Institution URL
      description: Hub that you are currently using for teaching/research
      options:
        - chicostate.jupyter.cal-icor.org
        - cpp.jupyter.cal-icor.org
        - csub.jupyter.cal-icor.org
        - csudh.jupyter.cal-icor.org
        - csueb.jupyter.cal-icor.org
        - csuf.jupyter.cal-icor.org
        - csufresno.jupyter.cal-icor.org
        - csula.jupyter.cal-icor.org
        - csulb.jupyter.cal-icor.org
        - csum.jupyter.cal-icor.org
        - csumb.jupyter.cal-icor.org
        - csun.jupyter.cal-icor.org
        - csus.jupyter.cal-icor.org
        - csusb.jupyter.cal-icor.org
        - csusj.jupyter.cal-icor.org
        - csusm.jupyter.cal-icor.org
        - csusonoma.jupyter.cal-icor.org
        - csustan.jupyter.cal-icor.org
        - dvc.jupyter.cal-icor.org
        - folsomlake.jupyter.cal-icor.org
        - fresno.jupyter.cal-icor.org
        - jupyter.cal-icor.org
        - ucsc.jupyter.cal-icor.org
        - usc.jupyter.cal-icor.org
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please provide details for your CPU request!
  - type: textarea
    attributes:
      label: Reason for the request
      description: Detail the issue faced which resulted in this request! Your request may have financial implications at our end!
    validations:
      required: true
  - type: input
    attributes:
      label: Student Count
      description: Total number of students affected by the issue
    validations:
      required: true
  - type: input
    attributes:
      label: Duration for this request
      description: Share the specific date(s)(MM/DD) & time (if applicable) when you require additional CPU resources.
    validations:
      required: true
  - type: input
    attributes:
      label: Deadline for this request
      description: When do you want this request to get fulfilled?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional inputs
      description: Any other additional information we need to know about?
    validations:
      required: true
