jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Az37IDXtI6nIF0wH9xhxk8lwON4MPqmdvOahrFKsi7AH9Ctwslq2AizWrSrL7YgYdx1I,iv:77BBfcVv1lyqzd76TInUCYlFxAf82KLl4puCEGS4BZM=,tag:i14Y5JOT3QxYF9XXu25RKg==,type:str]
                client_secret: ENC[AES256_GCM,data:/F5evcUHeEpzMK68tZqrwWa0S9OtbPVTqng/N0SU83QfH8mx4RuPHLnLS4HQGWOOSuRqqv9prHQVV08Y9FX2E5WjiTq+kBvmJz9cYPRJnBzTImWCPtM=,iv:YbL0aV0GyO31ROeAPECYq4o+Y8RIKcZQ04fo5pbba/w=,tag:9VkLQQOAnS/rfXw4g9ZlqQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:IREGubaYzvu2kxgDwuT2FsblroDKwkRRCy0PEKYwPZZZifX1DaE3+S2XCkpJfPntv6FK2Q4njDOeOiFLnGSfHw==,iv:HhQngk8lm1H8erGmFRgn0UAwqOD4Lv/tZgeVBk0lAKs=,tag:2hDC0Qi1GtwTVqNh68FyxQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:08Z"
          enc: CiQA471gatRo8np8Ttps2Ie2kG7eb7Bg6peuxUWL3DwufshCIZESSQAtv98xfqMMaJu3DghTh+jqRE48kqEZdpxfX++Qpjj1Gt0TYWPyyKtxklgzv2lN2Z8nfxA8dYtDt2I/ojEl3+i1H27BeHJpndc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:09Z"
    mac: ENC[AES256_GCM,data:jy1sYOAPy1fbb+Vy38wZ6cTJp735kjFnsTlvKcM75GX7PPeSLJsK3pgupJYpaddaeNMdtBwa2aaYlt2NjK/+G7I7/kNp7VpaPcOte5orAKvik1Aoq30VXguwLbhm6eGSrgfjwydiP6ZTt4S+NK98d835R6bDFJYgsdmogzwLjVs=,iv:krd7L2dCJduLViSwGqtE1vf8SOPGCkb8VJImOMjWtcI=,tag:8wHd4scBdsHZUr3+ZhmYlg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
