jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:gFCTCfTOdB++M95nGVPad//QDttgGTrZ1/93DVszVRF64HmFnWM9++y+ElLw8xhtpVA+,iv:28dyrS0lu+GyTAEmo8FbaTYy1CrE4tID7fmMgliRjDg=,tag:WcWLaTBzOAYl3xn/bq+Jlw==,type:str]
                client_secret: ENC[AES256_GCM,data:tZDcL/Z8GftS0+mSdYBT0BGniv1HNF5gFsdndZM7ULMstWBsFwngevsl9DMfe4tFLeYXbZQLD6xWp+6hmEBSZMCjtFMHFBf9X9cBlyOSiINYLw7SjDc=,iv:8VH1TGSWWEOo3pyYH5iqd72PPtug3FDLphkjKNSwFqE=,tag:TGdkjHqHLnLUMkNUb5+GFQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-11T00:01:14Z"
          enc: CiQA471galRY0OfeUzwNpwFtTuCcYeJfv0bQkvk0qM6AnaxiXDoSSQA0woZQ9GCSQUT0oGNJF/z1+aDTYbSTnZz36q9Rb85hXMMlDUAu92HMq7BYZBG34KMiQz+2Pr8WC+jAcKm+sbOyCBN1A0MCkFA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T00:01:14Z"
    mac: ENC[AES256_GCM,data:k/ePezo6E2XpxLG8XZOQJvekgb/kIi1rxRYOubGV5YejJKGCHJgWi5Do7EWUXwAbwN/XSMRQXF+Ao14mmA4n6iI/+2TPz7r97sDc9bq3PYBpvQYuba5f68nLYj50uxA6GyYglRlp87/FZsNk3+lVlrVVW23+puSSTkefbcSgQWk=,iv:u/uDmJthlKjPclyjqL9yoID3klsew2yt+C6DeTmbs+Q=,tag:DTkw20Eiiloq8e39ikxiYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
