jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:i2wCLk2EKpz2q5FqCKhoNICDMooZDpgyD4srkqjb19YM2wGVUxQDz9o9CAUoYCjMQ7oJ,iv:rQITfXNoKv+yodhAI6Niad5zeaMpMNf2NltcrCIAvUM=,tag:8QJ7BNDTU1Zz5A+8NgMMlA==,type:str]
                client_secret: ENC[AES256_GCM,data:uHCBY0eYvPXrZ+BIRAezdhFKmt3DPam/XwnhwZjvHsVtPQIZMNnz8B2FfO9OQIOn48XcaW4GAvf6xogos/IJCLm5TbmZXlj8/g/a0JukDTyrcr26Lu0=,iv:G3Hj6XZrxsCqS7GhnNSgfctVkBZBWNsQprG493pY5us=,tag:YLaSYSzInQtUCsLpTvNTbQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:I9ZlMXvlAStGwpBv2fqvZfyvSqVtqDd679MFmmXQbC7WkcmOqOVMk8xn7Al7YJNV50tVSFY2BNEARpsJR/tb+g==,iv:i04dQW75ywAwN2QvZoRwmrh7633zNx/Ri/zpRHgX25Q=,tag:3FJhyDKjV0TtZondiIo+Gg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:10Z"
          enc: CiQA471gaq9zSFsnoo/xr9xnQRBZoQjpy64dmUDcw1zbllRQPvQSSQAtv98xQd0IfvnoGOi/XmpFyW0wdtLgYy8uNzIs7lLzsr9KlR5oADkKDpBXieWD4udvicNAK94OkGOAcELwh4mtVBQWQo9ZvpY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:11Z"
    mac: ENC[AES256_GCM,data:MjMyfNK2tUI9lrTgPu3bLOiSFp/EYCtcGBVHihTPaiIUtGY9yhg0eB6j5wAKeaFIeoQIDQpghWCviZ27mvAgI/OD6CQ8qPqN1vh8dlknYskGaLsKqR1R2eckWLpR+Lzf641kHJ++TR6s6HFGgQvmGJnJNOSsQfvI+ErW02wBf6I=,iv:j4uHBHGFUsCKsXRIhs+aPFo+PA/IKja5G+L2tLy2yks=,tag:KsgpbkufSBUucrgT/Wkewg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
