jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ZPV4i4uGmJ+8UetYJuMqeTHqAVpSOvKUbvAnQFBWhlvCldV6o/GI4YEp6r52aXv3mwqZ,iv:bjG+pBlenh5m0Ema4TRH6HqLntFqS4qdIMw5OrR+fO0=,tag:xfWIUZUEeCd1IQYE6fMe/w==,type:str]
                client_secret: ENC[AES256_GCM,data:8+EiY8mOCebJbbiqY2G7fmCvoGXSwxlHyr7n00fME7NMnfTni6Gw+O0iEUXzXgNGxXJk/hgvIVAcYORinmOLi5nsVygoGVLvOGMWaTITGco6QhDp+7c=,iv:cOfFQ9E+0UJufopj7fo0en767eZF+bHBwaL/VeT8OuU=,tag:JscuoKHuSF/odVDrf4ZZZw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-11T00:01:14Z"
          enc: CiQA471gamNf8ojDOqeUvyYOqrQQnrcJtwU3c//Oen4FUO+URjMSSQA0woZQM7xGIejYDrX+UcJoGLIconSRAqlXncn9l1WnH2Yvumcfs1x7Q24PQwc3dHLjtfTLRBUkFdDBZ2EGdaGrbZmWNUvTXcI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T00:01:15Z"
    mac: ENC[AES256_GCM,data:C5zyN1l1IpsOWHy72nk9kDrSVYWFDlv4t8mKzIhNJX/isphR8ez7hp8SSx4BldBoitqRLx2t359fqEt2GyQpgHc3uw2nwL3P1tfymImCzI+IIwRmYKVNJnEetcFrylxjc2W7JEuEUckiWkLEWz/h+0XEP1vTThO47LbSGd/uWdQ=,iv:SWFqn/TGPGsVJkj/ao2+1ku0TGqGceB4FrlB5uKaNBI=,tag:P0A1ztYxz8qbaIw3tYRQaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
