nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.183.114.2

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "main"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Los Angeles
          logo_url: https://uc14ab104f4b763300c0d7f2cef3.previews.dropboxusercontent.com/p/thumb/ACg9PU7yDE0WybKi07wazLbyXcMX-OsLTip8NQ_8v_WISbuT5kYH729VGKqZMtedu8UL2oru5xOKLhDJg4DuqZvW7Txv3gHkZt5DouRAc4wZvV352MOoBB140Yg6xW1_QGMnJY3Sy-Q6rWIQ_5-09hY8S_Y5xcu_rwNlXzZDNi2nbUFMHxgj_ba56CE52p-znTn7LjsYhc1BdLuPdfSh6lEAb6QG8df1uVowVqpxalEqOR_Z4N-68qPeZTwYd5_0pv13TT9Nb7KeulaN1fQ5OvJGf7xPxI1f60I9jpqLZkZu0K8K1kzfvC93RIiqk-1F7znqSH2ouBLf0cCgqP7n8dUqopmYP7al6XAKgU0bZbOGyQ/p.png
          url: https://www.calstatela.edu/
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          https://idpp.calstatela.edu/idp:
            default: true
            username_derivation:
              username_claim: "email"
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - json2@calstatela.edu
  singleuser:
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: base-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G


  # This is under hub/config but got in the way when I 
  # use the template to programmatically add an idp.
  # loadRoles:
      # cal-icor staff
      # cal-icor-staff:
        # description: Enable admin for cal-icor staff
        # this role provides permissions to...
        # scopes:
        #   - admin-ui
        #   - admin:groups
        #   - admin:users
        #   - admin:servers
        #   - read:roles
        #   - read:hub
        #   - access:servers
        # this role will be assigned to...
        # groups:
        #   - course::1524699::group::all-admins
  #custom:
  #  group_profiles:
  #
  #    # Example: increase memory for everyone affiliated with a course.
  #
  #    # Name of Class 100, Fall '22; requested in #98765
  #    course::123456:
  #      mem_limit: 4096M
  #      mem_guarantee: 2048M
  #
  #    # Example: grant admin rights to course staff.
  #    # Enrollment types returned by the Canvas API are `teacher`,
  #    # `student`, `ta`, `observer`, and `designer`.
  #    # https://canvas.instructure.com/doc/api/enrollments.html
  #
  #    # Some other class 200, Spring '23; requested in #98776
  #    course::234567::enrollment_type::teacher:
  #      mem_limit: 2096M
  #      mem_guarantee: 2048M
  #    course::234567::enrollment_type::ta:
  #      mem_limit: 2096M
  #      mem_guarantee: 2048M
  #
  #
  #    # Example: a fully specified CanvasOAuthenticator group name.
  #    # This could be useful for temporary resource bumps where the
  #    # instructor could add people to groups in the bCourses UI. This
  #    # would benefit from the ability to read resource bumps from
  #    # jupyterhub's properties. (attributes in the ORM)
  #
  #    # Name of Class 100, Fall '22; requested in #98770
  #    course::123456::group::lab4-bigdata:
  #      - mountPath: /home/rstudio/.ssh
  #        name: home
  #        subPath: _some_directory/_ssh
  #        readOnly: true
