nfsPVC:
  nfs:
    shareName: csula/prod

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "main"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Los Angeles
          logo_url: https://news.calstatela.edu/wp-content/uploads/2025/05/placeholder.jpg
          url: https://www.calstatela.edu/
  ingress:
    enabled: true
    hosts:
      - csula.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csula.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        # temporarily disable token refresh to fix admin access to singleuser servers
        refresh_pre_spawn: false
        allowed_idps:
          https://idpp.calstatela.edu/idp:
            default: true
            username_derivation:
              username_claim: "email"
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
        oauth_callback_url: https://csula.jupyter.cal-icor.org/hub/oauth_callback
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - json2@calstatela.edu
    loadRoles:
      cloudbank-pilot-hub-users:
        services:
          - cloudbank-pilot-hub-users
        scopes:
          - list:users
          - read:users
