nfsPVC:
  nfs:
    shareName: usc/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: University of Southern California
          logo_url: https://identity.usc.edu/wp-content/uploads/2023/05/IdentitySite_MarksLogotypes_Card_606x330.png
          url: https://usc.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - usc-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - usc-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - kristof@usc.edu
          - kwalther@usc.edu
