jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:fbpGLPZiETeJnjMyI6XiIeGewHxn13Ih9g==,iv:7+vh5Bo5690+BZ+x+fVtnkuhfdj+AZgXXPKhlkWDdbU=,tag:i2JwHTy6bQh+mclOzAaavg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-11T21:40:53Z"
          enc: CiQA471gaueTr73LESR2z4FrwsqlySXs5qZWjsByZ6lby2SxFZ0SSQD9se/OB/549r6pAAiD3kYU9kbm58PUCc2mVFWDhuR9Z6QTTM9alfnmVQfkdp4WHFVLqTdaFjfd2Gfb4+Xc062xNMuqtxqMeHc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-11T21:43:15Z"
    mac: ENC[AES256_GCM,data:VoOE69yBfghqV+HkS9Ydl5rbEwMtv7qPVwVutu9D8yDtBAh5dBBrrHqlSgFzFvELxyd5qHv/Ew0rAe12FQNW/StArjV4/VR2qzaHzRRGrU2HW7bThvU3/0SqntOXbEADDdZG2jpL9nkDKbS16YUOp8X2fH9Qn0Ni5mdwWDPyFeA=,iv:r/yjCoGPtI+y++xBFQZeZIqv/E6CnRpzISF5Z/TGlQE=,tag:S4tVC8N0WawPHu4eBY1vjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
