jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:xGBZ1TQFtarOxsc8Oj1p340jz2eEAPlEUA==,iv:iETFHHH5XqxKUwITGNHAzfZKHTNPFEUWYOB/vcpdqKs=,tag:nAZc/H3/MYCn/I5IOhwKoA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:BdHMg9JBG00GHH6wFMS1JLACRUDK6jyT73d55vSanPjbXsF/pH0iMUtW6bo5uDHrAFmanrr5IpSVDyKAqQnpNg==,iv:tYDwtUmj1iZoygOZZLXtBpD1LG7mJhF7dG2FANt9jDs=,tag:Gv/NPb/xri+sBUAO3VIU/Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:16Z"
          enc: CiQA471gatsSwwG2WuXZe/nzCf2TDQT2TD44WTisEkH9NI4UYN0SSQAtv98xv7rYTpvpWjnCq4yA2Pn6EAry7dp5GpWRO/C/mRdQaZsGOFB2vU8Uav6DXwDEUhtVHtits2zgb5cJhF7R8DhPuIrpFLc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:17Z"
    mac: ENC[AES256_GCM,data:IdtDIcWqoLeL18R1ZdQm9ZyWtqnw2ZDMb4FnlvlVAB00phRtsZWSxfr9aMIOu6skO/aRxrGsNHRsJXV2kCoOi1oktGtJqE9JPi2MXIgKSBelxJn6P2z4X75K5EC5BL7llcyHgBj/QqME10X8BmmftG4Fjnba2U526mBN/HzEugU=,iv:Bh6vcoVZ4CNkrYpFRGbnjms6pDf7Z9m+QwDGx49Ic1c=,tag:HHl+/0CLNpDoMG3e3qygHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
