jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ekoy,iv:tj5B97qiScnyWeUUpDz4uWvztYyzTdkkqyWVNKCPOjY=,tag:1Z3Qtb+5qT6s6TtZ5pIfbQ==,type:str]
                client_secret: ENC[AES256_GCM,data:FVPm,iv:ycdMqC7/jHf9URR2cZ44H7wiJny98PP1FjfeifDKdr8=,tag:raNIg8yPRAGxkZi484XWcw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-11T21:40:53Z"
          enc: CiQA471gaueTr73LESR2z4FrwsqlySXs5qZWjsByZ6lby2SxFZ0SSQD9se/OB/549r6pAAiD3kYU9kbm58PUCc2mVFWDhuR9Z6QTTM9alfnmVQfkdp4WHFVLqTdaFjfd2Gfb4+Xc062xNMuqtxqMeHc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-11T21:40:54Z"
    mac: ENC[AES256_GCM,data:e7EGb5zn33cI2qIMdIRsmIy1SBYvFc7B16v86ETos33ggDjeSoqSgC9QUbZQy/jTdbJoi87m42sxbwOmNAnPK3DNrMnjvEP1ZWWQSILNJegfh2EdmPTRaku8LCNcHD198xdpQFJ6BW4yIEb+6yUy0XBXVWHzXgxVBxO32EPGvS4=,iv:WIyUVQHJYAJZrD1w6erx+IEW5BegXro6CqSuvMzHTWM=,tag:AflF0IHclNrg67Hi79MV+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
