jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:h6cRMrF82cQuOaQ1o/ScAcGm7dWWYEDBNQ==,iv:nNN2eW410dIuihnBjgmlWVdYDbS3uL9hqGWsYWlqDU0=,tag:0oW79piKOYNGFJyMxygrWw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-11T21:40:54Z"
          enc: CiQA471gatZMBZpm8rpFzuEWqAwRjSOG4HtO1NwVrOFty8lsFMoSSQD9se/O+X3eeyvDAq/2BH5TLh3iarOV96b9zAP/iNuZrWuGDuwt0xFwVPCMZAzkWabDjMqGLgye7AJZAGgRyFI0TaZ9m5EIbqU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-11T21:43:04Z"
    mac: ENC[AES256_GCM,data:wQix4N8KM7eqfoCFul4O1Z/G75t+dZvZDeqCBsp9QUhP6F47E/0uhjBOWFb6ydPTUGlpLadpZAQsc+FSOh0T/454TshZuSIgeyT4i4rriVg0v/gpveMKp90RcNw4oGjn5KxBZ2OiHJnUyrNax+x173VAmUakYsvSriLnPFOvWnA=,iv:G9J01AFDZ8e5fbjgxFJZLJ+6Z6A37WHT0Lt48i8TTUA=,tag:4c2dqOdR/YqXqYIpcNP0ow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
