jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:EeK0/Idi7+8lyCPSrDoWp+3DLwAYXiaIPw==,iv:BOprD3+3yxOhdrkzpD+XfBIDUmUiTe1o6wQwoe4cwVY=,tag:1qHILCuSfeaERvYDn+zSoA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:G43rjEVm6S2cnklcFq4YmBAjcQx3MdTim9HCTxblXHQ6fx6shsxVbCp5Jx608aAT4kdlkBsB7ojuTH1R8GOT9Q==,iv:N7E8syySWhhttDsz4v7L3zsXvsqh6XQnKlUan9QIy5I=,tag:whn1GLU4ha2+lDnJFFsxIg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:18Z"
          enc: CiQA471gavFNyp3jImKTCYgHvJJUu308M75uurnOFbTEDNvVAiwSSQAtv98xREKqK5bkxRUaCNLydEwlCLrTU/aZH4t4YJ47L3Yra6vuZog9x8s5i/g4c4uHUhLzzTgib7RiO0fCScgu9DYg1YUyRfg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:18Z"
    mac: ENC[AES256_GCM,data:e/9qC+wx+mAgyBKnNBzeIj/I5QN1l4JTfjisWvvzC0iOCwzfNevZASYkZdGGuCi59I6vfiYQi85MfSDisKkTfs5wwDmTmKUW1n8GgeJ3YNLubwKmJzboKKeD566RZhtCt0ib1MSZX3v9P4siltEToXmhETc3nZAjudxYQ8+eGZE=,iv:tneD0gV3SGuxctuof8Ra7KgR0nUSh7HCah+x4lKJaEY=,tag:wNorwARgrHBuay4cbmUv2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
