jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:hJFU,iv:m5PszecLaqQrrTbR+jWTOPmT8kDV6DMe677jcmeUyUw=,tag:mLLoI6yMlrDJLTx0LYf5Fg==,type:str]
                client_secret: ENC[AES256_GCM,data:WRWX,iv:unnMOB/fWe9EwLnP7zFMaEDvvlLw0U51ak/hsqZOnjU=,tag:FLiUzxPowuX5BMS+rXXzqg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-02-11T21:40:54Z"
          enc: CiQA471gatZMBZpm8rpFzuEWqAwRjSOG4HtO1NwVrOFty8lsFMoSSQD9se/O+X3eeyvDAq/2BH5TLh3iarOV96b9zAP/iNuZrWuGDuwt0xFwVPCMZAzkWabDjMqGLgye7AJZAGgRyFI0TaZ9m5EIbqU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-11T21:40:54Z"
    mac: ENC[AES256_GCM,data:xhrgPqjUBEkQ2RSZk3cRbDkk4+ALi/vMZJKcs833tPZxBoy9RSdB6zLW9743Mz/go0FkUPHDv1dBTv8LVYcCsJHvDyNWLFSGNcDtOLQK6KbqXCCD67pzWhEqCB/bdEWmKVtUXtvgmkgtfGQx2RhqagsYop3dTHmt4HWpWPASvs0=,iv:4UJzfLMwE26k1Dss1vOu7XdWEPez+e5C0VuIfhDHFE8=,tag:kKkYA61vun85/9kyiBu8pg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
