jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:TR1NvlKJxhTAYiJsA66tHZTDZ2R9hoVPOg==,iv:9THGyBPuBHVG8IPjh6FARt/JBW0wA6AosqMVOVGAmkE=,tag:cMRqp3rcpf+VqlK9AKQrZg==,type:str]
                #ENC[AES256_GCM,data:oF8OEJcqLYhQwrH5WhMZ,iv:q84H0t8qj0t5Vm3IBxpGWNSmnKx7XRRqKmK7wQWzcNc=,tag:SjFksa3PitlJbJOiukTo7g==,type:comment]
                #ENC[AES256_GCM,data:QNCTkhh/jVriEcRRxQAzlX94KcPVRxRHHOYAJevZglrJwOlp0vzD+/L4SDiHA/QMIfekVU6J6EufBH0M8o16E/XHdtLEfGoR,iv:gNeARxRds50u9CCo4LsQEL0PU9fktVKM6OK6AT72EsA=,tag:fZZydPixxAvYCkgLs/Gb+A==,type:comment]
                #ENC[AES256_GCM,data:Qohzu1Dn4FF5CHrCSdihFibptwE47+02ydRDJZsS/g==,iv:kR7PUde9mFwH2dvePeo59LDifSz2yvd45LlzZkRYF7g=,tag:Ay1HK5TiuuqZcEIKbZPY/A==,type:comment]
                #ENC[AES256_GCM,data:gagJIQ+VkRxg7awpUOi4tHiQ/LwDrIfd8lXK3ffaLeG4rMJWPtDukCpR8LCdzvHSDc/dg7RVfQ==,iv:feGybKlz0kAPMrMBdgGUM9b6usPFRZMc64GWpoVEUrw=,tag:p8jUTmYY8nJuksnKlq3B0w==,type:comment]
                #ENC[AES256_GCM,data:N8fLFPDzJAkyJr4=,iv:VVI0sfiAs4prMAwdorm0b6CXEL38Yc30DC2eTA8MMjM=,tag:JvhvJ+VhW1afjA9l3HTThA==,type:comment]
                #ENC[AES256_GCM,data:E2TPYaMUjS+PsLdl1TTgsZAlZ20gV+K79sPe,iv:gg+il3QPPtoocI0i0AAeJQHJW65zIO5gfeEpvL+2MgI=,tag:Yfndw3q/aWXnYWfgGDkS1g==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/9c28321e-eb64-49d9-a0f9-30c50f9b0214
          created_at: "2025-03-11T18:40:21Z"
          enc: AQICAHhndPrOpg8p3dk1k+xmm13F+N1/BavujEV499t6yDc5OAH3ZXxU7CVlHXzecMZbzK8UAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1NFHuAXUChrFQeVuAgEQgDt2a8X8qW5isCfaTz5V4YTxL68xSNayLN9MfAg1V/lSM634sMFSUw/W5S0IzR+1M92Cjt2i8l7kejqfUQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-11T18:40:21Z"
    mac: ENC[AES256_GCM,data:t9NRwsrWwO3i2h+/a5cMZu4prii7P3UJ1DomYEolxlx7MSDK9E0EetTwRe1gaYwfq4FuU8AuhuPfbHcykRnzDFEf6859eUwOopDzcoDSVwqstA95vNbQMYCGDvpJqWLBZK/AlthTMzDZOI1qUHE+eEnB0fc4a/6UdJND9+hZpHw=,iv:lJnhxCOp4JaLRZdP8MEhUn+rjgQ40na1173mKkxD7vY=,tag:oOV5EwZ6eKQnjg257bNMWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
