jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:xwQo+PDkEZtLEXpzcfASogWbF+HvMGt43XrxB7bhCaIER0sUhqxQNqQjRWEWehsN450=,iv:U7owaBTYJZJt+vFU7fJATYpUYKazKgn8YB9PP+SqNrI=,tag:V8Te1qWsXrt9oOBch6HxLQ==,type:str]
                client_secret: ENC[AES256_GCM,data:bSubP+YTCp2ecXJjdaXLjI+cgcPmy4c8tmv0dGtpq0M0H0a/mNqMZWlc2xAe0sXUCJi1VWzY4Mdeby1N1cqgGeE3iKycHgFflPKYXItnYjidepg1bYk=,iv:Cni2W0pBTVmKm50u++JUfY3hO1iPw83ijb2tToF6QGY=,tag:rLcFeu4C+fTUQE+0TkdDqA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-12T23:57:17Z"
          enc: CiQA471gavdLgrURl2ayglj8Oo/eE520U8O76D8TdoE9INz1YfsSSQA0woZQ3SAFi1aOIWez8epctaD+pcicdCLqHAVYf9zgaqZjtZ0a5w3Mw2H5BpZsafwY3CCGwKSlGXY25f1NHhR1IxqfvH7s92M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-12T23:57:18Z"
    mac: ENC[AES256_GCM,data:dxFxV3u7rJtLC06sEA/yB2w7adfFvktBxVVYro0/iRHJvcSXLCiqize80jCF+dVgbPESkmD47Sv6162MzPnjcu1h6HmEJzweA9k58/jGl4PS3vLg+NcDy+vSNj35+gPtDpa3cyFx6ZGJSo0w1cATsWhcAyS82L4E3XtNDovhBt4=,iv:42/+fdrMfWvLUs8eppT+VahqbAsy/DVIgYPp6OnooUU=,tag:TPLnS+H1hrPX4v2cmYi46A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
