jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:dpYTM4XGb9FbP7BMa0BaOVc/oQ2zALHofQ==,iv:nT1qPDkBJDsCf5Nvi41bcQRpPV4V9eNdU8nSXBSqrVU=,tag:Kp56pqZE3yY5snSg7g+IgA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:01Z"
          enc: CiQA471gahTVRILUBuiM6zFon98BdwvVtW4vKxrbighvsybf+dgSSQAjg8vZh9CHA7jFDyIGE2+LPWcqYi9lDJs3J1U6W+sAZ3EnQ+U1NGD6JVn6M+YT9MzahoOA1W16FypgT2JmoaQ386Y+FX/S7NM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-07T17:21:12Z"
    mac: ENC[AES256_GCM,data:wMEu85g6mMvM4hc/2rzAkyLhPuSfzg4KXIGSY72HSFMlNv2k3gmSeqqqvGaP43RfIFFs80erhg9kqWQhJIPSWjOCWMogAUI9/I8dU7xOrntvtz/CjKQoXbueA5zd/j44IKvm/PFEwQ2N92P65P35IkcgEz7He5TdSHvYGpCRbT8=,iv:Ke95AYnIqwKKh4sl9Z9/wu31C8R1sUpQKE835LjJqOE=,tag:3x8Qp8Ul7zqD20DzA1rKLA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
