jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:JrGxxFdmdHQSoK3/uk+6qrP3xFM871G+DTru88i/nh5Sl3+0iEPNUXAsesqEIg60miY=,iv:MnX9d8GRhpmoUAk5ULjd8WhZhxVLzQzF/fUegJgficA=,tag:EMvXu3mD9Aa8OKMJWb6z+A==,type:str]
                client_secret: ENC[AES256_GCM,data:FBhu6VqKH6patd5Wvbg/BzLcpgE9Baxw4OZLawZ25xCmC3Z+gYBNXwh2uMu69LiNZsdcUtojO8NzD/GC3vB8pDUaHjargWaq9zHc877GOUukQN8gqPs=,iv:m2cJ9O7tKRtV2hTLfWGEjrZHqrwX1ZViIR3xe/WGgu4=,tag:Xv+bbU1X9QwJEfR3mh22uA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:2aBENDIHA3tdNV3RSaQuHdq5QsS6qxlNtrQ0AouTUlMm/cIkVCuyC0f38hqsf/EcI0TY6J0p0G/0Z49WxBMCyw==,iv:U4EBCEVzhQrMVcYA4q6IW7oQTSyj9ciFfKAdKLsWa/E=,tag:V+Uy4ZTlTtDriZnQ9s4GYw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:04Z"
          enc: CiQA471gagERZcKJ5OFC2rV3IRL9ldJEmyuukhMeGKdgjwodbpsSSQAtv98xUIMJCNbpaD9gaQrEHCNQmQhDZ0YpNZc1LCkIDMnI4rLR7Wwh2np7lLl6kn3wxR0SjwPl1G+oL2/NHq6As0/9w20vv6s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:05Z"
    mac: ENC[AES256_GCM,data:10Ly5Xy4Zeg6zC3obLt304eCK7Pbt+RIW8vli762q9thsm5jz25fdXefVWFKGDTk0UAuvWYLuUe/Y1vwxHmUyBrt1fgGtkudwfPfytulmjfekPZ4tiByALPSbMXCCWZvm3WFw5vQHCyIOQCYB7t9fZt6vp033ntxhleeyD+cIgI=,iv:Km104Z6SO6OiLPyBswoK+++cU9ENfDbTJqI+zhfKqOo=,tag:9CpWg9WxWyk+bL/1Pe7Flw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
