jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:FJqyEUYvhaWS8D7UnRBx1MHfTuo4SgsDVKeDrjP0Se7Jw38bHhUvPJ9R6wJiaCGtITUa,iv:G+TJ78q00nKsPM7otNsOPU+d8fWp5oEqSoiIX9tTPqk=,tag:8UwBwDO1t54QL3S40zurgQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Vp7u/rHy6W/ODHYoy0oqJz89w3e8kPV9T0ftJ07bTP4HWdU+EEL0EtS9ex6YkMXujEwDJAgX95OEitvEjP5TJ0GhMLiJnbqYRh5yNcJeKl/w9CtEj3c=,iv:XJkQDDG6LMr+fb13H+2uWK1GBALtaOiVngL7hII3ABA=,tag:tPe6E9KUmDlMlTvZsFXiWg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-12T23:52:51Z"
          enc: CiQA471ganv53XsSUYoKIs5t4H1WgsJr6IxuSQTPRre9I3/mSzASSQA0woZQ3bWgFJVlqa8DsgcaraSP/Y1pNHdQMBb7uYxoPVjA5Rsie5RmqPW8nsajX03taMLaVF6nt4Wm0CgQCWmDHNUQIWrKA8w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-12T23:52:52Z"
    mac: ENC[AES256_GCM,data:MOesdEvCiqYBlQ7Q/z/ts27OD5zbF/wnJy/vpwR/he8HaE2v/DXMjn1vwhYspvjnqo7MSZ877uv6DB05yAQUmWXkKourWkiEWN5Pbz+OV0Z3/N5YiVv9dN/DTy17h6DWe6QIEaEAdInDkS3sPcrMRexivATxby3UH5P191Jp+1w=,iv:aJknk0oo3KEv79S9PtAd0nUY4Ewnxjb5aRPWk7EDy1M=,tag:PAAylxswjghMHgyUOtcB3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
