jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:BDn2Hq/NqgQRtf1vGVz9dSIRGx5xBGnVAh4PjlofdrJxVUp6wTyXoUwrV9j1rnlzifTZ,iv:vTtDx3fwDYDTcwLue4jRRR6uSckfVCtpT97eqFCVyVo=,tag:7y6bMFtl+CCUdbmCn0MliA==,type:str]
                client_secret: ENC[AES256_GCM,data:9wyZCjT9vV/V0xidruFfhyxz6o9d8BFy7jKKsZTkoPjlOEikQlJHxW1s/bXzgM6DDi7hg+TAe+U41VzYCl1wmxiVJuvcVzET4aLIo7bnafRZ5dsAW3Y=,iv:dkwRfyLKIcA+EM6SpEAgXLV4iCMKkmOSWuiBCJ6Mz0E=,tag:0BGUG2KBNxbGbMZJiCGMpg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:+SwOO86+YQ2AFPZ0TRokLJCv38xTYVMjV6xjeqz1aQieM/iavVFYRLwGn1kG+42U9OvP5qsOgFdMFf3SZmBmog==,iv:aaUyEvpfcKrYqbRIgyms/P/hs1Mo6Xkr30W1R+MnAzI=,tag:u9BnP/fURT2nFJsxkkFmOw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:06Z"
          enc: CiQA471gapwgBzOKdVYjjgigSqP3AGveLC+fMaqNU0c5m3pqASsSSQAtv98x/4jOuIQ4p2aeSzo/fU02cKc8kZ3OOBZBJ35o7lscAMsDwL2IaLS0GUjrDDt2Lyw9V4g31PrC/KbuNhQBDN7nAEuIckg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:07Z"
    mac: ENC[AES256_GCM,data:fdQEfw7MwnY0vnRkx6YBmV8WrY6bm7VQ1dstz2Shm1mWRWcEJQbou3PU8mhXe/HHJ0/PJDbUJCC4Q9oObbhBLWIvBx1ZfylWMqSa89m/J/FnT7cvOanuW2uJhNACnrT+U/RVaU09DmEAvdd7qHgujqKccrmbk7I8/5fC3VKvlis=,iv:5N4Cu0zbP6POpFCrS28+BXdCwD5rXECMDQrS60hRBhQ=,tag:t69DEa8wfok2EljXBjHpVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
