jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:KMFYSAfskLBrNAgpq3aTw2y7MpjlBgdb7Q==,iv:c5x1pA3oYvGOH0p30lovLLBVs0+zhWwNRT1JU2NmXrw=,tag:DBv8XWeHBEBEsvKyqxex3A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:10Z"
          enc: CiQA471galV3Nb08FwjIQCr9rbKoYmepm/0xHcBky/yWU6RvR0cSSQAjg8vZVH4fuARRFlMVqnxnb4aSdXDxaoPtWBuRFCM/HS769qVml6AQLK3NMfVi/ALRD3MmV1ZE8XSwdnEaBzhPPe+p1/BuTRs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-07T17:21:02Z"
    mac: ENC[AES256_GCM,data:qy/OH8fJTbtdu0CU2TsMPvBq8yGNKO8NvzHyXi4bo7Q6XDCWAZDS4y6zj4n29oWlBxOiyN6AI7QuYvDxGyd6a7MOe+mlMENeHmNHGg/A4m72cwSJzcvjvghd/Vp1eNoKhwK+ZXli7uMvx9EAOkdbbeFj/sTiLigf9Qh1ocLMwjo=,iv:yEnionZHYuqfwuiJ51sueW7XXY2zA3o5L+3bfFAcHKY=,tag:BKxGE1l05h15f9C9AoQAng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
