jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:IeIKF4adGfQiCbc6fTKb0Yzxj40Ep08gUykuqU8LnbYO2r6DTnsn2b/on9pmDPjKufvg,iv:e+ZxoagorS61t4uvEHxIRz8DCi1hKRX0yQXwA1M+RnI=,tag:FpdOS0FJ3a0Cngk/DXIOmQ==,type:str]
                client_secret: ENC[AES256_GCM,data:ZVVja8Ap8hIdQI5rpNxABb9iMucTc2bYC0NuYNdXmvZT8fqaJ6mvWBhMo7OYM0JZVUgjy0xGEmbPHn+27A0uyA8EhU2m2wFiVXQ3OiYga9O+4Blrqzk=,iv:rBAluLdfCsuJgD3jAPoAASGc+hq04CCXDc+E6f8x378=,tag:DQH0V4yF2f2iUr1lF6IZFQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-09-11T00:02:38Z"
          enc: CiQA471gauRWCvn/OLy45p6rj9pye53fvUuSgcyezXDJfhHHrBUSSQAC0RWojOYJjoFx5ZRQR9Hw9bJN6p2owKWwg1pNB0FrCa+qUC7HdtzhnjRTP35wBJjTh7nahFdyy+smIT+yH/NzjTOCqp0UsQE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-11T00:02:38Z"
    mac: ENC[AES256_GCM,data:iFA03MmCG29mk7BCIoaHnJD4wLiA+tCfwabl1ZlFULCJcK+uJV1pQrI5QytqF3Yi8oAa6ZYPmcllFaRiOEcCt7rW5i6ECY/j8l7A2OerX33xZd+i2ElL5rWi7HPR+Qi20hOgqTiVVXr/whW9dLz4lDpdLnpD5fvex1aDQSKZUQQ=,iv:NbC9ZL5MC+MZ7SjxX31FUgret+VhjQZrqhE7hjQnDAA=,tag:B+g9cWwxMKdtjDgJlpskMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
