jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:CFYHiFYlDQnFY5qRehNX1VYuftPWJ6Xgj65E8oXXRK46idC5hdnSKPsg9IZmL5Tpa6Gm,iv:X4RNIPJFio7D96yILliD5xHbXgtURm2ZdQFeUh8vhuQ=,tag:xIY9j7i2uMVTy8kMWcRbIA==,type:str]
                client_secret: ENC[AES256_GCM,data:XtBs2/YEsIf9JIMyTnBXt0Y6ZS5tslJhLkYBQ7XktwL/LpU/1xjDwQPBxXCFOMFjjARmR55LQrxCbFxmFIIoxZIPrqu+NB8wwaDG0INKgHvYpEQzRaI=,iv:sCvGlG39EB8oRJzgP09IwE6ftSQCUbw7VzVansGiJQI=,tag:m8IUjD4rwvjoWvYUKoGngA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:d7jDJbfrQ2FlV3KswfZ8KNlqR9wfogoop3O9gxkRd5KrKQev7SBeHRYFkxApr39OARAd+BQLbYYOwvpTVjSlaQ==,iv:AWds9gMHLTARONIcOktHrrzZS+TBRvfu++tnhwLqfNE=,tag:OS6ebve84nZGzgvqB/d0IA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:25Z"
          enc: CiQA471gagaXBYqoTtbMxE6fENQHsAzTuSMVjTxchY82PwYnE0wSSQAtv98xc0xmMQMeo1wG+l6ZMfdGxvgqFctyNYgV3VHyxnzeKFj9e87BDivRupd8OuDXtr9RhrGhmlOrP05GZMPtzt8Cm4P3Vq8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:26Z"
    mac: ENC[AES256_GCM,data:TCLAIquy2Gnn/SIfjd8dWLaCQjagjnmM3z5pp4KM9E4BKdoYe1CoBASb/daSnk6J+i/yCReOh8zrsCLqxPCgexkJDgK8Hqt5CvphPp9k3rmdY+8BCbeyIK6akAl92DNo032unrgLBWxoM1WqsPPc9P1TxDwRZ7enSMt60Dlnork=,iv:zaO0pohwU1jgFxsTexmGQjfymaIUH9C1wD9R9yGvRbc=,tag:tsL9Q6mZ/1nHNc0ew4NATQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
