jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:rlFurV/JwnUYRh4ZTKFrg6Ja+PRz6SlJZcNuquFxPw96vjljEJDLsonZFfH72vWOmN3t,iv:R2S/8/LK6YpHx0i3q0Vth/c+kNVZcaHSFQmMk1HpWo0=,tag:7wMW19zuzK+aCYSdhPGeYA==,type:str]
                client_secret: ENC[AES256_GCM,data:r4/kaSuh/wJq32o9K0/1wWh2YK9zsOAelJb05qzFLbEKVJA8SRXCBqUF5nY694YlYcijMY5CtErpylcUhM/RBMhvRo7iGGCdo+2rFA1E7/wRJi0zzBI=,iv:LKW7nHrwQobocGl0hZZJOZTI2z+Mem9CNzv/uTDskz4=,tag:6RRE6ux6WxAyqSPcNZielA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-09-11T00:02:38Z"
          enc: CiQA471gaqVfuSG3RHgaKS7LlAGIYbGSYydwYsL5JAsEK5cPERYSSQAC0RWo4N1dlCm/RRsoa8Kr5jlcf/sZ9WKlro9vtlvyNNrm1L6h8GOWR6aNyNtbNCo/s49mWUFH/8XXYbk4YTBbXL1/EADK9vE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-11T00:02:39Z"
    mac: ENC[AES256_GCM,data:Qoq7vEw+1HYcs2o3ZLdrxGAw1f+z086UrEmbt8lvLKHxPv4NXrg9do6Y35CiQxd6BXVvP/KbXQmrRrRZFTf8dJ0tdLvz4tkxLA3rAQylsuxkFqLNwlg66UBeE9lhRhqSEUZ0NdNLgHup4T9WA9VernDGBKgFi7Lxt2GYsYot0Sk=,iv:gAudfw4Uk4BdPXCkn5mzs/Fm3thpVf7tZ9MqZoflLRE=,tag:GBGlVsC+atCfNLUhvSIGIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
