jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:7T20ATEcaYj7HqRKgrGoql6OvCLV9WZpBUMg40teQjepzjBe3PuRBn2mIbI8ItKPGa1L,iv:mqTweHdrWQ8j0+181+3jaQrp0n++H9G4HAXLxvdv+Kc=,tag:hAqwSRkjjto+TED4CVGa7g==,type:str]
                client_secret: ENC[AES256_GCM,data:jDgSAlvQRg+zGYnzbJxlWNIEJ8sBHNVW5fchjRdntO6WpfvbjXPUazt14W18PlfxrIoYnhFrViUyARNckafXfIkkD8pulOugckwgoz0VD6XvZbSwDh0=,iv:PX2Ky0XnfCadvToQSwwHRKKO8fHAleJC0Q9i1EsAeVg=,tag:KqzFNyS9kDRoJI3OpiOnPw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:dDoAi0hALt/8bcyMhbTLw2RLLwOpZsAVKCdPXe4rQuOO1hRG33v5MPy97lPLcvxHVz635Sh46K5qwJk6q4Kdtg==,iv:43v/htLKspoSusLkdndRf8puxAL8RKngkzlaEuclGGI=,tag:hQYg0eIroQWuC82zUHhInQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:27Z"
          enc: CiQA471gau78Z0KTHP0meHOr8aQseVXHLMBHERkC93CGZL+ht14SSQAtv98xnwOUfELoq8TnRK6Trlc9cVSv375pJE9gK16LHStfnotyCVkRAksnr6+qV4vz2tuN89m4SYaKiRwm/lKepZE82FrG/HQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:28Z"
    mac: ENC[AES256_GCM,data:us8CgiPnexBesLFwQRC4F3NXndPtrHvyGcIlIjzMs8MACg/Hl49i1t085NRRj12U/RJcYZpPVX0GgMchMRqRpJy4doj8kQTLT4/qq9eGsxMPvSF8FyQI6watx6PSJnq1FSiGz2eEDIfwLmRnUCEbn7URnH82sh7a4rTF3K8Gsy8=,iv:4Mfosfo7PGBblZCRAey908ApHNnS/fzK15uhajMu9Xc=,tag:aLDZs1Zp3JD7bd+7Ald2Cg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
