jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:87twGoxOOBMPREbXVqOL0gfEhcdGTuKXtKiu4/wcDcWEhWAtPDywL4fKVgYjKllee4PO,iv:fT48vHDHPQGYclJXKPCl7bn2TL/DnLrWxLdDboMavUs=,tag:ZXX2F132MCtye68HTNR2ag==,type:str]
                client_secret: ENC[AES256_GCM,data:3ZbjAvh7kdmDUmFWDbur81IPEE35gXrdYZAXB8aPDE8r49tPczVRV90HfR2iRU9LWBq2x3Wcj/hZi+aGmPscGAE9iv7SL0f+OQU4LFoOC65ynT3pHfM=,iv:mt4KXPJnQ7uhy5Uv7OLasBkqjOYYlctAj9+Ei6HXJII=,tag:9fJL2UjJfWipicDF/h1Kvw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-21T00:07:02Z"
          enc: CiQA471gapP8MeIeTPQG8yzyTEOtttYqGyqXXk6OWjJLneU86+ESSQA0woZQrPwjkp5XTZwXEh5KYBM1P8jZHFL/Cgf/4nRqxZgFm2HfSDzYI/OlAc84WRotsvGVv+uqoPEjIFARKMQP2f795NQdvHE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-21T00:07:03Z"
    mac: ENC[AES256_GCM,data:yVuHVhMQONQNG2ZHvB2MnOjGakaslNt6hz0qB1EIJcoZh1T2eQNmoABAgsi74pYz2u1Yt35gKzpowq/3fwbveHIcFlHIVrqPn/T+DaLN6ijccPWK9oq29Zr2L0MmpUc5ClluiQ7kaoMq+H1u3s4dwonsyDOqgNInKpk74Vr3H/o=,iv:6PgMdkf+ehUXvVoD8NSN3dswmpYKPMRJMt0XOWor2es=,tag:jY6eAPaUCXPVJqgMgJvgqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
