jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:iYWxxjUi//N6nX/1+ubmf6CXqlQ2XAfCdbC83VQV62YQ2G/wMSn8kR+pEruEegDc3bbS,iv:YQtH1mUDf8DZwCLaWQhpb8YkGMZCBkC9VcvzRPHN83Q=,tag:m54O61ZcsFnyP5vQ/qx4WA==,type:str]
                client_secret: ENC[AES256_GCM,data:bjWw25emclxFcXeKCBE7GjmFmKtl/o8gj1DrptWQkol+SBGx8xd9RIKUbWlSmWsS9qu0YDhkPaANj0LgqKj2cffWzJ7E/BrhmKzT1tBjRmC+EHlVAUw=,iv:9NkfuJVFJVV2+gaZhqIjTmZ12BTDZxvLCAI6O8GoVYo=,tag:8tpLB2e8n+Qw7YV2S8Y5XQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-21T00:07:03Z"
          enc: CiQA471gau7+ZgRDpXBXc9v2hmL9WjKkifwxB5CJJTj9JbPrZKgSSQA0woZQteIG6ZeUHaRm3bv0L5U9HyxOFyeasft+GYaCGpnz7JxLlrOS/cBH0eD1Q8a2SDisggMCinKDVcu73Lw9UkGsy2cU7/s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-21T00:07:03Z"
    mac: ENC[AES256_GCM,data:vDqMVNr77qr4snCBzPHHZ6GyMTyPEWACwebFz8n6Vi+SYgzBp5BEdaOUJXWhhLM9IKmrZ2W6DdYRNYNTHDcXoCoatfeLZFJLljQokDxp/ukVVvNf/ACHyYCZ6jb0Is0glQlWNxDXiDvQVPzDnqpmIHdO2S+kt4o5lR4rhRX3Kho=,iv:e8tcg4ykGqiH2n7+w0c//rKapUHkdWrEP+euYhBmDYw=,tag:GASO1YJlkOYEgZeVfZIX0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
