jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:UpwQHNgX9B9oHmMFki1gP2sJ/NwRCCwg83hDZ5d49jZru+XVo1/oNDdGuCdXTnb+rjQY,iv:a8JC1jC64ZLYmJBLe3Cys/60qeU6yf07bKYoEUx/oGI=,tag:7F57tthHOO9CKE2LqZeAEA==,type:str]
                client_secret: ENC[AES256_GCM,data:nv3OznDPcgW2M1XMzakcX+Zvug11LapncxlFL0XASXxioLOTG5lImD55P6Wy8MNTLuuytGL+ECYDsAWyO142j1WJiHbThlm40TKvz2bQeTvPuzp534A=,iv:is1MPM8xydwWj2yfgywDX3ocslPYKxaU5gGRjsAizO8=,tag:zoZXLYbKJ5PoZeE1fN3cww==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:1tCJGLEPZrKR8vSfYUU2uIh8ODYmrxrd9FqY7LybRLIl4A0/3VWrtCAb79A01tls8pg1wh/qCEI4fP8u2ULw0w==,iv:qYz2T6uIrpm7zFaltxxgAIEuzORcuFQK/MAIEr9wGIY=,tag:ix03fZx7RcLPh0VABdBgMg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-08-16T19:17:39Z"
          enc: CiQA471gahCa7ZIUpKpImEaG/l7d7ugx7wMhm9dynTt+RwjXkNwSSQDKo3g/k/ocaN335lTSnNDO5O2O0TdO27BqHxlU6JYgvhRbG4yBPcPUhXDsDv8fwQB3dVoVBHTMppvP2/amdUfyZtHvvxzDSXQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-16T19:17:39Z"
    mac: ENC[AES256_GCM,data:p1ffbuIOz/UnZO3MV0Ykjiry8Hgl5IJTbrCwLrBTp5S+JQKWoy348h3HGDrgUmNvyigO5SWJ6r5ba0igg4wkKCfZgeOlrQcNbr6KxE7d+o1ZuP71c9gi7b1TU96TIp63AnZZ6bbiPbtnGLv0hSEeVgu3smqjUwxBb75irwNvLLM=,iv:WlKkx7cEXd5kvl63vpJYoxUQgJrUQqmXo6AdAJUfNbc=,tag:sdo54mb7/ECzL7IvOFfP3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
