jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Yexy3RGRtFxIjXh5qUspU/EZOcamqfFrojs9ZSr4496xBZksOqW1sJZ7G/PL6qF+oM9B,iv:YiJESzx6kXN2x9Xl8T8uvKwcd6Cf56pXB9Wedm+hgJw=,tag:QKYBAwtMdPmsImdxwkopig==,type:str]
                client_secret: ENC[AES256_GCM,data:xJRJFcTN45xCz17cRD25sxih2g7zVDvK0fJroJ5/NRirNwzvGzk2e0EdmToUZztoesxw2cA6+yzRgbzqGMUNzabr0UMJKZ5kC9rVbf1tNGqRy5eXiZo=,iv:pRiC4evvmE3DlmllX91i/aTf0+vUCXP1ZyCRJgGOGis=,tag:wbiWq31f9WM05Y7sXmW03w==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:aKY6BtWM21T0Tcwbr58SksNtqlkqlI41b0kAceX/oWKVyDEj4rY1edsaFxMX2Vib+E5LXoRqZPRJQ0rYZ6wbrA==,iv:1CYSODVfXj8+buk6613eX2cGIKaO5aGTzu9ClE4DbgY=,tag:UeLp1T5tM6p+nB++MvvQpg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-08-16T00:15:55Z"
          enc: CiQA471gavwIJzMUi2Fwb0iEUPlAnmOrEyT6qI9CtGhYzZWexWYSSADKo3g/rpVbmPoizbK4bgE2/j5hHND+W0FdFZqWHCl56FmLxdL33/R+OzV9STeXSYjoPkLVAtYkmlB1+nrgZqS9aBoojelMSQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-16T00:15:56Z"
    mac: ENC[AES256_GCM,data:RF3fQXU5vrKM45ymCpAOmj5NFTkyRshV4qtKunR+aaz1OlVKLjd84NGhgars8o8u9ymFYObL8MEUQ4kWdFHmQbQEuByJtKVnlzCAmmf/7cSOuA1onrz8cEM47tJKaeBtyRCaQckVxQWtQva8uFx6a6/KTPk8cIHnOpTOWmtPXbg=,iv:tLmeRV4R38MiP27bDDMQiU4VMlV3Mq/UGdX97m7E2fs=,tag:QUz/SENrSNNFti3CHRWiLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
