jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:JOGM3WFo2iH42fBGqRY7SoBD5grkvlcfSfGkQg==,iv:MolJnEirt7hgaeRXvV+0XAIDyocjFt/UmUEnZgmsDng=,tag:M9r4e+yEyOTeGcdRTcC0EA==,type:str]
                client_secret: ENC[AES256_GCM,data:gdO9oe8bKe7FLWxK51A2Z4sq1CErho0h6Maakg==,iv:iBieW66Y5bi08oVvob2m2VePGheKkh21kYpC8pLrzBI=,tag:0/FDkMgaHjTWWY0BEesh7A==,type:str]
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:bsm213icOvBG8944pSdoM5A=,iv:TDUibLMVS6bThBv5CS22h9hckq7/UJZdP6TZTxCLsU8=,tag:L8hSkDy5ocbOLjhHUGjD4Q==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:ucpPg19qAqB3dRh7c9/YS7uGb8NZOidyYi2CJ69+GNGWWRf4MkgTNwRa8kFNl3+4KpiGVJPOv8PPLF4k/eRNug==,iv:uhxTWwrtdjKSFac46bvy6fndvut/c2fME4+a6wi/MA0=,tag:cL6TUDUzRF6pr3JdE60xKw==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-07-29T00:32:23Z"
          enc: CiQA471gav2FpvShkdW4eS237K59fjZ7ViNAOkuGEGYW1+KN63USSQDKo3g/0NMx0T5JR5TURyAeqP4SU/17oWf4jvfZmmAqXq+eLQVGVaqObAGRYhXig5TaNmZeMpiSsfiSR2EmNKBMm0oAfU2penc=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-07-29T16:29:24Z"
    mac: ENC[AES256_GCM,data:Bpp0dFt3TZ3QX85HSSJHpmpPUVCtPbIUmhyL6qqO9ltoX6Wb9R6BNQftebFnImRTEdDfu94jdo3nBfLpNXcYUgMl9PUX0YV7Z3ryfQjo9n/RREmYZGYzDlIy7S9tG13zTLP0evdS1EHCgp/VQ7Ai52Hpo+fhszUzvkn9BA4Xl1I=,iv:0K7aDZPbCRsB0vUiOCK3fU3y8N/R4gWYmfLVHI+YsQw=,tag:vKKrK9XE5VFZCBILZOiu5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
