jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:PxfUauWxhCnERLh9gwVh4B2Aa7TTX/EKHVg9rA==,iv:3XxOlCYGuZRX4MFPp+JFyaABIhkFIXP5mHGwb2xv254=,tag:InTyn25JKjNfSFm9IaECHw==,type:str]
                client_secret: ENC[AES256_GCM,data:BWgAXxOgYod/oI2QLNTPWTm8wZ5ozwOafSb0eQ==,iv:f88sHcg3EtraU8CTB6t8HPV1TadkWLIbKn/09Ujx8DA=,tag:aiGpqPz39M33n9SslHT2Dw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-29T00:30:50Z"
          enc: CiQA471garNtOaFBvbeDlAh2IyJ8bJcG/aHQWJDJeYpt5sQHGyUSSQDKo3g/b8+cd9QVaT4OhyBC5c49qZB9ik4OkVYreN7L4Sf6i9xgJYKNtcJUQ4kKZJCMsDUEokCgIr8RscX/eVHleBXeWwH0kE4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-29T00:30:51Z"
    mac: ENC[AES256_GCM,data:/dBVBNzz/gRjMFOKgG83JUe++nuL/ai5Wa57X3feb6SCem6yGWcdDkQUuvmSAT/nQt9at8TVxo7CsLWEMLcIpRqsC402uawE1KuYuMo56pblo11Q4AUEqNuepIcscemdowSxgE4dKtRywFeTFAzkkB7XP7MV+1vh5Spxw40HxBs=,iv:QFKuqLW5+dQnwORJCCN2AKhJM4IWDIdqnSJZ0BOZaVM=,tag:AWENHYX6QLRYIztzC1tspA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
