nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.183.114.2

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "main"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Monterey Bay
          logo_url: https://csumb.edu/media/csumb/site-assets-2024/images/logo.svg
          url: https://www.csumb.edu/
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-03-05
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-03-05

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-03-05
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          https://sso.csumb.edu/idp/shibboleth:
            default: true
            username_derivation:
              username_claim: "email"
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - aunfried@csumb.edu
          - clogan@csumb.edu
          - ducampbell@csumb.edu
          - etang@csumb.edu
          - hglanz@csumb.edu 
          - hswift@csumb.edu
          - javmata@csumb.edu
          - jcanner@csumb.edu
          - jguilinger@csumb.edu
          - jmccall@csumb.edu     
          - njue@csumb.edu
          - sajorgensen@csumb.edu
          - shereynolds@csumb.edu
          - sogden@csumb.edu
          - stkim@csumb.edu
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/csumb-user-image
      tag: fc419addd25a
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: base-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 2G
