nfsPVC:
  nfs:
    shareName: csumb/prod

jupyterhub:
  # singleuser:
  #   image:
  #     name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
  #     tag: 3dd516c42558
  ingress:
    enabled: true
    hosts:
      - csumb.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csumb.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://csumb.jupyter.cal-icor.org/hub/oauth_callback
    loadRoles:
      cloudbank-pilot-hub-users:
        services:
          - cloudbank-pilot-hub-users
        scopes:
          - list:users
          - read:users
