nfsPVC:
  nfs:
    shareName: csumb/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Monterey Bay
          logo_url: https://csumb.edu/media/csumb/site-assets-2024/images/logo.svg
          url: https://www.csumb.edu/
  # singleuser:
  #   image:
  #     name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/csumb-user-image
  #     tag: fdcc806fae36
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csumb-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csumb-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - aunfried@csumb.edu
          - clogan@csumb.edu
          - ducampbell@csumb.edu
          - etang@csumb.edu
          - hglanz@csumb.edu
          - hswift@csumb.edu
          - javmata@csumb.edu
          - jcanner@csumb.edu
          - jguilinger@csumb.edu
          - jmccall@csumb.edu
          - njue@csumb.edu
          - pshereen@csumb.edu
          - sajorgensen@csumb.edu
          - shereynolds@csumb.edu
          - sogden@csumb.edu
          - stkim@csumb.edu
