nfsPVC:
  nfs:
    shareName: shares/csumb/staging

jupyterhub:
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/csumb-user-image
      tag: 31e13aec049e
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csumb-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csumb-staging.jupyter.cal-icor.org
  hub:
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://csumb-staging.jupyter.cal-icor.org/hub/oauth_callback
