jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:J6e5BkhelkUaQEqQ4k9QXZIg4To/qEF5LQQjZqZQ/0hHozPOxV2sezKzjhILkRYsCduk,iv:R1NOWIuXcCt1tpBH/esOtZpbQrTO36mP8do63fr+h/s=,tag:cqpCmIMyTea1PoCT4J6iog==,type:str]
                client_secret: ENC[AES256_GCM,data:02Zz90+W3OYUfkXkgCuE6kJPsnRwFTMPCx9kGoHqM4U57YAxLTXJ/Am/mCXgtoPrGJIITP0aUDqsyXo6qr/+eiX5ZYl7V8FXgIf3R7O5zWjTGx7KIsY=,iv:5/vXXFhc10Lq3MyCd0GD5FXnt+FvRZ5O3BFMWh5P4+Q=,tag:EngcJqttqIIUc49pFxNc0g==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:9Z0av5ELstXzY8mnhdOm15CMmbJLgG+tBBdaFUtOJSLIxNzCLeyaPtL7d1dDLiv3aYXDegxmwkDN0QaU5ZWiHw==,iv:a/iObub9AjnILeAgT3iwCAxi8Ewr40ekN45lYmxUWEE=,tag:8/zBw2m8oe5lA7nI8pgm4w==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-09-23T23:21:03Z"
          enc: CiQA471gamgs6Zf0lw+lsqS4Wjuhl9PMqw4D9vnh7hqsrP7zZJsSSQDKo3g/iSerLHrnbfOG11bP0FaGLNtzn1KizYDo1zf1dgySCHqxr6+ALZf2tYt0o6wpUSCMiA8pQClQLEa9a6xyFPYARokGYn4=
    lastmodified: "2026-09-23T23:21:04Z"
    mac: ENC[AES256_GCM,data:EV1Jbn+9P/8ZCCg0gB7wGTe9j+c0FSIW2NFQtYjxn58O03cUOzaVgLCjY43tUDSiXrYRIAe24+xn7QXivD/QNpUWw7ZGvMVsVVrNETLy1uad9EUvgmgPeENUu/TuA7SMBbGTiTeJTUZcSrpNZQdoSAEa5b9hhRkr2yECYRK4duU=,iv:E5jPKGESUKST21kcovHsAe0uM9/opipFhmynE+vrlDA=,tag:0FnUhQjBGH7prWVqOkQhhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
