jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:NRyY5HyglflmuIUqqmITrUJ4L+8CufqljQ==,iv:KsC1NvYDg+ZM7UuhALey74mzZocnGtDw+Us2jpjZDAY=,tag:0RKxBvrGg9xc2hMK2e2XSQ==,type:str]
sops:
    gcp_kms:
        - created_at: "2025-04-25T21:34:00Z"
          enc: CiQA471galwWWwZ/ZXwW7+566jHEaKNaSjnnYRYUb/mFNSQmXIUSSQAjg8vZliK91DIi89Y4tCNrKUQrQgO43UEoc7Cw0ho5fNC7tBDck0Q8kyvittTq7ALoSW5Ff6WairkfN/HtglXMOp1JjEjK4mo=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-07-21T18:35:05Z"
    mac: ENC[AES256_GCM,data:hCj1uWxMUiYuNZ1tiFT+pFM/MvpmLh3vaewn2jmtix8s9SjFG4iW+0jpVTkK7GYcDzfQFv6CJQ2Wvp/0FofNUWsGHK4apXbonK5HUHzj3TaKXqDBQp7d09WtZN3fWRb3yLzBPaUMSrGBsppvFjaCr2Z5wU7ApOvirHfj0SqOmaQ=,iv:aMgtRDpcJEVkoOBPb/cTOCWuwAyEg86Pm77k8OVqajQ=,tag:0CrRUfsd9BCUHWLbmHnc5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
