jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:689rhxQWazZ2GtoecXexfs0xPH0SkV+wP0dVJM3nR1Ilg2s4G9HP8D4jhIiguBPqd1kx,iv:u9riHjchtzDFC2KZELQn44zn8hTqBdBgHmaPs9MbpDA=,tag:CJiuPcA2DcUUlkNjg6M3Hw==,type:str]
                client_secret: ENC[AES256_GCM,data:2z9whIZbJ9CTn7+Z/cQbpiXjXVcS9bsTAhUZxcBroOjoApsDZhnAYOm+foADFNZeJ2rcErA1WJozT72K0o+AvbpGav75XOQS4/VhevDb8r99VCk2HBU=,iv:Xqd8ZkEqPV/3TJuI8/r6aM+OOQStbkILsbJu0YeJFXg=,tag:NA3dC3deu0LwU8iTf/oz6A==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:wzUa42AiQb2z+iT0Ww54fQdu80DxDA1h8cQGcpGLaPWr1wgP1Sx9bEV08/lvbvqUk0wwjtW2rdKzzhIOaruM4A==,iv:6IfkNsch6dT+fERPvhVV7yu7vSTWm5zrAqTod5qYZ1k=,tag:XnWpz5NZBPVo1B7nCfWqyQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:12Z"
          enc: CiQA471gaggClu70bMkJoF8qwgcqfKmzRFI4+vceP/jmjt+39yUSSQAtv98xds471ze4zbwZDc941wwto4KzkMkPDX892D8XmojJhKDkN7+FryCI+BfhLqUHAO181XinWuwnnST+NXbdBRZEshwSbpU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:13Z"
    mac: ENC[AES256_GCM,data:hq6xhxlLYSmXKPMp9N7Jvl+QWrVn3Sw9zBJW87sQl/Vu8kM0s2aU60ohVTW0zCHNyUZUrLGS34+FQgK9f87S+/JPyDW9+goOQrFbinlb/krGIe4vzobw4kPxkrmfFZV7MYQkqORbtgYA3shTh7/Lbeh17GzdVIYhT8a36Ob9bFw=,iv:bnqrrgCCZOyRqUfBwyTp2Wp3azBe5P68iTFM5Mp/acY=,tag:pDnuKrcywfILbgLl9/zI5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
