jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:thee5Cg4f0srIpJXLNPCh8KRsgglh/pEM5x1CyAxmthexZKoK2KytCmQ0nsVZguhuzbk,iv:xLiNwvHZwtTztNuvJsT1uM9IOTyD2w0zakCugELbDGI=,tag:g7t536c9rrjH6fZSfaR/aA==,type:str]
                client_secret: ENC[AES256_GCM,data:zds+oNn8FIIpEu8Y8Xe7HjkpYqkxFsHTTT500T0Y39I5X7b1i2myTNeytttX1t5w9u4eBS7+VmtkVdQAom3ov3uuEo3UP/LqC17ibb8+k9mhls3QHtw=,iv:46gzvaWgdg19zPCFtEquM9lflnekiMQkrbALw46cYtQ=,tag:cQ9KNXgXeUHr8UgYCdf8IA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-16T19:30:17Z"
          enc: CiQA471garLkNmQ3S0DgJDwTQxJaaub0mz3YXXIhHMYjw5zQfYwSSQA0woZQ+QkVMpbCZXsMfUJwXBF/gVd4BM1sKw6AcCP3YtvajvTso+5tfcmslTB8khSTH3JTzRZzpjiovAERFVntZCZ1N5joTgk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-16T19:30:18Z"
    mac: ENC[AES256_GCM,data:SLFcqULJOg3dzDjSFDhxQsctV67/NR1wCOuyBSgzEL/R7X3VWXqvniFFolRRJH8PNkrxvZCHuZ1vMf0QUEu/VYLQ8ONHpF0hhZ8SYP+IbNjWwy+rCnGl5aNMM4zcUm6gNlfBHSDf6ZXjrbOQl+NHeAWPRr+nwyBQzhK+uetjffE=,iv:InKDvXwbehcysmauD6hEF3LuC/WDw5OY5yXTuMTVmBk=,tag:1+iftCJ+Qme3ODpnAF0eNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
