jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:MVelYdaZ0LGeHFYIshUmJLBrKhrg5ivHk2dGXs2X0kPUpuuzXt1w8Xyd/X/tMiYg4oxK,iv:T6BunTmcH2gQSpxavHT1oaz8HU6z5WELm4mexDvzjZU=,tag:kkCTDDsVKfoq40Cfi+of1g==,type:str]
                client_secret: ENC[AES256_GCM,data:QS2HbUtTnftZZfn6Opgr4qxHI39NFb5UDB+/Ar5MGlMTeEi8fzaxXs0iTWIch+osrkOf8FpKXIhxZT/XJ0ik1v261UlyFFPwMMEYQ5PbVeSrFMdG3aA=,iv:D4OpWSHjZf+WbYkGcm4/Z6xdi1Al/nxTxhewIHgUT7E=,tag:RvrjbJK1Rcf2RS0tzC5iSQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-16T21:14:00Z"
          enc: CiQA471gan9SOqdnpKyBcqsnMkU7fAPH21QiWr1O7+906QZyyEgSSQA0woZQ9ZeeNqAR45P89yUKLtfSEIZ4R+JdzewIJM3tdcRH8SeCWB3CSPjNK/myYJ/pE8K2bSNlBfGEJTTik98uQ2K9ytWYQuM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-16T21:14:01Z"
    mac: ENC[AES256_GCM,data:zHti2LPa3qx8o0+nd/7rAOMC+5i/O9OIJthYqgn4wXPjkZE/Sf1AlL41FeRobbtwbwXZUbYY5Vu7v8yReU4MlXviPTHrNydgmXs0KHaaRRQB/m1PPcQjCXlHeQxNp0FyWTmYQzGKDMZ8XhVJUdE1tI5L+xVgWGbfkibHHE2SCPw=,iv:dIx+wv+tiUHcr9Wvd6lusuGjUoj85jsb/d6kjSEErsM=,tag:KmNwMrCzTS7gEHanWwufoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
