jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:9bTF1jKjZIm+yi65qQHPkEb1J8ihDnldycv3CmRV30/VAONhkQobEpITSmJHDTn89NdG,iv:LFrgytIZLvUiW3/1PMwotqT7Rf8oV8ZVFKeCOIyX/I4=,tag:HUu+xD4nbcNGqgsL6pXxoQ==,type:str]
                client_secret: ENC[AES256_GCM,data:3PucBcFqISih0M8/tR3E4yOQ1eQYHGoePQI3Xo51wHwwdPFHIe+o2ptXHbRxJQieR+VefoPcrODedt4tzcjFIKX0b11nkzOs8rBvKrxVx1dfoR7Rk4c=,iv:zbnrhwvZdvZPHC/U5MJ1uQzTcgZoUiTFgahs3D9uUOo=,tag:YiD3h2/5luZBQKBTrbcfyA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-16T19:30:18Z"
          enc: CiQA471galePL65BkijlG6eG1blC10c+vP3ztlJuMSVsgQUDGQwSSQA0woZQ29iMwvhLQ/uymjtlM2snPRqjq9CN3v2wcVAYWwxMGy/L9CxZsWLl8PUVW9/6pC4quUjSEYfMbbb5/xTvd9h/6cDXWq8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-16T19:30:18Z"
    mac: ENC[AES256_GCM,data:r5pkmNPKoDF8g2niVpYWS+er/8Jgtl05DMBzlbMTQ6IJPIO95yxHn77uYfpG9oDsCW+YDGPv3bCL6PRFLvdQVTxFJ7rByviaanl93nhcKlaRjMJlmHizSNQSfjvFjDyZ0AVcEnuo5psU84fSDoM3epsmaoor4ABB37Zl0Y18gdY=,iv:WhHEDP7BTq+m/dyzDLqpGTbMHCZhSr4vJvwU97+52fU=,tag:JdpCXSWYMtwGTQM5zd5nJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
