jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:zeNjre+nX/6Fam6yKGBF7y6UVIwK1IgVQHqB/Se6VM4mskO++n6Ok3TLQMXnBFE4gbn9,iv:fwkNIqpHFYojdJiDsHSoG0N7meyyJn07P+0oM0r1zLc=,tag:O2E2k++aYdQyD3gcfUA+fw==,type:str]
                client_secret: ENC[AES256_GCM,data:lAXwEOMDM2jmCTHX6H03MqqtkVIlYAJ4Ph1Rtx9J8rqmKFqka8cR5SQOp8sNuUqTNAcoHLVaokUeBWmahIUZNsEe3mpdp9iIT6wAwNutTiphc9OAjVE=,iv:5n0+tEYLvvJZ7UoQme7WwSIjl9TZLa1kr8+z+fDVcBg=,tag:7IxUeDlHz3nJ7HgtzVfUZw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-16T21:14:01Z"
          enc: CiQA471gatG9LDjIy94PaF+2LONYbX/o8/OuKW2fcav/bsk3djcSSQA0woZQNmcRYHSoKQCAxVAr+EBc1OU3nWbiN5M0igWRqD9PPamRPBlFis68H8XIFGB3M+SpvlEbHIkcFZ/S89XUuUVpO5LpP6Y=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-16T21:14:02Z"
    mac: ENC[AES256_GCM,data:FtJ+/5d0+KU+hu2rdsekVzPxMsEkUW9JB8J04mnCiTg99wCxHfkQryp/wAsvKg2jd2BdgoDGWhwKMz8be5aT0xAOrEQUwLJ6YrLtepIafGDiWfy2xdg6Fhczco1nbDMFEBOCM3cAN/cKwuelUbu5JHAHXd/+yUjENHP4MkDx1v4=,iv:eHNtPCKup/xhZf9FCTescNMs6xw+3qgXxVYw2K4BhRM=,tag:Yt0are207h7R7Sc0iQcnng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
