jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Zzye9qdeULSwMqfYV6McjcdRSKdmSJwtzPEpckoaDd9zAahu7fH6hOpGWSGcEWAqx9/t,iv:UCsoot6oDAKpdnPoNpl65yUBn001wLQsZOY7Z5KOGFE=,tag:yVyjO/SBk7XRWezZqZhd0A==,type:str]
                client_secret: ENC[AES256_GCM,data:aKz1UjHl23O2YBol9SFN7Jq2mYia1BohJValFQTNz8PpC9YiN05yI6V9oz3LPTeZBGmg0Ta35GUaXp9aPdw6o9WmvergsEXqfgJMOPgZ9EXv74KRnjY=,iv:sEMdHWUOrYIPR8bKayGM1QWzYE8h/Mnb/yDMC/1ChFI=,tag:cTXwHJYJwjQ3OEPKWruGOA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:VwLuZgn8lBp7KP9DC5WnJusoPjSrbNkencgPWo6uWz2XzknbK5JHjeskdsCcfNHlX2WSNd9FNwcToFL+Vyn0uQ==,iv:5looSq+apt8F//CLj+fAav1mjxUgcC/WDOThZvqYsrs=,tag:GTlYvl6nnkTIdlxAovfhhA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:14Z"
          enc: CiQA471gapLZRmit+XtFpO+r5dt/8zf2ykLYAQlSxQWEmXXkxq0SSQAtv98xhB03p18UDiywTu9f6C0ScgNGS9bQiPThQ58s1PHqXMRFwmS3ZbYqhWf5RxXQfG8ZmAQVgaceRRS5Bs1YSP3dTs8lga0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:15Z"
    mac: ENC[AES256_GCM,data:mOPVXsV1rRuxg2aMfep+f7XTwIjjn6iCv2Ur+1mt9Zjxm273R/XZNkIwaZ5VN0hQdS4+egQABQVdykvYLcaWevhbms8ZDkrMmitnkZzPcdAjv5Oz/el8amECZHi9ydY+KhZDbrey6QjtdB95WoC1G0Ujpf8fZ3mM6XTyo8HB1WA=,iv:e5fFkq8CYeneqm2ge/+RG4N+qEOUoupbsibTBceGdAs=,tag:aYzzjVfZ7BqbYEc8/eAYOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
