nfsPVC:
  nfs:
    shareName: csulb/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Long Beach
          logo_url: https://www.csulb.edu/themes/custom/csulb/images/logo.png
          url: https://www.csulb.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csulb-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csulb-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - shabnam.sodagari@csulb.edu
          - Kagba.Suaray@csulb.edu
          - Tianni.Zhou@csulb.edu
          - Antonio.Martinez@csulb.edu
          - Babette.Benken@csulb.edu
          - Florence.Newberger@csulb.edu
          - Seungjoon.Lee@csulb.edu
          - tyler.nakamura@csulb.edu
          - Rebecca.Le@csulb.edu
