nfsPVC:
  nfs:
    shareName: cpp/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal Poly Pomona
          logo_url: https://www.cpp.edu/common/green-and-gold/assets/logos/cpp_horizontal_2c_green_rgb.png
          url: https://www.cpp.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - cpp-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - cpp-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - jungjinchoi@cpp.edu
