jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:vC9cMsRzBbggYtYb04RBMG5Haq7nMaqMOw==,iv:oX8T5UC+0edYweWus24Xm1ymPZW/65EwvEzxOXzugs4=,tag:6KdYmENGNM75SgX8oQTxjw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:TFzTg4qC6mcIu5EPP/CXm/RJwppCyCB2c8pbrRrLbLTEK1onnhG9GpIIWpWdaJbQ16l6g+iBz9qk1hZuFXgYoQ==,iv:Q0U6I8CW2M+jqhewvEp5oMqC52+KwwADc+KaQmF8rGI=,tag:CLYD6wDow6LY7Fp1+PcSAw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:27Z"
          enc: CiQA471gapWbloW005zfNO5PWdDYCTwfH30RH8cZveHem+CbZDUSSQAtv98xeg8Yq1ksCWqFEB7cbBR5Bx/NOL52X0ht6sshL2aTiP35ILOs1nX3hEVCMphc6YmycM2xWmIyOigDGnyuUHWHUwAJwr0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:28Z"
    mac: ENC[AES256_GCM,data:Z6p47REnW5QHU+8zjE+WczNDrTRV2+eg2hHZQ0fFRngu+brAdXu7DgXx6KVPhcqZaHdU9tilVWDzerbdF1y3cv92Hb5IdJB7lfhNJ8jPohYKwzlxzTe26f4DsQ9Mwsv78Fwcg2MpW3NUbwLIKlNAyDtvQjr12jPhZiD618M0jzw=,iv:oQG14xQs7Pnx4zrJeHl29WAoYNNw4iI1kL5XvXfZ6wE=,tag:jPcc9Axb1JgLrU21mwjDOw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
