jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:atEuQ9UFV4J799LyjLLl+9QoXym/vQRSeg==,iv:GtoCA736fta1crdm7oHhEMefR+s81vI+FQoGKcaFB00=,tag:sEI+uzn22o/b7FVbIEhklg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-12-03T20:22:20Z"
          enc: CiQA471gatd9OGNaskk19iym1tAGbU42WgZWcTwesEelIkuXijESSQBxTImxnQvY3XEZ7FrYpiHKir+4sSmYkHEC6r+0zHFNV9537jQd/MwdTvTtD8uN3vIwCkVIMZH4bpY0DWR37PRZM7Gph1IFV6w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T20:23:53Z"
    mac: ENC[AES256_GCM,data:YzUC9nSkAnXlnBzuA2eOiACFXUC+adOh1kZwBXwfOSPD4RttEAiE9X6VnXa9c4a8QGMZOMGyVtLV5WP/XJHw+6M2gF7N0Pxr28NyuwMTTtOVEBCI0VkBAUxFR5yzcLkrhrVsrQLTsxgNSCXJ5iUWeijUxwjHsrtPQz2gXPFXiMg=,iv:9qlMG+obx3i8iY0JGCbahg7piY4HHjvD24EAMASCHJ8=,tag:3sY4+Hpdf/WeOr2gINsBJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
