jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:cCV9,iv:U1kPDvj2Lu8r7ceq9ZZqvBXobgZJS903FVEgkyBj0NA=,tag:nla1PJMB0/qAji18AbxSyA==,type:str]
                client_secret: ENC[AES256_GCM,data:ptSQ,iv:BFOFRnNxSny4gfekRpAHwG2pt8HkIdcTbNXWiieFEnM=,tag:RE/Emhhc2jqg/zdPozCSCw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-12-03T20:22:20Z"
          enc: CiQA471gatd9OGNaskk19iym1tAGbU42WgZWcTwesEelIkuXijESSQBxTImxnQvY3XEZ7FrYpiHKir+4sSmYkHEC6r+0zHFNV9537jQd/MwdTvTtD8uN3vIwCkVIMZH4bpY0DWR37PRZM7Gph1IFV6w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T20:22:20Z"
    mac: ENC[AES256_GCM,data:7CfAUx+KCx5fgVhwzEjaAgIFceMZpKTibSYr6wZh+ePeK+18u/zTYbnQC2mMgPllj8Con+nmqNDTnnHDvTzAwCKWL6yVmS+n8RUjg1zKnOBT2PiQ6HGStm2YCfE3CvbBqYJXUeI9+eF1/FGDOjItmbpEqVMHj6yoDZATrsGzVF0=,iv:bgpACZrNqwe/A3SM9jK3v6cZFpu0vfCwPx+8/ny/rEM=,tag:bLzdj0bL8RV3OihY2cTbfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
