jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:/vgSZt6LVYJXSeTPSjNb7SS415yyWuvTCg==,iv:qh7z3SyK27Qt306oP0ifkakJW+dRVZfXouuvilW44ds=,tag:GyTikcph/BM++xYC2oViHg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-12-03T20:22:20Z"
          enc: CiQA471gaoc3Sl78FPQXWTPO9VxJjMSEh47yb+kk2TgFlS8daVASSQBxTImx6IG8tWpflTyBAGQKlfuTdPpADcPYCmzbp05A9IX5E03h8EFxcQMpNrt5YqOeLkFjO5/ZyRckltA6hnN7/OePnbG56MM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T20:24:02Z"
    mac: ENC[AES256_GCM,data:9wNTuiZTBfR/bxcq9Zs/7DvE23IRjmkzvgNuNdwWbPdhij3cVQHdVa5JL0DVE933je307ZhCbKD4JflMtqPjMKAC9arIRjWeDD7dn4vhLAdcjvXpiE7rUlvJjN4K74Tvf4hyoupiACpMSaWDOTC7a0LI771cOhWdcL99K4gqToQ=,iv:9jZsg/N56xT+35GKQAejTJ+FHrNnDvsGVFFPdKqAaCk=,tag:DHb7D5cjpv4qUSrd3kFd2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
