jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:5xvfyDv1keySqywPE5RL4qGNNM1Y3zfEXA==,iv:FGp8p/XGD/bgc1EBh4ArJyD35ecpLT953DMMp8/oVY4=,tag:XBtSl1iQASAXuvdMCjm9kg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:TC4jJVsoCYOUjJ6uLTWfvM+v9kEqhzvUNPspYYLdgAWmqA3GsMdhRjixT9gozZablA5dGzhzd5ZOvb4JzuvgEw==,iv:bmn43cdKMI6NnnrbO75FxubNcoh8yPlChIMP4hrpe50=,tag:TEdGvuqIsgxUUh0QEuFrIA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:29Z"
          enc: CiQA471gago99OvHKVpqLun7Ypya8DCe+YH3Em6PFDSthkEGRPISSQAtv98xNYopxPZVWAYLS+bwl6067uy5ZBBc8F8tArF70/s+Lz6sin8feAe0SN9TjGf+VCJ3Iop3wd7sfCK23pRBRzZzQmLFXRM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:30Z"
    mac: ENC[AES256_GCM,data:9VD5hcWIQCEbkyrCC+5Z83rz+5o/Fv+nL5XJiSJ2U0u9ZbH/3pONVloopVr56g2ZsxrS4M7SZpsPcqv+RwWIwdtp1GK2mHbk8qxMteMOxDWyW+M5qQkpQnM8GfV7PhZwUG5Ei24Fk5dtSEU0bOMcp1i/ZIa31FmFku3685xVgZ0=,iv:2SAdNCmbnB/CktZIvGvodWS6/gxOnG5T62zeGg+j4Fk=,tag:YXdZhzq8rIFBC2WACRGbkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
