jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:22oZ,iv:LzD/EugCwq3y31FFKlQmv9ajSLrxFohCocxwlFRF6gc=,tag:Pd9+XOEnefS+eyDi9rSDtQ==,type:str]
                client_secret: ENC[AES256_GCM,data:3Day,iv:XRj2Gd7Bp/5warznvvIm4iEbgSPr+KB/gDf1JJ4lpIY=,tag:rHG+7ySfdt3amaijvY7pmg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-12-03T20:22:20Z"
          enc: CiQA471gaoc3Sl78FPQXWTPO9VxJjMSEh47yb+kk2TgFlS8daVASSQBxTImx6IG8tWpflTyBAGQKlfuTdPpADcPYCmzbp05A9IX5E03h8EFxcQMpNrt5YqOeLkFjO5/ZyRckltA6hnN7/OePnbG56MM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-03T20:22:21Z"
    mac: ENC[AES256_GCM,data:EPnI0um248cIdI/XZ9GaOmwQNWdn77Xf3iveaBDGr6X2+PB1kiSqdnJljx47MecOrOfLkik/SSijEPTYNoWAWLxkvaEB4BljNA8HL8xkGO4QJnCOteoD05UP/vs5uiUA5jr2N9vnqhSfqfMqfIPkbK3vrF3lnhNJEFowSUoL3Xc=,iv:fo86KNd8ue39yvM0W34mFcHo6t3qG8mkceqmiE3IRUI=,tag:WGu9vb6H2FtK15fVLZPq9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
