nfsPVC:
  enabled: true
  nfs:
    serverIP: 34.118.238.48

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-06-30
    # loadRoles:
      # cal-icor staff
      # cal-icor-staff:
        # description: Enable admin for cal-icor staff
        # this role provides permissions to...
        # scopes:
        #   - admin-ui
        #   - admin:groups
        #   - admin:users
        #   - admin:servers
        #   - read:roles
        #   - read:hub
        #   - access:servers
        # this role will be assigned to...
        # groups:
        #   - course::1524699::group::all-admins
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 751d96e2ddc4
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: user-pool-2026-07-07
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
