nfsPVC:
  nfs:
    shareName: shares/dvc/staging

jupyterhub:
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 6d61d3c15d47
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - dvc-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - dvc-staging.jupyter.cal-icor.org
  hub:
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://dvc-staging.jupyter.cal-icor.org/hub/oauth_callback
