jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:YrrtYgDgaTf/mRmWP9RwvKqvIB7sEFxVJiHSV4gE44n+uiTX2m+0Mw1VqsCzuRvpZLc8,iv:KuQ1l51Hj83rbii2drchxNtAiZowbK6bZN8+hH9YgHI=,tag:Cyi5grFKvaU4H2YU4sI3lg==,type:str]
                client_secret: ENC[AES256_GCM,data:KXacLLm0EoqKTaIEyxAlwuH/K63oqdF2PQhYzBxhhn5zTZQZdqqng4j5RZECi/plequB7AtN2mmFZcqPmdfPBxpVK4oZn/qz98EG5DeFCWFhkT40coM=,iv:i0vaVot9RD9NUsePCGCykzEuLFKIJWrggCBqhJocK2M=,tag:eRLAi3n0tEatCWp1eESxDg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-28T00:28:45Z"
          enc: CiQA471gan+9c0OOUvAAkY/DkiYH7cy/K05Jb0WFFsOz9Bgk7uMSSAA0woZQooeyV7394XKbdVD6N2aA+zQTUY+sts932LbTAZ+nv06pXfudjMowsjTUxBbqHhEf3Fs2TXdv13DzGnzr1C5UPdKwsw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-28T00:28:46Z"
    mac: ENC[AES256_GCM,data:89al6snr8hgcJYF0H4hjpXpa58tlwvbHHKctkbQpGTStocxsklu/CW2+TD8IRlR7gxC9+EEETaS3uJu2QP+lGLpYAdhMGGL0FZmqZC863MqkCrHg7rFoNOfxfkxL5RPNyU2/JP7UIv1uuDHd5GD6aPJLXpwUUvynn1nL7yrwazE=,iv:p7vCnlXB5zr5uAClGb4Ac8gkcT2e6lxI4QDRijO3Al4=,tag:frlaYotw6QbLpepsBWgA6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
