jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:DcocbIWvmc9Rqaj4vCiqsP1xLNQfJ81awpzcbKB1PkDwL+y0ut7d9EED6+dnjyyfrZVR,iv:MkFg2XKLNJs0u3hSAuBkveQVYBcJc31u3poPpWE1PpQ=,tag:IoqBFZnQW10DRrhd072v3A==,type:str]
                client_secret: ENC[AES256_GCM,data:OqpGbO0A8G3ZoGKWXDfbBhPkUc/0w1+B3uqzn2XhQPB4phFLS8jS5JRFIabDbM/egjj4gzBFKTnaOvKw7aKlXGosnNFrDf3N5o8rev2kd/QYclpCfsE=,iv:ra/tvSYTri3J+QbLmtpX1KONSSHf5CxVUCKOlV6mjhg=,tag:PjxRh9oOJHEtDyA2GYvhuQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:MuBigtCJRMKjsJW2sSIZx1NZfHvIwro7+fN2Y0Kl2V9GzYW2kw9onHy8AT6dNq/ppfiq2eEBmRjW+j1yWtB8fQ==,iv:iLpz7O9jnygNQhIudPPgHlUE6LrICiPGNJu+bfobgsk=,tag:OxrDAUBbAhQAh9kBR/DPjQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:33Z"
          enc: CiQA471gatZYHVfRWciLXcMdU4sLp2qO+9+gtEh/xYkCjgLfvVoSSQAtv98xSXvDyfw9/6zlMMs9jzBxLOUtBCmeYv+cWLpt9/CMmX1S8wb/nUDmqoJIKZ48WFX4Hwkvl/Y9cGDqX3THko8LiOOSibY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:34Z"
    mac: ENC[AES256_GCM,data:yzqi/uHRnXJwCq9DRXswHVgHolnuEWQBFawoAzvYMvPr3expt4NJwGHrQ8F87tFhepdNN8b30U002NpitH0aGefhET/GpcH95zfHlJxdsxYf6aATMQM7hqw2lOmoUbeUSqSXTqTbaYl8BSiEdzMAs++zb5S3R4/1yhJfD2M4uZg=,iv:blZggioSQ2xNufJtnmDWhbpuear9P/c2ZdnBRVoLTe4=,tag:TXynATztJYhee1rqZCpUvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
