jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:V70Wb0w7/svaykOLdhR73feSFs0QPMNS10Tfven95Eke9OtNoPTzGw18J4Z5GfjpJdnO,iv:zrhk3KyYpDCLR6btTWv0absq+sNu8JzBu1LDNxl0e3o=,tag:D/ZOfEATPYfeAl33rHxikQ==,type:str]
                client_secret: ENC[AES256_GCM,data:6mmQ80M7Ga5XbeW2cFJybQ7qqgEXWEe4bpcmpyEi/glqyEwuKP/oEAyIaLPog7jfMW4c6XkrbHjC46lpsqmoz9E+qkrmrUn6MMrpU9A6InwHfEQBOCc=,iv:Es53Au935BO3P5Jl420JQVm+zlGCRexYZ6g4KJCQxFY=,tag:QE6zaaTOhfA18t/+bQhitg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-28T00:28:46Z"
          enc: CiQA471gankf3fuDtdl3u2k1pfsRZE0vs7T5tPiLI3XC9qyVT+wSSQA0woZQirolAGaBjO3CpZCNMOthfIC9mTi3bXzRauAhYUIdcFbCCalqQupg8wQowPVn6BQFQGitB2TlYiHcU3bcM7jlQb0I3Do=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-28T00:28:46Z"
    mac: ENC[AES256_GCM,data:f8jwdaNpiG2300u4lPYCYGAQIpLDJyrrBbu03G1G0+Zf0xwGR/8pEgQfbg8UWR4egWyoneZFOaBKI3st3+2lt8qe+wXT9Z/f9AIZsjaca/BrKKlPjclC+wT4X5MnZabTMHPseTvESOidWq6TrwSfSxXUClLj48cCNOJ7DA/GCPY=,iv:a1DYn4VHfHWvUk8IOWY9KDw6ouLb0PgX7jvGv6PpVb4=,tag:WZCStihiZrRErOMwy9t03Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
