jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:zMPqiV2bQ5InfswdWe+MskVCpsf61Q36SQlYaKNB7KBWzOU8gipb73J7zlMej/KrkgmR,iv:4ra7WKR8Tv5OA8VIUQtMgGIUtc0J5zlRp3Idk0dlS2Y=,tag:+ZryZZHkgw7Bbfww0lYhfQ==,type:str]
                client_secret: ENC[AES256_GCM,data:4JxilTW9H4RZILgaBLb7D6ubO5AIkGSr/5OK52x4F2aSuCOwEblhYFbQ+27wyTo4BcI5axKKbHrxTpBtCfuvqYDHL2z6wp/93MP4bzSwKFoMZSS8FgU=,iv:kx+7e+r9F1i1ZMrMTlyg1XDm84YFV4+axDSABIWX/4w=,tag:00bpttUjjFsfrFu1/F52Kw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:SrHPF588S74KqUWXLCjCAymIv6VFTcLiBFjMfa8avsP1ZCVRAP/kOR7H3NTYzdoEnQwF9RozhKIcclvxA6KTOA==,iv:LId/j3jzITguzaBVLgk8ylycf1m0BcZ7L0q/qoJoxUc=,tag:aCjgOjAexPSMCbLBqF6x7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:35Z"
          enc: CiQA471garViG+yWENPoYCG7TetXB+LHE1IwDMP95qlTEel8EagSSQAtv98x8KEcD0/5jtwkSgAqmI+9w5usAIXzpkKDCPkDxWBNZpeMMZxRgCfQc81cklYce4Yhc+CBKxjybf6OHCoTcPUYdQh8nq4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:36Z"
    mac: ENC[AES256_GCM,data:eLpMe6WOXyctwqk1kM3h20YK+AIghZdSLrcOmKdzKubXYfe+IpBiwmZcbiKbpqf8Sehkuxd87SoGwcfg0jo0blgINVDBupEe6OIjpghDDoBSmWnG1FNmiUs+kLOmt2LW8N+JyEQzSw5FGvVtFffpRkz+m/uDBjWDSelHeZrrJpM=,iv:OFBLcpmUloJtEIrEzfcx+erZE4IgB/p3DDbNPXC7M8s=,tag:lfgNuTMPobXXtWABSGwvjg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
