jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:uyF5c7exT+Aw+dfotq33G1lPJoj+7f7Ltw0nC1D8L2sUFrqJH6KHDtC0KrPrqvZddq50,iv:tJSKv2iBEoqydYx818RmYRTOs+0OW9qpXQ1RsX6UJtc=,tag:q//As3rLHg+vHIn2DQrCiw==,type:str]
                client_secret: ENC[AES256_GCM,data:QSm1ZwpVQNcpUep3J6j5GOUp5W5U3WgeYM1eEnCqCb0PJ4yNlMZRnbK9Zj8eOosETYCJ3/k6IjIZmG2CJy20btlSaROQ0bboj1OZsidGAMv9S/KTBz0=,iv:uHRl5uVb4WRd/j3o8Hcl/gGReiTlpdMoez2IgTdX61M=,tag:yByDeZiQTGYu6Wxo25c1hw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:mhEehUCpNWju2Q9cCTGQfvVMA0Ll6s6EF758V3v5LWASEUUyWzftR/UHA98Zs+Oiq74VUGRzF/9VgW0p2Nm8Pg==,iv:hRLEGUbO/W6y0XnMneaFkb3mAAUz0JW09bc3t2S//8U=,tag:SiS2R0ug++PDYNCxnGDo2g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:56Z"
          enc: CiQA471gavfUPpvrE3MWalW8ulBVn1F+wKtjOBU2kk5fKD/tM1USSQAtv98x5S9wntFawUredMw6HgYqa1nwNXngVjxsiyTaEgL5wv37cgbPxLAz7rKRXRH5nm1WUyI/ZvHbscazMWdPLAnAdq3Nl7E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:57Z"
    mac: ENC[AES256_GCM,data:0wNx9ExJJDgCf9Ogj+E3CJTF45YoDgOzzxa20Hdrp4rPSz0FaJc3P8k0xshWe8lbAfl2QnQQN4Qy3jn7Zz2QIBwFPNt9HOJ77UEy5gcS0SDvNTz2/Oam5D7SxijZ9Y47rcIt/l6/f7KRr33CvMamJe+YZoq38KAwgPxw79mgdvw=,iv:2kVyh0YWuT63rEgN5ZgpihQ9ZDKNeFhC6jAyW6zfvAo=,tag:sbnCuiAXhbh44YfkglsoIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
