jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:2VLV++VdNlTX8AOcJD3xkozw2nn2mvXSluVVkIPRt4K1+FRwY72Ang2yEA7mbmrMwQUo,iv:dsZ6bBYwRoEHOuePdPDXOzY/jqajCXW4a73hWVZTq9I=,tag:f9JZZn9sHHsxsLj1yNq2zQ==,type:str]
                client_secret: ENC[AES256_GCM,data:iyfsmzqLyLO9aJ9cNmwR+L+uXOAfYgI9hOE5hD9gGgb3WXtiG7HvnnedGtawt4Tl3PdyfKLbKTEkYxlX73+/cQp9VFfdv4pmnsayRVOPcr2SmRRHsYw=,iv:NK5NT7y7df7L9JPOJsKQCjPHYEwkCyEeQpgFPxRhhl4=,tag:DdW+sP/jeNCt9hc2N9B+LA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-08T18:38:01Z"
          enc: CiQA471gasyrcqo5BYDOTn/ijxv9VPjDlLY3ezf36l4CBiwLRw0SSQBxTImxTPZlIUQ3HiijCL0KlHvl+nKeCDu7kAuzFzdqPQpgJpIk97Oikh9YIj+VtLpw6QrFuUc1f1oO57nStk4NARIvCXBC8no=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T18:38:02Z"
    mac: ENC[AES256_GCM,data:SVHqyygOY94T7MGPLYAbMS5uFknyEHrQQZmp3XqBgAIfRJZtQZIa+0Dq36qzT4BG5DQz58SVx0W5r0wQSBBTFiXHX8GfY6ccD/i5ZG3SOLX2N01c4lVmBIZwuaPokZJfWOyWHt5kTZdorVL5M1SxfkQLH7ap4pzMj+b3omAqoJo=,iv:0oLv6LroaiGuvReKL7Tr9vYFDYZMH9zRHDjIkZPfGsg=,tag:j+cvW3No0EbryRuS6LVn3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
