jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Yvv5bp5Kgu1EBivz23rnyV2h5kju3fHam5xvQptHXzm3HzsfKKYBcxECfh/fAukk97AW,iv:4LCOU11zy+JG/RquZPNGUEWgvFqslDahtpj3ALMC6fo=,tag:/oWkWA5SCfoLA8eA2Iz/8A==,type:str]
                client_secret: ENC[AES256_GCM,data:9ICNCWn3wtMSEBwaHuN4MVZlkJvDFLuAxJA0RehyHaXGzZzBGu1QjfIVkCRFb5P14/2YXnCxm8KyMaBErBU8QyVjtAX88ZyEwoYenYysGplIWlzc5sk=,iv:+wGb0qt6ZcSN5Bq+B2ZuJrrCnoNrkEc/4No0boxKB0Y=,tag:nq8vGDUNHWOq/UkMc/4lcw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-08T18:38:02Z"
          enc: CiQA471gauFeWb9lzAm1TwIhznkCbbcH+seYNgZUt3459pchR1ASSQBxTImxX8FLgPsdInFwKmQlxPgB12qD4kQ2MF7uFTiZ8onycZGOug+1m0ZODS+bhqvYnQM49EOxhnYTYZpRZ8+yXifmwKuOu+s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T18:38:02Z"
    mac: ENC[AES256_GCM,data:Thym2GI3nW1pkyev6UeDr6+e0RuC8V6ERQX/Fk/qqbnpWeD1FjRIa/DXV3rTWs2wECBEexEt8CWNcwbB/h7JVhVcjGKoM3eS8xUJuBkBT14/Glgl9dnQjeAk1ocjF6wf1/PFTJcG8CzGLz4CUp2Q+5z+0ZkM2iXxz9H1Vsw/rOY=,iv:WDELWeVgnEjikMoWriLZBl5aZfnsmm9325biiDFPsXc=,tag:J9Rk9g7maK1tsOUCrEfA0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
