jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:xk+fQ9txvmCQ7fYnIx2XKPKEBQpAfsSiqX7uh78wVLJSK6ARiLMKY9WIA6lZpNnk/iI0,iv:JWCy4NQ2TIB7UL0zCH1bm/fDlG3K60KmNOTvVEP/kJ4=,tag:ZNmAtsBJTNJOZQxac7CzJw==,type:str]
                client_secret: ENC[AES256_GCM,data:p5/Gc62R4ZuQhejOCb64DMqp2qN1FNjqvVC1i59lGxNOYTsQHBFjhGP2HmF6No+5oanMpreGcR3y//n+9aaZbwKKQDKyRm4Q+Ffhoblf3O+K9VDf8sI=,iv:GOdT2Z3r2C7J8QadTRM9oYJ9Q1XqRIpLkXW6zd316Qc=,tag:34qtfj/YrSHHv88WVgr+jQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:s6ZsKJXOznaT81BicqdHGhhMSO4wKhbEEV9hlfDBwz80pHx83I7bCXdWCdtBOS9tjSZqeQnToatywiSTSeK0Tg==,iv:6UPfSqlAwijKCfjJatGqAUVtpRDN+m/GCE1wJ8rnkQQ=,tag:/9Ggdmws1UvcdFCRCn1kwg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:58Z"
          enc: CiQA471gatfUGfu6rA1uMBF8b0/QXTvruEW5D4PlOYmmwuRAhTcSSQAtv98xm2Xs/5m/G2nySOtMKHMOQ5JAyXGrSfvtZBA+bOvWyc0iSX9+czD8POOKftnYlsJXZb/8ng59IUnYbpacWm/TQlCmvcc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:59Z"
    mac: ENC[AES256_GCM,data:TMlUCdsgLlOpKh/gdkNbAA2ihVwSc5GShR7kZa0VxtNIwr3Lu9CPOm+SVHytK8h9v/Oe+6sCczb8j1pnIVmwGkxoO7pbl0VUgq6EfxJ+EvqHqop43oD0vJWM3uos8X2SEPW1UEugdvXU3axq+AT9y5Crx+BPKLo7KGSvzlibjkE=,iv:RzyoKBaHkJkttTUdS2WcbNSR10iSzM9pImXBZmA5sBo=,tag:VJgGAQ1O/GEVDsBEFZZPXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
