jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:sMl/ilrRjevpxhFeNT/0/ggwXb18mUOoEQoB4F8BdkGp0kD1cLPGJFMlEkN2JzQK2Tg=,iv:exFNJ3lNN3A3YMCoejQovWoe7h0LulemIN9k95S6oaY=,tag:FiJegIkXILqNyY0jG8bYTg==,type:str]
                client_secret: ENC[AES256_GCM,data:1p+JfeviMfUS0O3QhM11zBkAMaAWT5j7PsLrHcCe9kyIq/0PRujPeyIIF0drw4tzTs6ravaTKXEkScz7/AEEsw+AhLVi9tKSPFapEyj12WymN8aQLpw=,iv:Oph/QZwXsSVkCdt5Ed3xw1r0Haxl6gMOvIAgevudydo=,tag:/6DyezxaOZrNHKX0j/CyZg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-24T00:09:23Z"
          enc: CiQA471gattbzzGRqK7BH+uCqo/Z6v0m4Ihdwy5MA1hcPCJU8CMSSQA0woZQ3Urwzaqcd8qw3/Wm1wEnREh1oXZF88AfIy+l/WPflNZpwIX6tVA8Jyd5RUutRED8dVCTsik26DNhpNiTQAOHFy8wX18=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-24T00:09:24Z"
    mac: ENC[AES256_GCM,data:lnqkUQoy4/mN0lA00rBn94dHjhQ6NR+O62rJoiPZ2ri8rIhvabSEbFZkmP8OfKFdA08TaFW9+5U+fmjEpCh/YCb5yhrGg4D1NSkNa+ia7JaqB3aKLbrO4g1j+c+v06aY5SnT17w//mvelzjFNCGBq3v3TGfRGsfTpeeiUIH/wGg=,iv:Dm7dmYphK9QNdldJqcLCTQziH4xxSconJ6AfiQmsgYA=,tag:2od55h4fBDYC7XFg/QKwTA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
