jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:gf1RCKzuBHyhY+ZqN2bnV8rScWQ/gImTJIMDvYSx0ecV6paSTmtXl1A0FWs6BHJKYl4=,iv:jRU1joICxTkwOkb9lQ0mneArse5cX+BJE7VhGYOicwU=,tag:G5zueStrqIQyxDhdmeP3Yg==,type:str]
                client_secret: ENC[AES256_GCM,data:+iy2eMqZ9ERXglxsd+WbqWDFdzfOhnwI+zmEGlPRD8KzbBYO+88r0jTy/wlFYBoBylMW2Nk0XFav6HwmxRHEFeYJM06+lmuaKikqcV6XqlnqyPq6Flc=,iv:xEKdEpcI78e2vooK5Ti25b0/EPhRq6dLacfusp4ygEo=,tag:eM6UgR96vTeBBHGdF24vOQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:hPfMHMhE90wzBVQyeDrj+RGKzgLkB8nABlgurviY5fNTgndMMb2uXpaDyWZdMxQYySwlyeeAWzRhLDOqyXf8qw==,iv:JHhE2JDaVep/NlJNB6gv5uPsPrHrTd6wJXC1kCAjhTw=,tag:1T60GLeqIIamfj90xxccaw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:31Z"
          enc: CiQA471gaurpOwRttzjKXCueMdfUsXRpZiMLJaBCKlrkfy8ml0cSSQAtv98x6kKKJ5eqVaOKj+rMl6j5fjnB60Y6uqesOwLtrvKILhh9/lyFLUqncacW+6MCd8NtXVuerm4KkrxPOBLz9bzfnQGzPWo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:32Z"
    mac: ENC[AES256_GCM,data:f8HuUcFZQ3dG5sAkiV99rObo5vu5idpkTFRqwAVZjBo2bqszEn5WNlACG7BKsUri96nZ9xqgt3THZvv8YVKpZF7KZdC5T9g4dAqlfc66Ud++zDpiBdBlmX9zt56LYPEwBtHLXTSm6+75qI3hUmkHgy2kldzaeA8FokKXpg23Ods=,iv:ShGXl6WeBD10/H4rIrrDlf8aGWoyKb2w61ItcMmrLMc=,tag:sHNyJQ9dZwFHY60Gc01Zhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
