jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:GiTraW4zD6rlO/qFH1Rz4CqpBYwZ/+4c7vt0RPF/M3jhPQd9APEa7xzKoGmiIDj2niJh,iv:0jL9tMGpeYvWEiTp4EzLLGCBQXmuGn7vMPfZi1pQ5PM=,tag:2ZUg45eBUb1DAQYFK5gWUw==,type:str]
                client_secret: ENC[AES256_GCM,data:wdTF0c3m+J4+lD+VN0ozx4edAnwUOTI/LTxUjhA2B7+fiu2SNKN+M2i0tjFd0yDeO6dyFCK+F989r+1cbZqMIfXDCinLaEoi8OFouCJ8IqiIxceANQA=,iv:ZRsEUaoNJUbfN2cUD3nepryAdDHbUhPeroXTXb91Xfo=,tag:UMggzw0SflUaOpneyb5sAA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-24T00:09:24Z"
          enc: CiQA471gam3uxfwBoZaKcXsJQk8HZDIZaRs8zVCA00NKTsjTedESSQA0woZQUuc4B4CNU1QqsHickAiOG9F/1oUkXHLOWRF+xWR8IQ+4ROBvGMIZRh8Kx3Ijz1JIC2aAxuYhaXGs2su6jlWPWVsOfOk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-24T00:09:25Z"
    mac: ENC[AES256_GCM,data:ecKx3TnGhnGXvqvWCohDdyiGrSOCSXKhGPGb3ltt4y6B1PcMEch/LlP61Iv9c+NcN1V4KquWyZ9IrJfh+zUyoWHU1bWih/vXzjf0aypBTFo54Hd9n2jOIS2EdU754oCEBnafOCEksgMgPakapDgvtCdi5BgFYbAxkBOGgWW77DA=,iv:WsCHeiGyPpWWf/StmyBz1sgVb/xGgvmENDT3QSsLuy8=,tag:0YaZDvanekLMCs6nMaOyIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
