jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:2JM2cjDYzVhSMhZ7vutRM+gg66/ggsui2w5mIhIidyNHtAqZcyywPRAf7MTO02zevgMV,iv:qcTQrdF84S480NBqS6OvzsrcGt7nKvj48aOWB3XkUE0=,tag:48RL1jcq7LkqEjl/UJPPzQ==,type:str]
                client_secret: ENC[AES256_GCM,data:s/rpp75FeefmO+zzBPZ32LpT5R+aX3NIdIYNCjiqacT0k9sLKBz1jl8qEpEOpKtgg1OjFOClUiAQa8h4jJuXTjuTHBAh2wDrkAGmiCJmsfOAiQoe5dw=,iv:ZT3BEp9vLmuS2A6lV4vqkVmweBHpd0ZprmWQGare4HE=,tag:hA9+eO+0lCxuXNXoVYdKnw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:HeroRQI6iYUNCDnenM3qu5hSsMZI4jN1ZjqMGKL8GoC4KwpkKjTVCNAZpFRLI5sa61TOOyRGORkzcKPtd439Rw==,iv:eKSXFj3AIwpJubKhFKvM8tNzBx9lpSmcq9DEoc0h8HA=,tag:2Sn1G5ROUJElanyTTA8PRQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:33Z"
          enc: CiQA471gasHThZzPgnoj3gIO68h5PKsm3tIodng+clIq/2XS2gsSSQAtv98x58azaquBI9ryynrgzNT5BxwNIuCfS6oM07ff/s/cm3MK2JUFb3cna0zMVwXOITy3huBH6Ir4DAEnNdxxAg6HawHHRPw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:34Z"
    mac: ENC[AES256_GCM,data:qPQ4afHMbmYLfmN4Hg3o9rHX2Ms3Je71EqJbA/m+0uT4f+zXgzF7lSqsI+ZT5hK0NjDwej+S9rzwLUh0BjgNoX0erOq2WmzBUhQpf7fbssgHWd2BZG2YN/NCAWxolIz/tT/JcJX0Gp9cVV1raol9oJPyva7+QI6oErAS/Rfx7N8=,iv:VFLz2pjvCXyqD6Vpzz7+Eyi5i7NByfnDK3auJ8KXYjw=,tag:eDXXTW/kENR7glfWEuTm6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
