jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:j7SMfY2HYY79Yvmj/4pfiR1uc0LTeTMeva0lFuOi+wrAN6wc9KjxK/ELZHxoKF+4PkgM,iv:QPJHJ0OWM3GfM3cHXiC5e7tlddvrD1Z8C5Ulqus4bSw=,tag:W9fBvANaJ76L6OvRhJiaVA==,type:str]
                client_secret: ENC[AES256_GCM,data:MaU25YSFO6nWNGlqogrRRI5nrO2+Io+5X8AhYjTB0EbRXsj1ehOgQOwFpV7P/hKQr8Exh1q4qseKi1kT0KSTMWvjGO3PLH5/CMuPypOSMDxGloKcmTM=,iv:N1rnZ8lIamNWJ/q5cG2z+dCFnGx/Wt1MrAIvNvgK5Ys=,tag:wunbWff4eFF1c2frNoAXiw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:ZDdAYoTuJuWqPzMOqlCdnXBsSiH6qkeUM8f1jJ5NHLL40Pz8BocIWYAzid/OLw6RMHFusbwMpGwRodu7unRNQQ==,iv:fw4o+7sITTwfYEAt4RluplUY78KkLjOIo41Pvkjpy4k=,tag:KqYTZpuI/oi/DvaocUPzeQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:45Z"
          enc: CiQA471gajg/Is2P0rhzvmt/d1d9GXfC9snddjgzyJMApr00BNYSSQAtv98x6sHPz5lTXqg1MkgZjQ+os9koZqLGoMf5ryQyY6OwqBT+Ule2EuuBw0pd87jrzdmf/lRA2G+vJ+hjq/WoK02pqYp8QQ0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:45Z"
    mac: ENC[AES256_GCM,data:GdQWze6TfveVzidF3t1KvXSNSQSS20Fx5R2oxiBGaGHp4V5ZHDKNY271Bhjdh0r9PGoqWraxIGkc3VzHKDvS1tNi7fvGe3saOrVmt/Ulh6rA0jCws+HbJENOR2FkU7jULnmEMBXPEvc5+GyuZoynTUtUHTWtnAEwetj9XDSIbHc=,iv:lsObBHgXpmBOr0OImgx4+b4wO8JjzowYRrML5G5dcm4=,tag:K79JBh86/ErVVlbEfDLH+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
