jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:qYAQbstpXbD/K3d9+MlPoj6T79kXRjoxH4uhqEwLdO9YgUdgglZRYHSVwI8GwEJNT79C,iv:pUAQahw2P0v3X+YLhk5doDxZ5djvNEnJIVsB+Vi+iJc=,tag:6ehNIOAbhMUZ6KDDXxxTOg==,type:str]
                client_secret: ENC[AES256_GCM,data:gN72JUjLFVOdWVG5FVVXXBiRoeqGrpccjLT8/Ed27H4Mo301e2CSwgNrYnZBb3jrHWmbV0IDdga+Ypj5KZKS4UcHS8QY8daxnnnWdPed3LDZlTvwLa0=,iv:MWKrw9a/pGDgpmg2JQnisHl13MmOjFGr1s26loHoBqM=,tag:RgYQNJ+ic5R4wfGuT5TOnw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-10-09T22:28:15Z"
          enc: CiQA471gat3+qJ6w3pZ7NIbHAWx8RMkeslrUdZ4YBzt0tWC9yw0SSQAC0RWos/seWuHt1alFSwefE4dlEoQ0YSm3yXkiowjchf4JEaK5P+i3+ej/S4anNgoPad6HxLbqMO30aWFCdQVV+K22tmYsClA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-09T22:28:16Z"
    mac: ENC[AES256_GCM,data:YBEOLFRbw2+8K9nbhJYnYyGkpOimPBMIfreHmkofZ5iTP5EN7D459ghpOBDTJ8R1NSll54eQTArsSluCz/URwYAKg7ER56ejS6oinPU2yqPvIl4z84n+JUVTBMIKRIE68FS8seSV/jIY26tqUKfZX8Av7Tl9DJ40MQ88pmmtjGo=,iv:HieVGBm0DX54Ud+0AeGuGNg0h4VJty/Lj8MnTdKg1YU=,tag:/NOO/2CUqVPYd2S2VX3H7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
