jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:R4Ekq0euSbzcJj9prXpKT2qP7Hqb0S8JX8I7TVfbzJx4mETRztx6oDh+C50tA5VaprmV,iv:P0HRbFbOIzxc+HgW/RpRCwDRnE+Hbv40qs04ZctuGbc=,tag:JGtITiQ5pG8c6/fX7/Efog==,type:str]
                client_secret: ENC[AES256_GCM,data:OWKHeK3Pyi3b1z5z1KQFv57ZcHwW/M+USLrz+aa99NsbsBTSfNy0THn/nCzUonVa3/lGpU2nSbwxg6k6JsgtcXm0uzO8RU6RMKcMm1YUV2teR/gpdpI=,iv:6goMVSVMWYf96B6XbvLk3CNPHR/9d73cWPIP6TRr6P4=,tag:XnTegjaB7KrwVr6KB1xGVg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-10-09T22:28:16Z"
          enc: CiQA471gaovJ7XHvp4M0va6RSavKEC1un4ejP/6cR3rXZCr2pXQSSQAC0RWolpJkw7kJRo1S7t/oDbAccuwIlLEOtarbSb+l7VlE4boS93rnSrDxd9Qz5jQ1RYtbXC/3fElqfckZEToFzSlw4f4nF24=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-09T22:28:16Z"
    mac: ENC[AES256_GCM,data:OzfGq/jBECOk0iVqDMYr2c+Wvzl3lvvq9t4vXtFG2EWPaUj/9lKE6OJJBJg715oo7zU/mVL29y2ph2AtGSvmSOJX18Oki7sGAZ1wAircaJs8TITKRw6kvIjCRUWr/1miXaSZ/IcMjyKDioEnwlfKBE/qEJFC8I5PKAmcvJWOpbg=,iv:dz/aBR8DFofMmw/U694mvefsUNx9N5J0u+G+habZuWA=,tag:JhJFhBxIrWw5hioYABAW8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
