jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:0qPtBc0AiYbR/4lAFF5VuPiozaifYPQLEd93gzE6/StmGxctONbOGpwLhoZpP1GxcOd1,iv:f3a3q29a8iiNnFMJ2x785o1kD7KaE9XVW4xna9UiPK8=,tag:2YfVioKbuOB0BEHpr1kERg==,type:str]
                client_secret: ENC[AES256_GCM,data:p6ELxy/BSeAVVmvSXfcivJE9rOGjI9r87WMhl3H0ARRXYw53qs/7F/SoCgsasJZ/y4ww12DEI07z7aw4JDkn6gIVlXr/MvqIjZfZ0h654G8s+jnq8dU=,iv:VDECirYgLU8BdEwS8TlvdqvbdOwV4asaUmzVkM3aRdQ=,tag:I6SK4cj/ZtqyJhm03EXcWQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:wzA3XnfFuea8LANYnAF9cOll0/JdXIVvB70wq4ASCoK0U4Cvpdjg9nuzY+gZKDeWXZHV92I2T+0xUumtzetBbQ==,iv:SSgJOaWXDRgFWeLSqhiwKUGkE8odNxjuDnXXrJmaaoI=,tag:K5haKNc8nQhIZxXXO6p9fg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:47Z"
          enc: CiQA471gavBCDZ/D9sEyoArp1/TULx13TfrKJa4ILy71hRyTt5cSSQAtv98xdVig5Pgvj7fmAaUl3Xmi8YoYbpZF+2gNS/NR52iolTH/xwIbVTrYcI+Y7Wv141BXrI4xSPlkUmjTzgptv4KuCUmpQK8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:47Z"
    mac: ENC[AES256_GCM,data:7TBbPdS1VskRMcXBF7WlIalJze9LzGGAQHjcCslJtm91PqixnYQ8uK1sL+x9DKQNdeQI5st+K6nUOFBUa4l4jIUG/kOVcAgJXtwtvS6EXA+GnJXC8+Yoc9+1EvAGZe8vZVkmBVIFx56R+yvPFqTYXeGOQvfImzvwYDuviiqKwKw=,iv:WDAK0uvrgONDq0dAVFoCOxws/GeCVUu9ovdFY+m11sw=,tag:6+WulB6w4EC91demfK62EA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
