nfsPVC:
  nfs:
    shareName: csueb/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, East Bay
          logo_url: https://www.csueastbay.edu/_global/images/footer/new-csueb-logo/vp2-logo.png
          url: https://www.csueastbay.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csueb-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csueb-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - mary.combs@csueastbay.edu
          - mikahl.banwarthkuhn@csueastbay.edu
