nfsPVC:
  nfs:
    shareName: csueb/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csueb-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csueb-staging.jupyter.cal-icor.org
  hub:
    config:
      CILogonOAuthenticator:
        oauth_callback_url: https://csueb-staging.jupyter.cal-icor.org/hub/oauth_callback
