jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:spWqPHyfDnwDSNP+3mTIcvM+QeBsclX6W1lVhr7wtTXh4K9w8fwoc9EFr+IVr7eUQnGv,iv:R5dYk3elkdh/BqDf331xWsYqg/D7GCDywS9CJdEInp0=,tag:GH6LNPGHdqUYFdVQeICQWQ==,type:str]
                client_secret: ENC[AES256_GCM,data:VXvV9W+fKllxd1ROZ2ifEP20tqCMuFcXg4U3RG7XI8iEm/n/8Iv47j7MjDwzs81Po6iEYZ+WtmmcqC/8nE3pYL/3s1YsMGdqhRMShaDxB2trml4gCMU=,iv:7xNM4g+DueWdo6SK365mo77wZBFoa6lQlxIn2ExYBUE=,tag:wpM2/yVlnCOsvAAAtykRWw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:ukRFgi2UFgl94Mt8XqgVxUfaGFDlNdsFmiFR8zeavew2bdDq3ZziIsLBBuOWYHqT5dsryZIfTweyT9rGNxSq7A==,iv:dHFdoW8N5fgfvimy+6uG1nKzN7h2r5C2VvWkoZfS99E=,tag:ovhw8cQ7Ei7UaJakBQjVVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:37Z"
          enc: CiQA471gagR9lgSY27ztuEmH9tfu7I3327pxFImNDgUr69A0EzcSSQAtv98xz8JDn4efgBjrCdmDPQJfuXc5YfHhkWb9ZeuikjXSBOlwEHPh9be46jUjy8Ie2efWpCDcsoRPvlEEgUK6mziZHy6G48Q=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:38Z"
    mac: ENC[AES256_GCM,data:saP6O1Sv4J4D3M93HBQudCnLDorVBM6uvHX9yaJPLdBD2ZRSygHrVb0QauUQhkKtVydUNLq/lZqWZCx5x7GnbnxWueTjb28KUpSZAgiP8FJWjllPPFxV29jRpJai/+fKB4WeaKjckRL4lyCNkMbcdU5G/rsAEwEArzuCK9x5UuI=,iv:vwwTBcRCG5Pk4fNfYcorRmqVa2nQ9h74jdgFobfwSvc=,tag:hJKNrhsxS6R5rb5/E9/vig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
