jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:LlyVk/Oq4RtSqHIW8QS17ipmnwMWluQLNuMlmBOVxR89xQGa9C+bTqbvRQkhRPEOXbSE,iv:FldkW/M71IG85R9VHtZIbrrQ9Lsn2Ysas7gYRd9U88s=,tag:Pw2SFRDnpoaD/PP8EXXinw==,type:str]
                client_secret: ENC[AES256_GCM,data:1RdcQx4A/P+eD4FdMszDyXUVtxv0FuGrQKst1PMbRmSrPz8FatjCplE3B+Fs0NPPCeZxOs6/BZZON5vwoXfNfWwdn9GqFyC41vcHKO05OdfwSx/TvGs=,iv:AygGsnbMUMrZeytCvjJdKryIkXzCCegMyHKh26oiRig=,tag:kOsQ+OM9YkZ6EETRKmmVRQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-28T00:10:45Z"
          enc: CiQA471gapa5cpQjfDtP+/YQScvc9Mvl1sX1MlyhDU2J8rfSmOsSSQA0woZQRlQMrzdRwkQo/eo9qpAQ1hc2M2jmnukEcZoiCNynESTY0UPi0Xuv9Ffw1jc4asTkmzoCWnQPAirvKs6W6pXGvkSZE0E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-28T00:10:45Z"
    mac: ENC[AES256_GCM,data:yAtOToJxUdMKHOolB18s4PMxW5dT7PnwQXJYk1/QnX4fJbkoD6NLDcrmOHctBM3qjRD8kzi/sIFE3UH1ZJeRGFAW9ON6ZZIBlcWT86l3BeDPHwrBrQQr6XykoJkfEAsKa7HVyruXmo/E3WD/Y8ivErtz9Taipd4xgC6q7BM7JGI=,iv:SvxW11r8CD51GKgB7/q+1NDwb3sr9AwhqUOeYK4meHY=,tag:5wEeBDiu+uYHQ2QtVUHklg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
