jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:IG9L8/sBePjyNt1BvDc/YuvIopm/EbGOp9LjFBeeCnmg9gLk+LV/pfcfoIaYKFj7WbWG,iv:Lss+JrLinvgmWb/06tV8ZsUNQ/5LU4AQ5CD5sWzsQPU=,tag:X+pEbPMoyj0WBVZr3EjvJw==,type:str]
                client_secret: ENC[AES256_GCM,data:Zd+fkYy1w4jVUdJaomKp9cV+MXOo683xaZ/tO3grNyK7QNabafZ8ip6d5jqW0CbSK/xUDZ59QZUIAlx9QLvX8yHVM2fk/dm8GaLNc1hkQ41xYEIRkO4=,iv:4flvvZNrsgzSTA6MnXdXs08V4/w9iRC5ZTre99/uP80=,tag:YmyllSrDziKO6sPMzFjhBw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:a/0JUYV8O18ZYO9rTBg1Qky6e3jisQhkP4ckjllOcWk3DqcrDuOYVJEDlCfFFlwvkB9SG1YQdvPF6c4MSbxfYg==,iv:DU0EGfMw1z9ZmdeJGx8kKwmHQYXCFDyGX4aNyMGPPXk=,tag:ECQYzhkbG19PRK7EDEgCBw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:39Z"
          enc: CiQA471gaj9aWCvwtpYBvtqxtfuJ7Xq8jgeLKADX4c8yov2ZfzESSQAtv98xfaNhVVOn1OGU1SiWKDzPnOtwp+bkQGrmWO3MolxIeTDx1HWIExBVttj4+pqRUypXkQhocqvs9IrnQd32B9LFf1G+Htg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:40Z"
    mac: ENC[AES256_GCM,data:iA/iIivjfAjL8VYcdPKrpgnllWUJX00vReJar4jFzEkoTBFV9WXl9DlnK1LVACW/Kz2WpiZfYMLqGr2BPVDjUoaJIcg1YLOAi1fZjEP+ZBZ9HE6q+A2Ixa8yckUUsfHSAwtNtTGL1nGNKqeLAoeu08Qv9gB2CnZ9JVWvnK3KvEE=,iv:SNQ0uT8zSbKbedUQSUYkaPLSnznj43d8aqkApcM8O4s=,tag:V69aP5rlhi68za7u8haGIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
