jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:B7Fvu112eCy91jFPhABp9QH/oAcMUfPrMpJcFedhu5pVWCaUNqB/y4w3w1iLfjD8c3ho,iv:5Db/9xqT2iDiHFbEVIcpQ7KoJkSVBWTj24ASzQcGDtE=,tag:B5v6Xiigm9900wj3mFufNA==,type:str]
                client_secret: ENC[AES256_GCM,data:m7ijknwiGFKPnr0WTxymbr2+pcmoaHEVFBdRbr6trMjSH3PPRD+UNfyck/0Nq6QbMTYE1RfIMX8QH+4nHGAGlY1obnVxBYDcBnVT45oQ/qzq5/GlRiA=,iv:a2torvwaqE70t5g93AcuJKtJDXBXowZwW5Wy/fbdSa4=,tag:VE+4cmIbiXbDNdVXfChAsQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-28T00:10:45Z"
          enc: CiQA471gaj9fbGs3zN/bZnc+1ilFFSbRwVs3UOU0vlhvQO3vao4SSQA0woZQd+AX4u6wgqIcar2gCmFOySvl9f70gCl4mz4LwPSr8D6vrqf3bwpmwjQoJ+5MN2aBU2I9EkQjChAiLgswA8eBEXYdRq0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-28T00:10:45Z"
    mac: ENC[AES256_GCM,data:BukliTRvl++B+C9FrFDDVBxtKnc3ZPxfwSWs2n52wPyuQ3ZhG9zw8ipJx19mAxfT8sxGbc0sk9iMZyzkLY4yjEZCtZt8fO6Bfa5IDs5UvXM0N4GUaSTgftXikgkCItoKRncEs/GcdjJ4I2wn+oe1RDLXJjcsREnFdMEx/PyP6Uo=,iv:1RR/v6CzHofSZ9OKd85MjB8zfkM1YcWVPj5On0jtfk0=,tag:CQpTGbWvoE5RLaa2/IB/kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
