jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:1vfZ37EE+/pOZdhtgdtXLrB5/E5RFQQhyO8FTA9uzM9bVKODvZh4UhjVDGtyUfwrI38f,iv:jstJ1wcZFJnVrGrhdxzaXCK30Yx0G0sbA36E/a4e1Ts=,tag:Wr9U2SkgXn5XMVbvk4+Iag==,type:str]
                client_secret: ENC[AES256_GCM,data:N/RUO6tIedE5SNxiKduMAuLSROlYLybPxvtt37/7JE+E+VAKwJTjRXVY2Evd83R9ukV02bEW0yU0Hu9CJVsWhfxrb/gSCaRBLKziMbjoJ0OqKgz0iIY=,iv:ye/OYAsJ6mz6DE9ACT3Df6b73DrLtPqnEhNpDU5UK6o=,tag:6ntKfgAwe0UQNxLJ9WKPKA==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:5inSfiNvS96v2pMVM6rKnzondMpFSj3Y+GLRPQEKfUONO5Xt+kFtkMQCa9neyZiXmy5yPC7y6JjzdnsiJg36Bw==,iv:lMf59qLMuQ6fj8qx4PHkiblXe3e7RLIQOuekeetnQkE=,tag:J/lzh6XOHZzFA+FVnk5jLw==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-10-09T20:58:55Z"
          enc: CiQA471gas3zM8hP8s4fvkL0kW7ouhW2mDk9BIXfQLhuivrxLSwSSQDKo3g/Amv1EG1xT0PDE7LtiMlF++p7e1pn+y2/L90BdDs2RWb/JE8L+Ua/Q8+xYQ0AvX0siVuEZxdErP+TYnMeRMnE0KivYx8=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-10-09T20:58:55Z"
    mac: ENC[AES256_GCM,data:p5ZJdL0K2HjzTKtcW7xWgbtHVczi5VssNL/tNdPtHcsite0zpWDFbcAW2UFadrF2pDhhmMUWNeJRQQaC+Bw9cieFggsCAyX65J+NdrAJdEf1plypUVDExwiQkP27MuHKykOYmsA4r8nfA8jN6HislSs+1qYVMSNJZwu6yerz4mA=,iv:fgjXm6TB4/J4Ed1P1xthNd9f94u6dlYQcHYLOzo5FVA=,tag:U31p3gdogsrqVjbWFBdNqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
