jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:eLH3enEMOAz/Hpvp07TyKCuqZ+786aVR+E581NM5BPVozxlXagTT3dtP2rLNP3ctW00N,iv:X/i9R/1CRr68/KhOXHJvj6hdh7oGxyoQtnaQjcJjots=,tag:3RB7S/SBT50j/ZzgrDJK1g==,type:str]
                client_secret: ENC[AES256_GCM,data:Z/yoG5wuiiCHVSiqWfP63cMVBqmIf3oJA0URhlFkKgTAY1Otk1wJKqmaW4KXVsVyiTSPbqfqz3fRapVYneKpIaQF+yAxeBduOy+WdaDogsy5p1C4Lrs=,iv:W+5CHH743tdH71IbCq9TSmienMPqZQ98Ha+DH8/2XKE=,tag:smPUK8E6YG95RlBkFGbfEg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:qZPoJf5/D9rwVyNp8p1KeN1XsbJu7o9XzdwTryByLkrrG/uZy4Yhg+0u0MQuQrqA4E+8vyTDSnAMxfIhJtH+Tg==,iv:PJiU0uO4ni1G6ORTzL9P51XAD3Oz0zXlvSc5vKOUOws=,tag:eXeXk1y25AFJ5pw45MMNqg==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-10-09T19:42:51Z"
          enc: CiQA471gap1UchfPyk1HqO6x3Rr9hSeaFYnhHMuoHma5IfW3FjUSSQDKo3g/2tnLj5FwFsFgeq+xBIlCE00++uqSY6Z1LSssyOQpM38mt5HcU5VadDq0o5aLxyH1wGjIdfTDbSmophWb9y93zrug9Lw=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-10-09T19:42:52Z"
    mac: ENC[AES256_GCM,data:nnpC3DDp3yxqjiGrpNWRDxZpskSv1ssqwzIptX+VowVtrUb8t8KSXhDnreWH2ijVpOFIH4eBynBUT/UspQDdypMDvEJNy4v9GASXSE4e9z0EcC90FBc6EmnL0cAyesz2d8kVqstF5pitn5Dp4qMZQnfCKqNI+EIy1MQLiatzhDk=,iv:DKiuyU6okC2eRYT9nUcJWzTX6N0tAhhDA60RV7v8w24=,tag:o9DELnl9A9GGkRUIGP1t8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
