jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:C/rLgVw1tW8knsnCJk5hn58OmZJBJ1gXTw==,iv:yq/ETJXjVS2sCZHGXB1YwVb1kjtt0cQ3acQNNlfC9lE=,tag:xTg55JBm0KAYQ5cq+3aP6w==,type:str]
                #ENC[AES256_GCM,data:a0Tkwp/dFdYZ2sLfN66A,iv:SnORj4D+BvjuQ3HoirjynoxEsFaCMhfPNpY6l9KfQUo=,tag:cylCsARe356oB2qkKXoGDQ==,type:comment]
                #ENC[AES256_GCM,data:vmJVm3vvDW3tsmZcQAVJvlPOnMtgAciMW0kRralLQ4IEtdTB2pdnulXPLgafTaYZKwbJS0UM2Dt5alCQkz2QvCpUs63CQvBv,iv:5P5QCeA7pCdQnO2cUbNOSnJnDHJl0AgZzlsHqU4kWE0=,tag:tNzPxnqoRXSCL+O6QlknJg==,type:comment]
                #ENC[AES256_GCM,data:jh1v7uiOYTLbqDV6J5bxqp3OI89n4RNuIBHRBJ48iA==,iv:6qwwmJtfAxRVfnBba9/CpEWhIyFI++4b+9FO0uB5GV0=,tag:xGS43PpeeUj3oM1/pnYNnQ==,type:comment]
                #ENC[AES256_GCM,data:5o15JEnMLfk25dgKsJQbMlAPMq6jV+x2Ft8P6lUbObVIYLZ0y41RRYIAHw81E02l6vtzVJLmJA==,iv:mzUtuKq3f4rs3333yLQVcb/dIYNgmr8nMUOTb4ijF4Q=,tag:XyutZTDelr1XmF2WrJ0X3w==,type:comment]
                #ENC[AES256_GCM,data:UnABv+gMRiIQT6E=,iv:V1pPVZMBJU6z4p6AfhySc4Q2ZSro3EGm1e+gG8duGL0=,tag:OER1rmB7UwwH+qji9HJPlw==,type:comment]
                #ENC[AES256_GCM,data:MCg9QrHM6XLYVKhDVHEYcKHlIB436YqLX//u,iv:iUT2ZlHgbQOskljmsB/PKZFFInzoW6RMF/erj3Ezm0o=,tag:Heo1gZffBNDaxF9iKb5tig==,type:comment]
sops:
#ENC[AES256_GCM,data:kRFWmsPgklxMHAo3mT2QOlc=,iv:Mh/QQlxyVvOjKKFmDjCfk2OmyiCr3LeEnucKziiK+UI=,tag:l5fnCVDZ04YaI+Zha2w2WQ==,type:comment]
#ENC[AES256_GCM,data:6fG6pHJSVsxN9GX6qK9MFtZZw1Xb3F1jY4wW2CxX5OByF+AMly60StAIaT341ae4Ts2GzNV3DJVo0TEUzfeD15jtvWGTrtZRTueWB7Y6p6a6hGP6+sVWT9StfPHHRmL9PjyaeQ==,iv:uKlJ8BJrYykodL4pt6CfL3tI7PYGatpFeMuY99jLOO0=,tag:482SWaKgzHUmG9IER/8PRw==,type:comment]
#ENC[AES256_GCM,data:UeZxtt1NHKlEscTWgHN8AjREKU+XsqItOeZ+Cvylnhpz3QbLsoJmlAC2UVYRL6kArmubNjHemIAly4Udpz2g2Fw=,iv:1llwCRSHYnGZutQepgAsGLCGPcMbO3z6VOZikTAGfd4=,tag:LPnyoKO4PFh4hpLAjKA18Q==,type:comment]
#ENC[AES256_GCM,data:Ko2EqtyebtKzL5BDEexgcnsZhYGmsLJWhArd,iv:7jtzw2K5oVr+FcQGgLU+iS/EvFxeEaw+3VtinQEmduQ=,tag:fPw432ymEpf4pLxDJz/eBA==,type:comment]
#ENC[AES256_GCM,data:va1zoEEwiybC8iNMdvgnovdSGEO4vDUl,iv:OqZyxeIQ9KGgBOIduvvdbur3OGOdm5OmxhL8qn3Yd/o=,tag:ymuHtpvx+ZYCIeD+e7v9+Q==,type:comment]
#ENC[AES256_GCM,data:ps60kkjNgW3L7hr1L4PDFaPPYpt2Kgq/Tk20zA==,iv:D+o7ZJGCi3mSPewDO4fZBVitZtCWDPi2HaIYCPWmjsc=,tag:igwb+lPkLsbYpBWJ5V6Dyw==,type:comment]
#ENC[AES256_GCM,data:7LPiqCOQuO5O01YgzwWp,iv:B47bx0ULZxDcbgiwscsaON8jWuD1hDZ7N0F/i5R3p2A=,tag:DEtPDnEnGREOHBAs3IMXWw==,type:comment]
#ENC[AES256_GCM,data:Sz2T6L+7943LyRjI81/rU4Uz,iv:u50Jbf+DRVayCII0H/Duov691URlhjwmmDiswwlKrHM=,tag:rKE3Tyq8rdOnJdHfhYdJSQ==,type:comment]
#ENC[AES256_GCM,data:Bz5El+BEQQg/Tjc7,iv:cb0DumbK6wia0c3PpjhIPbNwbNRuqd1H09m90Xt3jxg=,tag:sA0K5IcSp9fle8A95eO4jQ==,type:comment]
#ENC[AES256_GCM,data:kDQ5ER1W7P8f/7k+pg==,iv:LtdOlL0e/q2VTfT5WXfsBofI+ggHtNdHomXNjeHrflE=,tag:FzztWOWGZZ6L1JqBk0gXVA==,type:comment]
#ENC[AES256_GCM,data:LGTxkB5gAt43qDlUC33ilcdTaJuxNvCsRYfNbc/1vNr+Q0EbBN59hydCcu89ErjrZPnfLLNNE3Wgg9N3gPCE7ksT5XxF1Sp9+nBKgp9k/C0=,iv:6mBZ9DbZforl53ARrtT8U8O7U5dmKvbuJ27XHt4GFRA=,tag:g6W0y+96ZaleZwFGkGBNTA==,type:comment]
#ENC[AES256_GCM,data:yfQ9YmvzbrUHr7tGUaLmhiZnCxjmb/iSPX8eyCzV+uRgREbSn5/odDXFwV+/k0y9N8HWLxcjaIPNxD10Vt6D+vARl70Mkmlc+fcwTsjPMzbgfN3wdQIXO1O2O0r6KLTw544B+RNBq4Fj4VLLZwYEv6pmjoz7ePScps0/pB3SqHbwBaBq00PW3NfJc2Q=,iv:8QVoGZE/a7ThOwig73Cby8KbPwdxCATR+P4qOG7SFs0=,tag:RH4n7fvFFnXTbN2xb+tbOQ==,type:comment]
#ENC[AES256_GCM,data:YQmPM47T3ldgpRbgGqL3zAO7mmk9gjI=,iv:iNX07WPekxczi8NuMY773tUVkM7eKqPazziCcjPLn+s=,tag:j3lqqdJN3dug0A1Pl4ne8Q==,type:comment]
#ENC[AES256_GCM,data:q4QCJHtfpOyDJNCc/Hzh5Xipj+R6naTx,iv:Z2Sc0o1YLIOBE5d9lum1GLayIvYDX8DkaAPjZzDp2iY=,tag:MiRQ79KNd2EDlZ+dcpTjfg==,type:comment]
#ENC[AES256_GCM,data:abQNao0Yn0v3Y75/RlJ0P07jQyBbgMPYkpuAxNgc6slzvQlFUEXtPg==,iv:9oscAw8XoGspszNORRiF8wfP8lOnpmvqOjPX/ghR6f0=,tag:hn+I9i4+r4RRRzQVr9eDRw==,type:comment]
#ENC[AES256_GCM,data:fe4qr/1NS+GeYx+/bVnkwTbBOliDnDi8iZ4VFY+a0nmcju+lyA==,iv:4yWDt7GCU7Yvy6d++dbaZ9ygbTzPjdScKXPFl01NRiQ=,tag:iqISkz8ueYO5x0b5tH1M0Q==,type:comment]
#ENC[AES256_GCM,data:vwvkDKmPEH/ehVfPfqXr89wVXmg=,iv:3Hqa5Wlp4No3t5XSDALyUSk/38jsdCwzdHIkKtIvU48=,tag:aKNxLQDLPMYVsiLvn9p3rA==,type:comment]
#ENC[AES256_GCM,data:zJCr3A8x3wyPNkyO2q45+m4VyeU1xHYxiH2BSD/i8hvZ,iv:FiFj0vx+du7K7n5TnMZn7gXafKHnzqhtaRL4becH3W8=,tag:/mg4PwPbTKiiYtXRcVySRQ==,type:comment]
#ENC[AES256_GCM,data:QWmDP9AU4GvV0DXq8cS0XLM0P1+Tj4ZgRGRbXT6IKg==,iv:F4VlxyROF0AUeMNhYk92+rj3Iknnud+oVXi9vSqn5+o=,tag:o8tRBCc+HtsHGaAr1u74jg==,type:comment]
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-25T21:11:27Z"
          enc: CiQA471gatgxy7psVk5RIU8HEoJbaZt+J9sAxzL0utPtM92lKqMSSQAjg8vZfzYNlnzVHfnagG5fzLsDGl8zyC+OO8hPgSXklGf1Hy7RLDo/hYTwXiai43Qeu3b0IoYxNTeauvtVAH7B6d2GFzjC7vI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-25T21:11:29Z"
    mac: ENC[AES256_GCM,data:AqVFq3mxhehukHuy3T6n1LnXnRLi8ol1wb3YbFXF+Oq76ETDykVRel64GOQBzrsmHt/ZbieXXbeX8y8V3KEN5KvMGOMiv75QcHd/mFSLYsJfXaEuYfAUFMlVE+2fMrO9UU34YQdSA+2Hx4sBZsb9s2tdV1CK47QmORYMc67pPAo=,iv:uKf4jKctz3JYTaYuXyHCKd/3N3ma84iXW2OSZt7wSS0=,tag:l4nwqoDy6u2z8x/FAPl3iw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
