jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:tCpHtRUVF/F1ix1QB7YL2h0o6it+Ty8Vjg==,iv:r1MCaEG7mgrQpzSbKk8l2Z+0bclzIQ/IDIvFoQvUj20=,tag:voGF2M5YXAP5X6GfvwlisA==,type:str]
                #ENC[AES256_GCM,data:7PIGmfPKKuW21v0LH3d4,iv:xf5uYxKZTtwJpaeWxWktdSQrM3XRUsIOx88yats3O8A=,tag:IZnEKIjCUDFFNcKC+OOE0A==,type:comment]
                #ENC[AES256_GCM,data:D4+FUF+ByI3gdYZTG7m087hU3QAAbW9BHce73/zgRV5mIXHi5lkPpSHAAoQEMG9Hz/oEmdJhh95/HPpikS4RPFPJm7kRiij1,iv:e6ysNQKzhZINRpw225p7q0bM6hiqpH4aZbcysL/H8sU=,tag:8S8UCyvnSx2VvcjvhrLLgQ==,type:comment]
                #ENC[AES256_GCM,data:p6r9w9YQzOvQDTSrwwzdYRR7337+QI1BEOrR+Muk4g==,iv:CUoSsCRh/KOz1rTp7lSGyNNuimNeI5Z+Wdh1xXJxOdQ=,tag:egXHxsjOjNroBh+nOwKEsA==,type:comment]
                #ENC[AES256_GCM,data:h4Z2Ps0n2QgNCeEZWXWc+uo6Ycqzfy/zfaNGq6N9v81vBjK0xeBsCrMLri9dHk446WSIr6vcIA==,iv:alYkuPqh/3epPbzhxfWH9T4M+rntbUtnhA0EVfvf7uU=,tag:2ZOuipO4ZYZPLFbW1l12SQ==,type:comment]
                #ENC[AES256_GCM,data:/6ihjbQKZ2HjWZI=,iv:mF8ScqSYjD+NFvoMQgm7M3gRWhvMeqNC4TlSAIdY/T8=,tag:Sk0qgqDM00GQd9tdgfuTww==,type:comment]
                #ENC[AES256_GCM,data:4uTCwQWzWeIL1bhavK2wfpgENjhVYqZ+3NCP,iv:aNrR4pVjfRdfJHyvewufEiE2EiAOnLTT77aG1qPi/1U=,tag:pd81VqTtAYE/XhJh2JWMHw==,type:comment]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:39:35Z"
          enc: CiQA471gah0e5VSLSVoPfpiQ02y12LNuA3PAR79CFfzSgxRlKU0SSQAjg8vZ4awqT/qYyFOeZ1m3kZyp4x8eoeTs/2antUTKqoKByZG7wfqzyT+P6EbUHpErAqhIhZA5ygeC1G46e7ZAC1Zmw9yBMdk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-11T22:39:38Z"
    mac: ENC[AES256_GCM,data:7x//b1KZuPtTxXvak4SP+KVniH1ndQ443zcZQRnKAVeBEWvuDUbaFMerru5Qzh35e7S523lkj3FD/KVVJKk6qu2iYU5At0BCBsYqxnbfhxm4ds+JrqgE3Ugz6sO439p3/QV4CFv2rQcXxRNh5mfi7pg2gg05ISwZM7j3h30/jrY=,iv:OXDDzimdNynCTW6nwUgKoIfzSqd6L4TNKg44hYotYbw=,tag:F/Hr8Lp7izu0KjyGvISldg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
