jupyterhub:
    #ENC[AES256_GCM,data:hLAWt3cxNDP/+DxtU9wd,iv:DY/WXQEmgVzA40Y0e9mibZczpnu70lSfiGMH4KweKZA=,tag:tOwwTKTyd49oY3WRg86C5A==,type:comment]
    #ENC[AES256_GCM,data:Me6G48qZT7hSYyIs4Mvc,iv:nI3nesp8edU8tVomjX6rq+bi/k1kL5imhd9T4QJjjq4=,tag:nSPNDR7+62zoAoB+bk5wRQ==,type:comment]
    #ENC[AES256_GCM,data:6mCMS1HvIDqrdFVAT/xFQxeqUdTrynBGMx9o67Qx5JIdCcBTG/I7el6I8bnm/PtxHzZmvFkDKBacHA==,iv:asTUHodanoFCL7TepGv8gnwL7VuosJPQQIGoQYopzPY=,tag:EYFyf+ShuQr/KrCqVqHurA==,type:comment]
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:C/rLgVw1tW8knsnCJk5hn58OmZJBJ1gXTw==,iv:yq/ETJXjVS2sCZHGXB1YwVb1kjtt0cQ3acQNNlfC9lE=,tag:xTg55JBm0KAYQ5cq+3aP6w==,type:str]
                #ENC[AES256_GCM,data:a0Tkwp/dFdYZ2sLfN66A,iv:SnORj4D+BvjuQ3HoirjynoxEsFaCMhfPNpY6l9KfQUo=,tag:cylCsARe356oB2qkKXoGDQ==,type:comment]
                #ENC[AES256_GCM,data:vmJVm3vvDW3tsmZcQAVJvlPOnMtgAciMW0kRralLQ4IEtdTB2pdnulXPLgafTaYZKwbJS0UM2Dt5alCQkz2QvCpUs63CQvBv,iv:5P5QCeA7pCdQnO2cUbNOSnJnDHJl0AgZzlsHqU4kWE0=,tag:tNzPxnqoRXSCL+O6QlknJg==,type:comment]
                #ENC[AES256_GCM,data:jh1v7uiOYTLbqDV6J5bxqp3OI89n4RNuIBHRBJ48iA==,iv:6qwwmJtfAxRVfnBba9/CpEWhIyFI++4b+9FO0uB5GV0=,tag:xGS43PpeeUj3oM1/pnYNnQ==,type:comment]
                #ENC[AES256_GCM,data:5o15JEnMLfk25dgKsJQbMlAPMq6jV+x2Ft8P6lUbObVIYLZ0y41RRYIAHw81E02l6vtzVJLmJA==,iv:mzUtuKq3f4rs3333yLQVcb/dIYNgmr8nMUOTb4ijF4Q=,tag:XyutZTDelr1XmF2WrJ0X3w==,type:comment]
                #ENC[AES256_GCM,data:UnABv+gMRiIQT6E=,iv:V1pPVZMBJU6z4p6AfhySc4Q2ZSro3EGm1e+gG8duGL0=,tag:OER1rmB7UwwH+qji9HJPlw==,type:comment]
                #ENC[AES256_GCM,data:MCg9QrHM6XLYVKhDVHEYcKHlIB436YqLX//u,iv:iUT2ZlHgbQOskljmsB/PKZFFInzoW6RMF/erj3Ezm0o=,tag:Heo1gZffBNDaxF9iKb5tig==,type:comment]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-25T21:11:27Z"
          enc: CiQA471gatgxy7psVk5RIU8HEoJbaZt+J9sAxzL0utPtM92lKqMSSQAjg8vZfzYNlnzVHfnagG5fzLsDGl8zyC+OO8hPgSXklGf1Hy7RLDo/hYTwXiai43Qeu3b0IoYxNTeauvtVAH7B6d2GFzjC7vI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T20:50:42Z"
    mac: ENC[AES256_GCM,data:gEaaAqne0dytug4OlQYnJVBc6j5hAyXOBmwSvt4BSkf5h3lU+h67JHG8vBSm9TGjM2NrDEIfAZla9Tp+crS2qd8P124YDuSHBYuWcLlBnQcGY+2ehjdrhrNDKd0Hg6O7/zjq5b7bdcFjQsJoksNI0G+1wKvMajT3NvxgD3FL7sg=,iv:l4Q/ExroSyK9p2mp1PGK/LFScSv5RoeyoecZZ0vtsNA=,tag:rOHNqljOUG/Of5lDrk8JkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
