jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:NRyY5HyglflmuIUqqmITrUJ4L+8CufqljQ==,iv:KsC1NvYDg+ZM7UuhALey74mzZocnGtDw+Us2jpjZDAY=,tag:0RKxBvrGg9xc2hMK2e2XSQ==,type:str]
                #ENC[AES256_GCM,data:QhaIfQ1Q/hwZL+639Ozm,iv:Zc7bCwoZ1Srv8cBe8TNJ6r3Gwvc5Qx45IrRKPE7YYVU=,tag:jYpWffGsfjYH4HBQIiPrIQ==,type:comment]
                #ENC[AES256_GCM,data:IUsLtx9TZkfQtZIWctb+MkEelgmcDwzhKdqlolGlz7ttUvYC8soyhbxC1JCsEtQotzLpzNMCJ2xodfucJr5ESJiosUk6u/pd,iv:2K1XMI7gVgl+tc/jLRYMEBINr+72i9romKPlN260XMc=,tag:PeRPKHhh0FkM4KXRYpg/BQ==,type:comment]
                #ENC[AES256_GCM,data:eWhU9PiXDKtirfgI2hJNgsajUuEeJd1erSN7fG/tIw==,iv:i8X8faaLJgXU9TgrEXMpYyLJEds4TUAhd7W7mBlO6F0=,tag:zDNjiJFJw75f5J8DQkubmQ==,type:comment]
                #ENC[AES256_GCM,data:hWifjPiyjxT9/bgtlmqGbw8kdqTUGIoFaKDxCFq6F+YcdHydxDz6ercVVv7l63vxFI6HlJGI4Q==,iv:m6wuUAnKjUTVWXTi4xKoQ3XHD6d9WVrh+ndQ1/iGXX4=,tag:F16eeiWnUfXOUQkWkkobfQ==,type:comment]
                #ENC[AES256_GCM,data:G4jRRtW/TbOem0U=,iv:D1W4vE06cf+Zi4rhjLXOx4ry2chUV+cU7C3g7R86T9I=,tag:Fa330L32eFFyluxwK1L1cA==,type:comment]
                #ENC[AES256_GCM,data:JFHafweOukdEapfeHLc78Wb+zaYiJuwPN0qn,iv:Zm2MeL+Pf+iGEcydE8uBGnOIqbPT42yfbftt6TtY2xA=,tag:zF1SeEkaIwDUiorYyINaIQ==,type:comment]
        extraContainers:
            - ENC[AES256_GCM,data:7USnTETcgaaQPaSL084KOBDgcQKHwR1l2rItvM9eQl2IlR2FOr4WGZqeNZSsKPNYPu7skacq6bkm4bZ7rTmapT4sJSFBwvqDeQ726ECr41TMGxm3BeeTorsY+FQCNQ==,iv:avTy9z+P1uajX0l5zTyy3lfHVOWe2QHtE3iH9v14bzA=,tag:ifdh39tM4RneuVfPD0F0rQ==,type:comment]
            - ENC[AES256_GCM,data:qIn7B3QhhCQ7eEYBbmW1W1rZNYNJaaV/oSq95kbgkFzKEEHpcJLHRwLyrmv2QFQFTgPu4XfUw6HJH5c=,iv:o91THRhdXMPeD1K47BQNi5TuV6MztyvBlteBUb/5O1Y=,tag:L7xaQ42+AxsEFMY+jx8dIA==,type:comment]
            - name: ENC[AES256_GCM,data:mRGCTsn4ETi6+tk4Tso=,iv:uIEbZ7oyTWX5FbuJ9dFjamALaQZ1lYfVaKFCClPImh0=,tag:tstAofn02ut1r/nHevS3Cg==,type:str]
              image: ENC[AES256_GCM,data:cqa/SNBaGfVCfw==,iv:WDjh+EsHo6rSgix35uVmI1rkqjpppDBZmiLNRlIcfT0=,tag:N2dZgAk7776Kyu3sxbeY2A==,type:str]
              workingDir: ENC[AES256_GCM,data:IOv3nc/wCo7C,iv:unCNjFtiwMcBwIzduSsu/pz1pyXzxR6ykpnYo1VGrl4=,tag:7ted3ImhA8wv/UxhgnhP9Q==,type:str]
              command:
                - ENC[AES256_GCM,data:xdvN0Ywkqw==,iv:IL44m4Xa1S0VV/E75GFhmAf+HZhIcHGNoarpyvMgxM4=,tag:VX37vNimstIzMszSHCCaKQ==,type:str]
              args:
                - ENC[AES256_GCM,data:Jts=,iv:P/e+a2U01k0KPOViL9TfUItRwtDaGwW7Y7Cea0axY5M=,tag:AFbuUS1r83c3VHAhC5eQcA==,type:str]
                - ENC[AES256_GCM,data:p7s0PO+c8pXZv+z+eSYBALeRZqk5Z8EEGAIL2Pz8pMdmap2zuFcD0T0ETadhm/nz+LuDkuBaVDdOEfS2L3PSWEox0RiOMA==,iv:4ERc2pGmc+vyGq3Q/iX7RVnsBemBhSXBkASJtJu3qHk=,tag:YepDXWVtmbccXI2odkDbjg==,type:comment]
                - ENC[AES256_GCM,data:WQLGpbuy6J9nLXMqcFeVpSQDgJi2EX87pyl5xqAEV5XpcqeDKKfSASKx8if11lQQMAJBDYyn5JqSoxK1aH3uV4uvVBWIUxdXJU8p5lIWPydrA/WBvauHLKKVgV/3mqWg2PPenqBoUeK6vd9x6w7+tZ3YzGeVZ75WCZqrdxot6d4E,iv:LL5WTJF1iQ9PjJAJ9FTqwPV3Ih22g5xNOlT39SApIPQ=,tag:qFvE3tva/ej5TLsgNGebuw==,type:str]
              securityContext:
                runAsUser: ENC[AES256_GCM,data:ktIosQ==,iv:eIneDVYU2BhrN8BOanYjtC27bBgrmc8sDWbZCFOt1PY=,tag:+AGlSoDIm6y+YSuxk4Xxeg==,type:int]
                allowPrivilegeEscalation: ENC[AES256_GCM,data:dtcNnH8=,iv:CYYNoB7UEiLbDnnwH6lNFmnzAekuVGki39vMqaebPCM=,tag:R+3kmRjIbmbMoaRQ98qItw==,type:bool]
                readOnlyRootFilesystem: ENC[AES256_GCM,data:eALvlQ==,iv:Lg8eGV4cR2RV3/oiT4EyktNTYodjKmFPUG/tRHdGCCI=,tag:JOKAX86JfzH3IJ+faECaKA==,type:bool]
              volumeMounts:
                - name: ENC[AES256_GCM,data:1WmnfIRycVz7NUgET5GOaQ==,iv:cABS4WEzoLNYjCiwYsykGqoAtj6PoWOUo+HUMWfy3+w=,tag:F9/BHv4oPZrR/snVB0hiVw==,type:str]
                  mountPath: ENC[AES256_GCM,data:Bs2cUV1wr8GM,iv:vxpPqH4V+rI/HRL4gNVkusX/Fgq7GTWbi0+A7TXQbQI=,tag:rhJRnWPXAojxVTG9hEZASA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-25T21:34:00Z"
          enc: CiQA471galwWWwZ/ZXwW7+566jHEaKNaSjnnYRYUb/mFNSQmXIUSSQAjg8vZliK91DIi89Y4tCNrKUQrQgO43UEoc7Cw0ho5fNC7tBDck0Q8kyvittTq7ALoSW5Ff6WairkfN/HtglXMOp1JjEjK4mo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-25T21:34:02Z"
    mac: ENC[AES256_GCM,data:NQEgIvIQVTE+FL2pg70ST+KCDqFFYzU4TZoUREw1mQBSfadQcazZcDKegnNI2oiG9uUFfJ/EihCLNRfEYDt/GmunwTBxnlm1wB877SIOU3Htatf4QLIWygqjqxrUokQ2sBzZW/m8EWYwR+5uWTWgmYq8oi+Wb+2KMEWMS0qd038=,iv:bdWXMmmqJfiSVahuMhCwLqpmKLsANGQCZtxqS6MIVQI=,tag:q/pp2taPNCJ26hh0/jXzow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
