jupyterhub:
    #ENC[AES256_GCM,data:lI4Kf6ahCmwDXIls6BWq,iv:V080DK6EJjDBuaqOR2h/pV2IakPvlioFqFEmnBG0PzI=,tag:4V+NaVB8szwiRaFXhuHS3g==,type:comment]
    #ENC[AES256_GCM,data:vHS+Wt3Ckkf0/s7t7ueM,iv:ji3d2jYKfVuTC+GJ39VzqVOXyU0t5LsvoCg0CZ0G8EA=,tag:szRW1xrHITDn+kbHhQRqiw==,type:comment]
    #ENC[AES256_GCM,data:ec3R6bCxS+GlyAzmas/RP/LzGRTy+n0P8g5PrFWYayR9nDA4iLLDVN+//oJd5dlriUiJIac8pUQptQ==,iv:4QNz6hROc2g+G7ngUBNqr2MItnshwaOrbhzIKV4ewEo=,tag:SS+IGdlGLC9M2LomRGAxJA==,type:comment]
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:ySuYkBn2iW2YAAf+3/t5VMg6M2oabuM6nA==,iv:6/VD10i/rti1pdExFbF9ayjOELAuDNSqAsOPZavZXgQ=,tag:eg4M286QxaHAs41n0AoDNA==,type:str]
                #ENC[AES256_GCM,data:QDgdRSvWuQdz7cEhEDCl,iv:oQbzhLtC+11cBTPKX3rtnhSLFWk3h5TOcZJVD8f/2lM=,tag:Y4IlcRQ7zZ7x7Ab1PTTmpA==,type:comment]
                #ENC[AES256_GCM,data:Eie0bNE+Rus+hNANg8vT3jrCS/gDn/TqlKcmP+1Gkf7QGqoEo/alNoNRawT3Oku4kcYXa2JPumf1Ec4H1VTuHDcbuaBE9Yb9,iv:SJsAmHfi4IXWRsgDdOJzsaGGiWwNcEvNYAssm4dSxOk=,tag:VUOwDbmosiDAByz8RypcVQ==,type:comment]
                #ENC[AES256_GCM,data:7ggf4YA9yR0jBw8KgOqa2o7vBN0aVJJJkZKQnG0RIQ==,iv:A2Zl5c14aVNGCHeHgwex/2H6O7Hd4jT9fD2gw2cewes=,tag:+N8U6z7v1jEQx8jFLkNZDQ==,type:comment]
                #ENC[AES256_GCM,data:HXqbljT2uJiMt4jGfHXSXgWmHEx6wxp/ATnVHDNyiMXRDjaGVc7p/aInhgxS95f7lEi4Xk9DzQ==,iv:Vrk19eENY6i3EwwZ61Xuq8qWvN7RqWEig7i1YHi9oUI=,tag:1voZVc2tCBlOuDySNALOZw==,type:comment]
                #ENC[AES256_GCM,data:gEgGylbZ9Gh0rGg=,iv:7Tcyb4r/21R/9RDCWPsgOvY5NnKUzTu7KPUjuVs0HK4=,tag:0z2/iriqvtMs2YHkob/jcg==,type:comment]
                #ENC[AES256_GCM,data:aUR0xjL1DjzCbMd7BFv+spZqHN9o6Ks61zoM,iv:P3PzfZaqyaP+h19ITeWo2HWdYM1blixIRfl65iHs7dc=,tag:bSFjOiz68CS12FB68kPmHA==,type:comment]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:xt1GIoY/qpQsJOEzS8IKZrO8bZ6S5Ut6HKArDhvNF9T7SU6iu8Mdr4hUCgw7/5rBbCZCqIr19vtyQmHekigPkw==,iv:iSj/tkMI01rWZcEcn01Sm1c7blgcIpGHs4zbMj6r1Jo=,tag:FjMel8YW3gAobHbQ+Kuf5w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:22Z"
          enc: CiQA471gajASPb/bWeJPITfxQKM6n+5nNEzP1Y4W47HZNkJmaQESSQAtv98xK3ObsaLdXv7PDUFyXy5v1cZweJ3zjhT8vVVfFMUJwukIDCwXbhbsPW/1IBXXPrYFM+Fhzu8+ycJK+clIkEpPtVgJZ7w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:22Z"
    mac: ENC[AES256_GCM,data:QeD0bWw7OrkjCSxRgo6y9+a8QL82o57yomzBMTjTyjOEbq4ZyV3ygceHLteO2KSLPNY6J0NaxIshbKquJQHEsG+/z+rlpZ0a37qmhZo4bn7Oudo0DiI3AloKLmfkeEnSChLyAtxbv9bHzXiPt5G0+Pzf2qzhJlzb4Rhgq3Fkd1M=,iv:gbXwAElxsc+Wcqh5TEeuS3Q4yIDomxLaGIKONpC+I6k=,tag:cM2l3+FUYeGHFcLZUiE7BQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
