jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:1Ur7Yj/tXfVI1GOaN1aR+OYTpC2mXJK9+w==,iv:mi3FAizljnQfm5k7LSc4maPvfQ8Y4nF1L/eEiMXUtw0=,tag:izafr6Q8SfpbOFIHKTHbyQ==,type:str]
                #ENC[AES256_GCM,data:88m/ux9eV+eP1eRMCddZ,iv:cgj1dy/dqn88enD6S8R7YJjGkmWoWmOoRYZVnK+04Vc=,tag:deVJpK7IB0V9AtMco+lw8A==,type:comment]
                #ENC[AES256_GCM,data:D3UPptMZpnBQLeywMW2cAiTrMBO4ft81P5WbFN3sz78RFyM1YQ2a3NaJ/cILjkfYuSw2xrB5588qT/tG7yzwGPE1HTwLrOjZ,iv:+LyvwS8lTgEsvucdqdwiIcnmvBk6EqcYQVr2UQUAZqc=,tag:QWEWO8Ikz3kzih98sdTkcg==,type:comment]
                #ENC[AES256_GCM,data:EpRhcBgftJWOCFgdKqgLKAVxDNUfEv56yJ7JgvRWBA==,iv:14EBRaUHqWv7Rjx2OmqEdTriAVvDx8hEfz4yEm29+mE=,tag:2VJbQVsXlkZTNJufGYI54A==,type:comment]
                #ENC[AES256_GCM,data:cRbTtUKVAY3GyExx1p++7QsRIcd/ZU2mnjBwPppX5um+dw9x+GDUzOhSqqRtBCGWIzbLq27wvw==,iv:eLILFlt8F2lfwKRebrqg8aPdR6ElyhAZ+gR34q7Ujew=,tag:wN6raACAsPTrEt49nHCbDQ==,type:comment]
                #ENC[AES256_GCM,data:ilt4zNtyB2sAA2c=,iv:aT2/j3uOq1QzkybAhNZlxLFAXd7wJA9pKOk2VdebiaM=,tag:fLQMtMFjL13UpQkAoY+6cw==,type:comment]
                #ENC[AES256_GCM,data:SZzijoT7P8ePLz+GgJjQKgasB2C78v4Oex+H,iv:9C+B6WQgpkLVCnjUb1DylYC4TCcm+wZPz7E4ReOViFM=,tag:qxZIUu1MO62ySA3gmMWpLA==,type:comment]
        extraContainers:
            - ENC[AES256_GCM,data:4YaHqE+LgxXJjv9VNIHujm1Gq3X3fiws1J7vcVNyzZ5aYu3irFZH4CwA16CwoSLnwTzg8NSZaPzcOC0eQdMi3kNY7JMV+Fj+HK28N7X2HEn29Fifmh7DBV38h02kKw==,iv:FugAwefE2ypJOuabYjuifcKpavk9i79dzojh4ExFkdo=,tag:Jb6RiXLjMy0U91l7xJ2Rqw==,type:comment]
            - ENC[AES256_GCM,data:3va5Rr0KMA0ZNAH9MwdclhSaY0Q/pkzg6WT7nzzQgG7jhCANpOFI4EVCuuxjQKTJ5WbP/VQkgg+Xfzk=,iv:L7NZz7JBYzs6NyPlIeTUN/icgogyGjILZjkEevKwe0U=,tag:BLFFFujGBJyVDHNgCRdecw==,type:comment]
            - name: ENC[AES256_GCM,data:fIkT00yAcxKTns571KI=,iv:McwZjUQlDOVFMU1mHrlFqOu9+LoJFMeDNzmOwUd0G0w=,tag:lP2BjtjIzS8kV60yC+39uA==,type:str]
              image: ENC[AES256_GCM,data:badMMK7gdHdsQg==,iv:32dG5esJjyS7Jcl7ruPaJk0mUl6ppOK2wQpoAdpzKD0=,tag:GwATfhrnUSa5hk5tHjYQ2A==,type:str]
              workingDir: ENC[AES256_GCM,data:utzZzY46/57P,iv:tEuRpnJiJZeb+5Y03StEHqOBW17wA98XANla51gy6iE=,tag:zs+rZtcvPT/UUN4sciYl1g==,type:str]
              command:
                - ENC[AES256_GCM,data:AiLlsQN42A==,iv:rBHkTmhTjsQZCZ73zMDCUZ87c5N8rCT/9JMr4EodljI=,tag:wNR+feQAbTWOkCIszk6WGA==,type:str]
              args:
                - ENC[AES256_GCM,data:X78=,iv:tKDDE8Dip9Bq7ajvmxZQ+BP2QVWeaI/2i3k3xFt4dA4=,tag:X9ukujVeAjp/t7w6BNu2BQ==,type:str]
                - ENC[AES256_GCM,data:LNNJvYDxvqX3FVN2MXcnWMa4BRx9kf/Uy6iBaXRmhnvX0Esdxsztx/4L4geMmhgXFNgn0jAIglEnKVeI1xkObP66lscj0w==,iv:W//m7OlUvNo7sxNoKMyZmvN7+pEbOnM6eCjsFdiPG4U=,tag:d9qOwnPbTdSL601NwUcLFA==,type:comment]
                - ENC[AES256_GCM,data:08iSVcCNgD+daIrhKCF6AbU90o0QwKxtOOc0FBJlBQ5VUbrEcA6hGZ9kw7n2XmWVUTeKzD50fIpgyri0vtx8g5f9v2tHqlQ7otZQA9vvpZ7QLXSvt44EKTGJkPJLGFkRQLY5aRnrrKlhHvwihad6nwxUgZ/HQSD34Hvp1Qieu8bo,iv:ZIMeEg6p6tZT/sqcJCZOSARZL0uf70A6n2YmL4kM3EA=,tag:O3NMkibB8bIS7U/0SwcovQ==,type:str]
              securityContext:
                runAsUser: ENC[AES256_GCM,data:Tn+kbQ==,iv:lmt0w+0AaJB+WM0Qwf35ZOYbS/GvWLQDsv8yZiC/7EQ=,tag:qidMtuwXFImFHGtVwZ+/Yw==,type:int]
                allowPrivilegeEscalation: ENC[AES256_GCM,data:I7+2pYE=,iv:l3ojh2gT4g0eEoL4LBAn+oCPrXFPcyb1kfgbOjRPGMA=,tag:W7y0SVkSvHbwiNYgEt7SCg==,type:bool]
                readOnlyRootFilesystem: ENC[AES256_GCM,data:LglXxw==,iv:vjxaD5hgR+ShuglXFS/EZHvHnAqjh82+2/nTT3ToJaA=,tag:9e7UbUJ8wTjX7tpIytrY3w==,type:bool]
              volumeMounts:
                - name: ENC[AES256_GCM,data:T5DbOFZKmcoBAtZPd9ozSg==,iv:+o3TfSVWKu/pFCeFcUCWH/ug8e45XUqSG5v1ZuN5wkA=,tag:1nZ3ymPKC2didMBixaK8MQ==,type:str]
                  mountPath: ENC[AES256_GCM,data:tat8uAQASXjZ,iv:TjdZ8wQGjENC4uc4IXTR8h3d7uK10gM7jsOUnnRL8r8=,tag:eNSJIS8C7bP3Gd/tatrEKQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-25T20:29:46Z"
          enc: CiQA471gasY3NkAt88fSKMxiTloDDXLWySeyA0QpeVgbvv/KneISSQAjg8vZJWkf32FqDqDwRmrNT3dooJUkk/9r4z0A9NPP2xKDH3VgUtHPpCnBsKe06SnoY26zv8QupbUrsVHbivutmnW0IFuMBC4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-25T20:29:48Z"
    mac: ENC[AES256_GCM,data:L+BCWf/CfbjNYIY/wvhsbMZyfVJtpiV0o8MZp1ilCezdKx0kteDhVZRaD366nQx8i/p/FVVOzCRAGCa/Orwx5GacY3nB3jw3T0dKbnTeVI/+z6RR/D8G/RQ/kqHb2hlLjfg0t4J1VwRBUAQodwHCpGIac6AoiqViNXqEGUMQR8g=,iv:Asmi4k28k01gf4sxE4AK0jCHG1ju+eGRzP593dXag2g=,tag:z6psRPfvXu87nS3yAN5CVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
