jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:7JtZuNDN2a2m3xrPWW1/nBMDZLWE95FIoA==,iv:tPPJRNX30DoqcjoyXhnBBevR5Bw00267yOxuR2WpA3Q=,tag:Y7Z0rAYxbmhrWKPCgELdcg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops-dev
          created_at: "2026-07-13T22:22:53Z"
          enc: CiQAWDCByxQgYqhBldPzq3/3PdUOh0gOukb3eeufz/6WUdxLNMsSSQDoFjihJtdHPP2n8dOL/NN/W2H5/mWn03oN68s7BmvgC+rlxq4e7QQ4iS5Z/FIixQ4ORJ5p/CZV4disAkQURtfXZ33ayn2gynE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-13T22:24:55Z"
    mac: ENC[AES256_GCM,data:01PPZar+DAnP6+Dp4Sn9JIcdrRC09WM3UxUBzgh/hHXikXu6DGch9vgspJpOYjjUF2kqDiTI/T7gOk8eCH2u/kWkMAZJ1rQ8J/bZRNbV1w1GBzhSsHVlNS62VO3Rpxvo17/5/P/LEN4Usvszw7VpW89bEBfsVTDPQdGyQqxLV1s=,iv:++SDTOC2fQD9jDGp9WsFGJCAY5fuLpdxKcrUGCtegoU=,tag:LikRGYDSAWkHrzDgePiJmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
