jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:9y46628GVAsIBxcu95hjaRf3A7fWAIhFFg==,iv:xl83mGmsvWu49+ggBr4NkBV8AZQ5RgVvzxuK/L19LBQ=,tag:4E5FRXPGl5VIHu8aJxVj+w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops-dev
          created_at: "2026-07-13T22:22:53Z"
          enc: CiQAWDCBy4k0dY3mU0m0I+g2VyoaOoZUqA9Pwo3QQxjY/rO80BoSSQDoFjihv0WlOpCcHHkCWy69GUU5Pyp5kaqBOKaKHqifFLeVdMZN0P8O3TkXBBIUcJiZjf6JVybQMi+FmuLhIUhIu6X/CabpbGE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-13T22:25:03Z"
    mac: ENC[AES256_GCM,data:S928jQWFOVRloBXe70r8I1VV9OvkikWazkVuSAENyBalkar7F4dHNWiLO9pYrQfmFG+DzylV51RbhtcB3sMoxkAu8NexlwSwnpnssjzmr0RGc4xEWlSshwbRtDsxQWds6v5Ft0Sw00atkuUO3dY8h7/f2TQ5uw50Wmtb2FxsBNI=,iv:o/e2QrQUGlq1GnsaKx2Zov3qnqKBxjOTQGMS9EpM7Lc=,tag:KduVw1JUX8LnZvy9O+qCFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
