nfsPVC:
  nfs:
    shareName: shares/sage/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - sage.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - sage.jupyter.cal-icor.org
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 1Gi
