jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:1JoenStTs4hrTniYBX63GzljZD1DDFqer+PsOQklrr0fiEl731BTyoNVWlHLTC+pX7pa,iv:kGfIQPfmv3bZynkw9gRfa16Ka52R36L9URYs2JTbmqI=,tag:rs8VLB3ZvvkBbLAQNpSOrw==,type:str]
                client_secret: ENC[AES256_GCM,data:RzgFMWtt6Pp5bTOHTZCaeOpN9QJHsFZ9mfm5kL8Rj3eVkWmbMy1Kk2Tjem8+Rf8PThGNgdGIFAn/Pa++5p6GAwTrRLj/puFd3Mp5DCTskmSzNXhxx48=,iv:1wn7ISIhZ5d7UvyscfNRNgsPPjXDOpK2Ms/F/MBFMKI=,tag:hob5GLWHbACfQimxVb0HUQ==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:/Xj6fioLdnQXzao+aBlswwSRRAaXbva4GiMB+0LjyE9cP1HlZKmBPh12na10TgalhsLBZ98mYlQhz0dSxS3y2g==,iv:P01VVYZt544ug2jj4FvOgiryRtxsBcq6z6l/yqbjaE0=,tag:KCFAk/TZQo/SofcFrgiVmw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-08-15T23:59:43Z"
          enc: CiQA471gatJ6tymftIZ+qROLchFuxalJsFU2oaHBZZWESS+UXTQSSQDKo3g/AdGKGaerc0yw37nZoHAC18YL0qGIMj26AnsDdfIrgf2ouBS8fMsezpPKKzbaSbCsL6ZoEHmTO+r5AM23ZLti6EIpEWQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-15T23:59:44Z"
    mac: ENC[AES256_GCM,data:fd9P2VYWSek1oFH8bm1H5E0s8z17ChBHLw/OBuYYl43d/rtExlhpaQ4Ic9ofoyjMjYlqHgyEjxdA/W/TAaWhSu+db0JQAobXNnWwislKXX+f2A0+emjMNKq7Ka56txY0MMe4csR7ggDDyo2FwB6V7EWLkzRoryqlCDvb0Yz55LE=,iv:o3pGxgy0QOqslW5TFgCMaepi/7TARXIjLu8dC6+NTdc=,tag:D9lSTFo5CiIC20yEeIvcsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
