jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:yFbkpgPNFMghHb8AkMCa/j4BRArTCaL+t7tRww==,iv:Ujm+yURTmrP/lWhRkrrmcC/JKEFCEbl5UVhDXcRml2w=,tag:b6ekXeEUG2JobQzPF2vIHw==,type:str]
                client_secret: ENC[AES256_GCM,data:FQP3f9CHxx9jAT4DX0VpEqFpakj8PY/dTgBXRg==,iv:LKIHne2Sn17rl9kG4HefLBB7Q5FON0b4nfXocoYt7rA=,tag:8RGcgrVwBS8wg/puCQABgQ==,type:str]
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:9GPfgC0j+WUoaWFeo6a/Qy5GgA==,iv:VLkwtanBo/gY6PutfNlTusMzRLrWGWivYBEiy0/M+as=,tag:+8z6xi7ag8WXJ9R1/UdLmw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:dNG8I4HxxeV9cCTI9zDowJbYcWiAhhCOQyL/uLtevlmTOq4Me5J8KVnf/0jkXTGP5z4Y6EnMMtV7fLdvWi4kqQ==,iv:PEiPZ916YU6u8paQ+7zsfCxokiJwfkFadcelO0HBrC0=,tag:Z+SBNJsZHE+8GcaHuZMLAg==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-07-29T00:36:10Z"
          enc: CiQA471ganzS0gB+bqRIXZx1tgpz8eQiQKYqnWtBI+y5qJYrctsSSQDKo3g/vzoQVTuheP4YI/LuIqpFQenwstF6c9s1dc4XtIZfdsQ+9A9H+yGjBlVQZe844K64mxkmYCV+AsWfoNVLze4AujmPQ00=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-07-29T16:30:14Z"
    mac: ENC[AES256_GCM,data:O3CniMebBPgokWc2///+yewQMZspCbBPntImuTjmAU+SOPksHtBhHpz7k3T+MA5Ys3Qo2uf54DQOmD1SbqrbHqiiAogIAnVngHJYHR6+OPJjUUPwQeQ2iop2V6cLXooUvasogGH6jV+n9CqkzwgXpGHJeMbyIzTUtFD89qeAnGM=,iv:UyhA4+/DVPT7P0b8i01Bw0+9zRzPjjnoZAvyrXxZp68=,tag:0dRswImH4Q30aNGJAtzofA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
