jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:mVTHYiIrtzA8O9/a3R6lVj6uyZn+QBjQ0XXzCQ==,iv:mqbh5GokLlqw86uGS4acoaipWSC7psxsY+ZzofUed2E=,tag:BgqG5jzLw6HBwugx6fGxfA==,type:str]
                client_secret: ENC[AES256_GCM,data:YJCuCeBmx7+/z2IWtDaEtich3t4k5KwkZOxXEg==,iv:sADTLoOSq7x7ij49jdXrAaqiEsI3vQhaAyyGg26WMrQ=,tag:D8tFaivw8CFcULT74+7KIA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-29T00:35:37Z"
          enc: CiQA471gaodiW8IlP9En6pQCWDtLaKX5PWuEYQ6EAyD6hrkFb3cSSQDKo3g/cqkZx/KOnYsOeiFforW4f+7L2XFjBvmMF1UxUxcegXYiTOUj7jIdPldDna8KaiWVcgNMYeDOrZQUCj830jzbYfQkQ/s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-29T00:35:37Z"
    mac: ENC[AES256_GCM,data:0MoZyfsMFEnkBJ6kZwYoMPcJbd0w+RfYDYHverCx88/ENDuFIapToSDhfZsaCOJyT9pB5e0aITND5IFF1PoEtTG6eMxufr9KfS7wfNNaoG7ELSpwENdw78UdclU82fNKheVB8pjDKqSjWmQqJXduhJXBygP+oCWPUN5EUFrAc7k=,iv:pLhU2XjVGxqIsczjffd5g7WRLLMV8KbJmAmVrRbDO+w=,tag:sFMx7cgyveE5D83XULUW7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
