jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:u96SmF+oVYxNa6e9+Mwt97NnfY9yUu5VEtBEaDUyfgufcW6JOCFvLRP8KTvZPkpYNQ82,iv:NPhvR8zu9gBg1I9Ap9PlBuIArle07z885ONfQCJcCbk=,tag:x42TirXZMZaza8HnPrKmGg==,type:str]
                client_secret: ENC[AES256_GCM,data:82viaIPwNjb20QJ9V9Qv5EkWgwPVKUUJU/7jqzAcJ3mSviN5LSwxcE9wlW6XNZHGAZtsAe0nSvruKbTE3Yyr8n9qzAbdj+v/kxWLfR2nGIdinpR3qgc=,iv:M9+BolI2OPvbvoR7/XPDFukohPyP3PXl/TNAKHnIMRA=,tag:AK3QfxZnCk4Vd1s94XU9cg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:ulBfT3CGd9a9j+Mznltn6+cYS900x1IFTAmU98zHdpZhqX2of5Yh4mDXpXavVNigMlcvunn6YDvAnFC4+3exNw==,iv:/ii9dSQ7Xgjn6zGWe3J/PDiwoXk0Ilsoq2RS9WRRC7s=,tag:a8oWaxRrmDixxfDXH6R/AQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:29Z"
          enc: CiQA471gakiKbl5YFKon9iiAMNFbfucaD4LWefK6+TTn2wm6gPMSSQAtv98xA7nB62vhcccf50yclocoQ40Up3erw5fLIWyrx9sRqc1zsN0JTuuEGpncwfzymxwFfr4FM2wzEo+JTaAlhtjWFAdVG+c=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:30Z"
    mac: ENC[AES256_GCM,data:Cpm3T8/ybtRTZvJxZM9i8XkCAPnVWiuFDVp2FL0nkRIt4D0Xa9zwDKklLppjMFHZ9rb9DslyyZggXGbovPh5S7ob+pEMv3gULf78pek5iKKWsHoj/s5EVyQsZL4ualFigmNLSiA95HDD43+w34ADCixW9OGaZdl85Yh56I9N3AM=,iv:K85RI5RpBVzuEsUgHKNMumfMPPOpGrlJdzmmdp7B1G4=,tag:PcqdAO0Vq/Yx1v6nFvolnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
