jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:v4JLVms+Lb4wnVoRWKQeZ8m43H899uj0VAE4sY0iDr/fy00XtMy3nT2NEiRziPPdBsFZ,iv:mdh+tViuc7hXCfOWQQyu681Bgt0rwza4YmJedRtIeiA=,tag:qa3gsWyJlK9dG1w5RjZYIw==,type:str]
                client_secret: ENC[AES256_GCM,data:6M9zqaytkZzHPzyYSkV1sg2HwNGEp3dnw02EgLCacNQWMF4Dt3VQvJlvwMXlvctTOFfRCJsIGvKePKThDffPM8JC0+wldh9diTEvXkesjJ+PFC6t7nc=,iv:jFkSZCAqMZyIvR4C61C4id2lwSUpcjwnvIx2kY+6K4s=,tag:vcm7mBQlquh8Dtfcf/mcjg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:12:52Z"
          enc: CiQA471gaq4bn/MR3XmdoAnIx75PR2Qe9p6slFP6Eefo1mkIbK8SSQA0woZQzCHAcEktABfPg72NyUwMirBCV8lx6n8w69trWPWY8ShIlxT0mYlNIH2eYnvcCdCEW1m2xCpN9N4y3Wo4VoJdPRnm7Po=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:12:53Z"
    mac: ENC[AES256_GCM,data:oRUosw7AR/2YbPSB3ZsoujLcrQnDKKFffVwCu+/AgQUSdxMNKMEkoJfOZa9pHmrntigOxBRdFaEnyhmmQpRFHXgZ55dbGcSRBpgQEVkrjv8Jc0n3fXaYy0CI3tsCfd/8EfwwitusG1tIGiOKK8efHL4EvX94s3ST/fJ80e2YIyY=,iv:eJ7TkFcopgzwESdT6FTaMXuML+Sr17KxxKPBk/mJzuU=,tag:WgV2pLoIXZ9pWbfEnITq3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
