jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:qMISQvtaqI7bcvPTqb4GAxZ8NB4wuziw5QCDCjEbox85S6hOtU97svn02yzTkzSrVfo=,iv:GS3tAcdfcrSY9YQD1+mKpLPhC9cwrf32nfDFxSZt0rk=,tag:YsGrV2XD6ExtpQwifxx5aQ==,type:str]
                client_secret: ENC[AES256_GCM,data:99wnezVPpmoNoJzrWFoKeHiyvyD3I2pk+Ci1waH/MqHPunXXjAY90sRS9AEt3kLqQqIJCfyID36AopmsLuHCl+/ClF6Fx5AyNLWupSI6eM4C7RdW6Eg=,iv:1OZ0OSZr1DelzvyHd4ANl8hgkrpEqgY5DwRSYx8OYjM=,tag:G2gWxDTGu7aRCA64StKLtg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T22:12:53Z"
          enc: CiQA471gap1khBFtiM/36B7by9gP+l9+hY6Fm0oa49MhgD+b4cwSSQA0woZQYjO/ywPK+Q7ahY9cEiEP3FH5KV0ck+/VjK60r6naQzdnF+wPQcBffEplLEDzZmaWqcAsLTPwUBB0fFA2poGawS+VLKo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T22:12:53Z"
    mac: ENC[AES256_GCM,data:Thp5lDNFPxe/CTdLrL+b6YIqfDOPTjCYLKsDnyAl1iJ0fG/5L1Q14fsWJiayzjVuUMmskdb9TgJUW2GurQZXvG9N0KDE6ScBTR5i4NZGMXk/82qe8pZeaBiweWOlo3jjPEZFXYsoHyC6JIOEX8Uv7WzxYnvt8tJrm20s/dT8YWM=,iv:3v+E5IrcZLedA3Tykq737fqZjHIdEPIp0cJUwQJsSjQ=,tag:uHQuSVDtI9b6jE+xt9zJOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
