jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:XFQ9ttbvBsSGiTOA/+sIsrRwgV/OJyvcAQUiUiB5Kq35oMsY7CkEroFBDsd+kfA79bg=,iv:WbVXcDDOD9DvL089MZbfaniBm9C6EHodc0UTtdL89zY=,tag:yO9XZq6CaLpqaeBJZCn3fw==,type:str]
                client_secret: ENC[AES256_GCM,data:ZLlPIn6VZ1T07gsU72V5B7yUtNdM5UikGChPOAv88r1MUhjtVaz4dY7ewJmrmvQxKzIo5ZAwyxINW6p12axIiFeN1EqFFrPTLNIi/ttvJ7Ll7Rr1bVM=,iv:4PbN6+RUFzHp9kriP+hDv1DhiQ2Gny8onJA9jgxwtdM=,tag:YJAD+xRa46Od87Iauy+j9A==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:U89ZHljC4vnX4t5xw/R4exbIGRFbXiwty69dKgb0ray0OAzqIesJBqB1HlLC+R15GzFUMtmStqWuyVoA/9vWtQ==,iv:LPCXvgGb6VH9OlfPN2gqF7veYaeMrnpJCUGmWaQNAHQ=,tag:qVyN4W1I52s/UtuTUSCRNA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:31Z"
          enc: CiQA471gakl4O+/8iH8WO28AN4ZHXXkC2XrqxIgB+zkSxoyS27gSSQAtv98xJLwV6FWhwYlnbHByCCc9z5yG0UOLrwgY3asJwPc6P8HvimEKB84jUGazEurpIwEQs32mD9dw6jhlmaeGoKCzvFvc2SI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:32Z"
    mac: ENC[AES256_GCM,data:8vH9+IbFpHMtg0i2LoVN+J17Y/8IF5CoEqf/O6vcPS61r55popcOtGfyHtjbO44JSaCTt1QvVl4786QmQkXFG/cOnWg5r6yvvkTBFbs3t+jYxrJsjSdX1avkGDka/AicBVaYiAqiqTAcQeOz+HLQebB5YcoSAfPlBPvWbtIZ+FE=,iv:86TTA4zdjiokg28twwX0ejdCeAr4d11qO68dscgU4HM=,tag:oOunWAaqw29u8TFOfaQtKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
