jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:21tbg1kBEIOfWnattfjLdvLtu+HnLhuN6HJigj1gmGyhuQKFNn7haZUX5xSeBivuhliT,iv:BNMxIJE8R3ZlXZMAeA1wUvx0iPtE+fFK7uwf+3tkXG0=,tag:goYoq2Ny426rLMkFAN4ujA==,type:str]
                client_secret: ENC[AES256_GCM,data:Ed9jN9S1LkWunn+5ippJ51l0DF9+4aPLfpOQnXWiwDmfefb8EktDcePbrsy7MD4FeXr+/kr1oi4RE8PINuuJpOILih5gtAtNdhPKjI+hm8ffoC485YQ=,iv:7Vl7eMyaK4mJ2koSqeur/Hmdl/ZFSe407LILP45awiY=,tag:/+U/joKsbNInChOWQ2Pxuw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:z8Gy4gzOiIfsfdtiOBhQFt3cAn+jRxMqMP8NEMC6ufydLDdG5GGy6UZa4vA5jKPrJi/D9bXgzThX5aI7Q4ImCg==,iv:n0ldH8Red3BmsM/clEC3yKrh3n5ZXuA55IocC+EyXqo=,tag:MNeLiqKAt+j7gko+hod55g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-08-16T19:17:01Z"
          enc: CiQA471gapeel/gTnC3/uvgXtDgt/zkmzjCG/89D0kbJWDylrikSSQDKo3g/mO4PhblQO3l8AeGtYiI+abk/vW9bCdjvAjR9I1CEJbc/YdmdNH/+HmoVG0qdK3C5HGllK8zzpThLg0mL8idWkaGt370=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-08-16T19:17:02Z"
    mac: ENC[AES256_GCM,data:FiKUHLCY9HAVLdP+YB+sgWKgnLR3xre5aWdTj5a/khD+B3fgzJ7dV+OntjmCit/RoXD+soJfx3JySCuppqXgOhv+EJSp880/gwGYb4KzVoHI5AFVKz493V6Z41p0nmhiXjORgBzuSLt0rtSZxHp/YdXSdKkWU3FKYiWE+lC6YWI=,iv:3puYxJBFjPfdqfx+3WhPlihzkq3w8Lzlw8Pqxsr7DmY=,tag:OGRPkm00sH216q/LZ6mudw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
