jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:w5XUolBzBTWgjsL9cyTn5Rg0h0T9gBU8/zhmN1LY2Vl52CuJYQ7mjKenLKcqQReA87mP,iv:1IDMdeMmAlDT9Rq8iRl1dVkANmLafG8NU53DBT3OaQQ=,tag:9gwfakqYC2kTfYmFB5VRmg==,type:str]
                client_secret: ENC[AES256_GCM,data:ZZ7ZilacmTycQL8rGZen3A+rJBEeOn0/IQEfcmdH00ZEa13NvW4d+TiRv1dYkdy/74FqLGGgnyBFubLE8cr4RXQW+ate3dQ1HkooJWhf070F2Pu/muM=,iv:Jf/gSCn4mCVZZYUHV1jvnI8Yyy0uN1ZwwnKklA4y+80=,tag:hLkw94PwyV4pMIRHSWfb7Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-08T18:48:56Z"
          enc: CiQA471gatc6wSTaPLpcuk8vaXuW0mo0pnuQZAwq/0CrOLbzQKQSSQBxTImxEDcuIKxuHNQ4t7nBA6t5tLSWh6dLsgGpf6JmUYYd3Vjb33ayo/HgT6Aw6Mu7X6eQ99AA9EIdkzdwRi6ABH/yU1+3CT0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T18:48:56Z"
    mac: ENC[AES256_GCM,data:m0dYUUMoL3YOuSMTXwp3bwNUpmuaiZ3e6IlwDXHtZg7Av55eBEm0rEJ/10XN3r153jnHylYSqy147uxcQuCUGeft2PCN3FZxsLxA6jcCdlBSeWJbnpiwXH7DGvVwLcNTXnVpZ9WEAqoISwp7n6xquzwMlhxDM+n1dgaAK/sJAaA=,iv:qxuj1nBrIeaiiw4sgAOOoT2QSwa+pg0VuC8EJD/0EbU=,tag:Oqb47UFZNY1dGSwnW6fGAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
