jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:r7V5fsL9FhWCmrCOjuUMumZ280sT3LgOR3MR3tlNSkoJepvFWWw3b5v+QGHAdXPmoMTa,iv:fA7KREeubYqZ37u44x2fVKunLwEFke0HL9YCRM9eZSw=,tag:vzB3uNO6VOAFwcZDG68KUQ==,type:str]
                client_secret: ENC[AES256_GCM,data:hn9dOn6WJBZnWnfKK+wdIf0ZaTHNZqloWUma3K/wmqxWzyU6cCLkZts0z74LNm2qAVl/TcVENuVyEwXNnG48c1dmFfVpM9b+/TuOdb6pncXFFMpZLwY=,iv:Sj6cOUJi34JEYSEQNEcpX6J+0g/PJwFkP1fiGNW+Uak=,tag:UoaEZETPSaFWbDPqLOQDRw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-08T18:48:56Z"
          enc: CiQA471gamwyx9YmQGsStUNp9cn3EbSze6KcLZ/2M2cPZCZN7e8SSQBxTImx7lRn3byuMdp9/Jr0od/Y5HwPeVPah+2ypOwqjvVX+BfNb+LscTkTFE76uB3hjv4Vnnlxzgwn15v0cz5eyaShlEVLYxI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T18:48:57Z"
    mac: ENC[AES256_GCM,data:1OMjVOZti3NvkIYTClvxg3xzMio48iiqcJdjYuknphIt2h+j1HARgETiqTUR9ThMgd8vBYc9OVREK51ZWoy6pgMVRz8IBRUOkDkBO8Ga6PWPxvrI1qo0iFx1DwUrQzprGOHTpWaqzQs5viak4+fk0pxIRgdJI+Bkm6+Hfo5XJIU=,iv:FvFuvKIB5CQq68cB5JmuJhAjhu1Yfl22L3MQAPLu/SY=,tag:p5AfuCbSGf/NVT50PhEvzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
