jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:kDJt5oZhC+L3xuEGyqz/fjkcFIcBpHwOwjRNaW+Inp+Rq3xDvuIzrUqWNeEk30hsI4s7,iv:ZSjux575m4qyozxTgwP66OScznlwwZcra7id87VdF8w=,tag:hVFr/mPjVv+YFwxe0L3LGg==,type:str]
                client_secret: ENC[AES256_GCM,data:d30aW3Ofe3OmL6s6QR1lR1AUXOzG855yrnbKhOSc3S002mo8GaQ+CFTWHKEF72u80P7iQmu5o1nmVNebUN6ucyHDQAN6hjKqokwN+qbhIsZmDg6w4Pk=,iv:G1ZJaCN54evuysP/f6CoZhuNNnPYxVUEzBZAc4GlpJY=,tag:qAp2XgzfpZVja9nraeZy+A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-07T00:58:47Z"
          enc: CiQA471gakaDHtEMgVDuKJqVZsKXDD/tNKRgxVyzo1b9+vYpFXMSSQA0woZQMtY49KchGQlzhTDiVsDc3APWoCIQpq+YGdP5n+dJTfbRbekqES37N6qz0uq8pn9Jpp3sln4M9scZVc3KU7RBxVasy8A=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-07T00:58:47Z"
    mac: ENC[AES256_GCM,data:+/LZEr6yGvzE5FPm85lGwXS5ln0w94CzvmX/xzpLlFO+O/ajze03nNrQaNt8OOgzVw8DiatW/i/dgCnIfMJGNq4fvtVkNElylg0fcJa7mKN+7Q0q6PSKkuvi+qZDPg6joWSILtaOwMrj7vn9ImRxkQ79j2CZ55JrbSKxkRCUJzQ=,iv:gUzmZGHm/FX8u5xjXFrl3s/tMxls0rZvJ4tyM+Khg2w=,tag:Ij/1vSBFhvlKv7f8tMHusw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
