jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:xF79hye2FvxBZ2x1W0bp5v0vVA7QhmEEIFNM/pwR12I=,iv:ARf1gffQTBjSCTv5RrcTmXprbRVpPR6btPCMYinnilM=,tag:9VKSjA4en7ReeVrMiZtSvw==,type:str]
                client_secret: ENC[AES256_GCM,data:X/84K1DXQ3RdeOyGmQqQzixN11YNaXjdHp0W8CQAhlqXvG/qPZ7wndfun7/n7HNs5iQ59aNt8B0N36fgd8tC9dz5O9qeZcBzmuTuRB3mo/E5rv5nVMg=,iv:dgjNGDMVkxniCepkcz74N5Y7UAqSEUbx3WOA6WD5+vk=,tag:ByzB8f71z5sZ/gGX/wGpqw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-02T22:51:10Z"
          enc: CiQA471gaq89b3Z80MCMWrq3q5cy42fPHybxF6rY+ZMIGZWP8tkSSQAjg8vZ1vnSGpY56R+dXFblw928Ix9TkqYjJ8KoqTCRSd678t4PBhjGtDn0MeRYzouyaXixx0BX9Wt6uiLDC7OITA0d14gpbMM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-02T22:51:11Z"
    mac: ENC[AES256_GCM,data:FgIqdBz7tJ6O/tZTOdHhlopXYOJ1j95uPb8ieiaRcvpDgJz/4vP03tE1IN8Fedr744ZXDIodhxw6AwUV7fdn28FbkJnK9cO+jDPLA6g4FfVKJMfGe21rrQ4q4Qz41dpFxdTgFv0l+FtS0S6mCKwe1hGyKotAG9oZC/7SuIxfvKk=,iv:RsK28MMy8ha9zbD80bzzkU+NACqdghsY+yx2eTdJMb4=,tag:L4+HoMjHt/vwMqS7unvaSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
