jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:PhOpxs7pJ/JSWiagwrljimE97VkIaxQLECx1a9uQXF3Zo0erd/x1hbPJaBrYqJqTvjNs,iv:Hv1x8OOV5VI9uVqusXfPb6XEfrz/cF2YlywkIEQAHwo=,tag:q0AXW9CofRh/c0ZOlxFfeQ==,type:str]
                client_secret: ENC[AES256_GCM,data:B3bbaIRTx65s03Hsf9XnzUKAaZEBhwGDVa2rNFpCoiTVsAZM+XO014Cdr1fBE4pyzMRcFmMnztqwthzjX/ZDKZhlY2RD+MzXHzfpaxOh/IbxVcunyEw=,iv:CnNCMG67D7UvkWHHPKr8mfqz+Dqf96wPpkXacCzqAwM=,tag:By14rknPrqDEDtEN23GXRg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-07T00:57:31Z"
          enc: CiQA471gai958UL4GTS8IaoJ2ntRFtz4UYSgD+iW+eRuBx1YK0kSSAA0woZQ1S/yp2U3q6Vq5zdchzG3/s6DIMoGGG9LC61g0Yb59UdrYpBc8/3FWgnr4pP5TbTjsqfZ9QdrUMsWtW84h2lLLYIqMQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-07T00:57:32Z"
    mac: ENC[AES256_GCM,data:0PlAaB3KCurmyH51csc0FB334f1zR0kVZ+PfJhtbseCXCQs7iLa/j88tZ9QJp6jlTooMWk6cKCoVjgfuHtsOW9qRIViDn0y9awicWRFgubV4SYt1AVognGCdBVBKTKedCraBxs5uXZIqpbYlNoDuMcU1/lKuFpr4XC+Ar9JQR1g=,iv:Ot2lsfJ/64rf4nBvXCGRbZI6M3uI3z9uagQlHNyc+HU=,tag:/rOZXH6cnVgegCYiFFb9Sw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
