jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:JYRRZWHNzwtuz0Y8mhnJsJszQt+kvc6zkmgQuirnJaU=,iv:Yg2UBNPL7wvKf/fwNH5nbkOqoJtFH3vnKGktmHTmh9Q=,tag:PEptSS666eUtj3ajEdwI9Q==,type:str]
                client_secret: ENC[AES256_GCM,data:KLQDkUperf+Pz/k83/a9wlkz5RFFqyDiewonpNFFTUd107XquABJh4T1ygjIbsIgz/kZ6Hp3S/8TI0bN/qQ/4JrM05kPfDitX0HZw12DZh+b3oYQtW0=,iv:JoC8wYluFyByUXrJNO+RcCoowkrYqY8H6PBc9vCt9GA=,tag:HIsW6zFL71u3j/rAOATOlg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-02T22:50:49Z"
          enc: CiQA471garSBpVZaC3qcZ1WvYMw2Tn2b0VgRY3qZxVfpA9MvDloSSQAjg8vZ8G6ALLkao2SlAb4COmSfJVeoa1hh1N3xT0W2f2uGEjF0gZWztB0Xz8yZh/NfhUelI4Qv089ul4Ef6oPOHQ78bM4Rl6k=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-02T22:50:50Z"
    mac: ENC[AES256_GCM,data:v20Ec8hRyDaQYDVuLywyduLoJFFj6kn0NuXBXZm4SLUklYoRsGIthwvPGJvv4KxAlqecVoq/ocdKO+uk0Bl0WYAz42ibtB0RYVsekoVH8FKMKDlwlv/2IhLr4syg69pNEwRKLzCp1FDv7v/xQdqOkAHz9IPIXOZXSc5NdKd+cCY=,iv:B7Yjrgo8zITuVHyOzvdFqknlG4cDFGXgLp0ROPe84u0=,tag:Y9N4jv1dkPkS4/gEecyy0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
