nfsPVC:
  nfs:
    shareName: csusonoma/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Sonoma
          logo_url: https://admissions.sonoma.edu/themes/custom/ssu_radix/build/assets/images/ssu-logo-full-left-blue.svg
          url: https://www.sonoma.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csusonoma-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csusonoma-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - ortegao@sonoma.edu
