nfsPVC:
  enabled: true
  nfs:
    serverIP: 34.118.238.48

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "main"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Maritime Academy
          logo_url: https://maritime-archive.calpoly.edu/_resources/images/cal-maritime-logo.svg
          url: https://www.csum.edu/
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-06-30
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        # temporarily disable token refresh to fix admin access to singleuser servers
        refresh_pre_spawn: false
        allowed_idps:
          https://cma-shibboleth.csum.edu/idp/shibboleth:
            default: true
            username_derivation:
              username_claim: "email"
            allow_all: true
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: "email"
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - jteoh@csum.edu
          - tinoue@csum.edu
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 5cf46ed80906
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: user-pool-2026-07-07
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
