nfsPVC:
  nfs:
    shareName: csum/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: California State University, Maritime Academy
          logo_url: https://maritime-archive.calpoly.edu/_resources/images/cal-maritime-logo.svg
          url: https://www.csum.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - csum-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - csum-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - jteoh@csum.edu
          - tinoue@csum.edu
