jupyterhub:
    hub:
        config:
            {{cookiecutter.authenticator_class_instance}}:
                client_id: {{cookiecutter.client_id_prod}}
                client_secret: {{cookiecutter.client_secret_prod}}
