jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:pGNpUFdjaQkpskklOQyZwdwRsTdA9eXIeRkk7z01HADbq9iWsCGBBaJJOu4tT5onOUOg3w==,iv:q63RYU90lgQwNd2Hey88jO6JLb/sjl+o5HAB4IzwKQY=,tag:nIeIiAFmq3gDGEkLYg1o8w==,type:str]
                client_id: ENC[AES256_GCM,data:QoDDMRy/AprCnzuIKrJ/2uB3tZY=,iv:Us1Tap3pxQFwytZ5+18i18cHN0apjJlZfHXQnH3buTY=,tag:xtduc+dhz6eJ5BrUCUGRYA==,type:str]
                client_secret: ENC[AES256_GCM,data:KYRQF7MZoPOxBp0t6QMJwiOIX7xnoZ2N7z9CJSJV/QGMx2c7Joc+IA==,iv:Gb3PS+k7RPNeR5xT34LFdIeAyC0mG5qTaaiBtlMHdDA=,tag:kftScHlYCvXgi1ZUU8bj/w==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:hIAnmXMY,iv:No66Z3b26nygA26m1sVWW13bS0A8s/7FIZGov3lnNvg=,tag:uWbNKPQpq97/MQ9jHOED9w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/5a15f4ad-7248-4011-968c-1595888ce007
          created_at: "2025-02-24T23:07:14Z"
          enc: AQICAHjfGHM7bUxlerxo7xU+GaCIqAiNcpUP+WvvZVLCeHISxQFrxpi+7GjO5iuq/K0/5uMXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVQ4lzulbv657bhk1AgEQgDvOF/5L9BJEaPq26BFR5G4JaT3oTQjCD/knL6EMUMZ45Pxsd1VHrznimq+bNAFf1JtYZqFWrugOpPuONg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-24T23:07:14Z"
    mac: ENC[AES256_GCM,data:yp/pEDSxdgCvRQFluEMpvZM0Rg0i8bwcyVhfnXw2+LpJYWnyh3i5Xqxbfgb1caT++yoQNegFiHcEG+8al3BgOph9TA3R83XX62EAvCZ4IxCsNGpilU8jXNgVcQbrqMnLISw3k8R5NKQNZ24rXd0LVqImt3NG5lMdP0KxYNQ8ln8=,iv:cRMP+wJSesy5nUu2X7to5Xc8iAsGn7AMRgZ70LTc/XI=,tag:i/DJkgJoTc50FSVv3VMHNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
