jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:0uDiXtCpAKsDDlJbdJNS6roge+o2AkI56Un8E5YH6ovSt7x774l+TdNxVz7SH3p/uLlx9g==,iv:vvCOO/7QuTOC+WZykYOcmNqwkN1C0zyHiP60H6xCTqY=,tag:2CuPpBRBwdAEQ9HFAbMbtg==,type:str]
                client_id: ENC[AES256_GCM,data:xnKfQ8jki4lXYn+Y9uJFGkuqsnU=,iv:b3HJuCAJoXQSeHA56V7I0emwssCQDuj31QPHswEKCxI=,tag:OdSipi8q2UGUXn2Fk2U1XQ==,type:str]
                client_secret: ENC[AES256_GCM,data:UYK3hxdyzK/+2h9y0YiWA/Zicg05o9AQWAO/50Ojfm/ivFBZHcsP4A==,iv:BNvBj8ng1Z7URQqR5NoXDnAHqLNE0Nzf0Vq6r5aciB8=,tag:+0jB5mynBQNtloNsbhasDA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:PVxo5ry7,iv:398ICCf4gIDWs/yS0UP5qKAUn51dN9h54ehl0hZczcs=,tag:rQCBpVolA6qDxy7RwbC8rw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/9c28321e-eb64-49d9-a0f9-30c50f9b0214
          created_at: "2025-03-11T18:41:30Z"
          enc: AQICAHhndPrOpg8p3dk1k+xmm13F+N1/BavujEV499t6yDc5OAEggWXbdS3tErWn9MeC8qeyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW+HKVOuncqnRBW77AgEQgDt3pIj40qbuIZGFdB2BnaWOZPibx5Up/XSUisVZQ3U2q1jhgT6qpb3l/M1IW8WqeiJWBl0QmhCEO9JGyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-11T18:41:30Z"
    mac: ENC[AES256_GCM,data:SlLtGduIFrmZM+JT3i7nmg2acuCVhW+8qNBwlKz2XC9uR3OPgSgt+l+2G+S7Q6hZXmNd9givu0hXZwsJ8epNOBNjTAzemFdyvivnvZ7Olz/4fnSBNy31yQv6NJ8+MxglK80uFBTv/50YDOUiA/nMMVgALEwLBPV3QhjQxCXZvBs=,iv:Izv/8GzIt89b9xva1ooeuGaX8fAOLCmS90YDdSk20fs=,tag:ie0uapPqNaDiPuQtWm9P4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
