jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:KK7z6WSLNCu6GMIoAhu2uMw6uxolbzbb0mFCogZLedEGRt7TQNHCPrlLrZ14izpjPKuWKg==,iv:TmgX4MAaI32wEy1UkGE58k9pZ4gseXZ/U79ToXLD9LQ=,tag:e+Ho6c1peeX8U3k0Vu9lNQ==,type:str]
                client_id: ENC[AES256_GCM,data:hi4sOzkAaDPTnJK1G/pmSgKoju4=,iv:4Tm9Npg0y2XKIQ/ngMmMVSf94oMDrX4FkNsZoDYlkqQ=,tag:TSraoYzi8zRvotC6YayosA==,type:str]
                client_secret: ENC[AES256_GCM,data:E0xPSpWWXj6tbOgEWQ9IjYhoacRsF6Sw5LCw9NXsMScc3AyhPiMW5w==,iv:E8SSuOaLZv9BX+Xw2lntaY5WGDil2MuHcQBT94skMOo=,tag:UNgcv3PbSML3JSdlIqjTHg==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:XIr1pHtH,iv:8iZPOnF1lQYabi7P7nmEFsuH23D+OYuYuFsvmWDQ39E=,tag:BqyOUF0vPnQy87sY4EfzWA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:01Z"
          enc: CiQA471gahTVRILUBuiM6zFon98BdwvVtW4vKxrbighvsybf+dgSSQAjg8vZh9CHA7jFDyIGE2+LPWcqYi9lDJs3J1U6W+sAZ3EnQ+U1NGD6JVn6M+YT9MzahoOA1W16FypgT2JmoaQ386Y+FX/S7NM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-11T22:38:03Z"
    mac: ENC[AES256_GCM,data:7278k8QBB2EEkLoQ/h3wtBlqxTMJlScAgAKVlo4RAf/IXPgmWjo9970aUy7gr2X/W3/rvDo6Qqmn4fx9hUJxhiQml9HBHh4ZzWLvBOuVoDAckeh6c8Y0JUTGG7rnxHIXZvdh2bm70RygCz5SdXLAodIl9tj4TtmnIR76QNH9wxk=,iv:/uyakNlW5gb0lyXZqpt0YouN8rc0gVFeyKegY/qXsfM=,tag:pCNFW927rnIYklnQbNae1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
