jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:kvIqMhAyT+54dLUKAZ2+Lrs5GZL/Mkb1nQxKIF+5ts8XUbdCU9YoCVjvBAyniwab3p3iYg==,iv:chUOpkAIChvFgXtALe/adUHp1HQAc9gHrf9hbk3Ww+I=,tag:9/y/7ssOWXfzTDZjwjZxSQ==,type:str]
                client_id: ENC[AES256_GCM,data:QgjtGpgun8JMCBSbz9hC8WV0DAg=,iv:pCp9xDTSY6vWq7OXYSkD6W64vX+6dZzLsQtBSgqwHoU=,tag:qI6eA+OLRWSpRdwf79c/nA==,type:str]
                client_secret: ENC[AES256_GCM,data:uJlT1MSIbPm11F4YMPgUTdx3/1+0+PPNQuAcxo15Iklo0FDhrIQhlw==,iv:fB3TRSFqgPYUi80sMvsZ+gk4vcfcToqcluxBFaM83ic=,tag:J0Flc4r7B9qxuSezQb7d2w==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:5JZ5fs8Q,iv:K0GbhM8NjORTxeM6DO+RH/CIr3Mpl1P3HQOx5GzO4nM=,tag:TUJH/jgPr1c53EQtFuyA0Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:10Z"
          enc: CiQA471galV3Nb08FwjIQCr9rbKoYmepm/0xHcBky/yWU6RvR0cSSQAjg8vZVH4fuARRFlMVqnxnb4aSdXDxaoPtWBuRFCM/HS769qVml6AQLK3NMfVi/ALRD3MmV1ZE8XSwdnEaBzhPPe+p1/BuTRs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-11T22:38:12Z"
    mac: ENC[AES256_GCM,data:EQ/olCLTqqVNX5cXqdAn7VKrQ01iolfjqZwtbuAAI3hyyyiK8mGKi0tNRj/cEHfdvlObRVOAM7Yb1VleA5loajm4IbEXhOkkpvibTOIniRsS9OyPKZgqleWNb/Ge90eRhK8InbqQ+yrnZwqohD35lgbv4d5FurDoedZm4qDmU10=,iv:EprR+L3Rt2w/xgaA6GXIyWoGkwRBin7nIQTqQPR4Mbs=,tag:WxsKngjZSchGehPaXT/WCg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
