jupyterhub:
    hub:
        config:
            OAuthenticator:
                oauth_callback_url: ENC[AES256_GCM,data:QRFhXi/PgsAqxplpL7U9nZvsFljaNyvVsdYSbhg9uMYsPr1pSRnMfTqPmRF2IGQ3agLv4w==,iv:e5sUXh6YfuFFhaPc2P0ItS/1n98yrxlexIViRqOJ3uE=,tag:QzWs7C3nphBos2/ldI/rUg==,type:str]
                client_id: ENC[AES256_GCM,data:Lbyv8JfxnqHgJ+mF+A0T9asolWo=,iv:nnJ2n4YaKqH0Q8s7Asv2OG4qawnDXcZhWIyk/qDJj5I=,tag:sVWVxv2lv9hbJ9kug6I9Hw==,type:str]
                client_secret: ENC[AES256_GCM,data:JKbeDNRlSWM8WGYGEIbrvyQCeEZMWN/JfFF6eMZH/gMlZ6z/l7BJsA==,iv:/FzyCBXztg6qr68rWeXDcbuujUxQ7llUFR1GyTII1L4=,tag:UFGtanNCrLbdKjW4drZhFA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:TOHEceq/,iv:W2w0cQiKuFjujSow0Zf3fnXO9Dy/3CRtyrawJWFyzFA=,tag:ufnyuDg1MzCHRFwe6qyBNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:296062562246:key/9c28321e-eb64-49d9-a0f9-30c50f9b0214
          created_at: "2025-03-11T18:41:34Z"
          enc: AQICAHhndPrOpg8p3dk1k+xmm13F+N1/BavujEV499t6yDc5OAGlTI7nHy8TXm4b1FfURjW9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSrglxgikd+fVKF3UAgEQgDt2A4B2o6F9Hhtd10KQeURFox5FrHI+IfkF2n13IQ0snJTRoaiLPzlH27TSNiz0gKrzNr4G2QxKoaX1Ig==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-11T18:41:34Z"
    mac: ENC[AES256_GCM,data:ukjedHFyRgPNsysZpXgAokXN/sFyj8M0VC1dIlqaW8VoN28Mh19vaTCU1l291sI5S+qoYr2DEq3t9rCFI8Pyj5TNyAWZHRh6ZdTfS15WyBl9CtCcfrK0c0fSNRUWS4wdhmI201MZMltkkaSXcIvX7/rACPLm19XTMwuaIC3GKdQ=,iv:CvJo+rVO8q6Uq5FnuvFQpCdK2wxOnRHVdRzBAGlTKwI=,tag:3Uomn0w+vbAVCvgjOVj9QQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
