jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:KMP0F4T4HOjgz8yUN9S1IgZ/p7o7x0WDZQ==,iv:lxdG4wmdqNZV309NRXEyebJU00aIqyhjZDEDk1R94B8=,tag:H7UzOjxxS1AVvAX+viYJ8w==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:kWBORw5cjAz+QmgbbVM2wllGShD4Rk1tdHBg/k5I2TZOauBbNyAXm0c/hW1JTdflf9/sDuKO2BhEbFr0FbiY0Q==,iv:8YvYS3MFq7xMQIlEN4tCzbZgOx43ncscepje9fYBBKo=,tag:Bl1b6QUZBzCt1MbK+/VyZQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:00Z"
          enc: CiQA471gasWVYTNzFX882wZlXNfD2LDUaQOHrQstaMh5EX5AypMSSQAtv98x9giP5oFkB7QaZ1UhtbrNs/tn80BRJh3ZubShncJylzIHKykSbXfcIiYMViCV+ctEgbmtYayRpPPhtUZ2X3Y6QYhYvtc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:01Z"
    mac: ENC[AES256_GCM,data:h+K3LYY9l4mzfQvxunK0NXk2+Vt4nfDLW6556DT7B53eNDdgzc3sRiHS+bVhMuf2PmzfO7dPO288JQRagvjZtsrvGJtZ5+wklXj/Lkf30PMExrwa5URIcmEWUNwSWWz7pX2IVuVUGhiHNtEWReYwtNnhD5wbibds4XBfwCgXHyg=,iv:Zr7QDbxyKCZ+IVsXQ+8kSAGlTTBpMpQkW6r6FFdgEgk=,tag:FRwySvaEvL1RxytyW9WjRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
