jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:hYvtk9pFseKgjd72nAFDiOs05qaKXtEAwg==,iv:zHMiuffR7bfQh/xnRpsQEdJnpBnKPbSxivHBOMZ/v0I=,tag:Uw3sz9ZEELKBx020RCgUwA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-20T21:30:03Z"
          enc: CiQA471gapSq6nWn5FKeYYjjQH7LPux0fW3pRZCmLrP0KV8SSPESSQBxTImxxkU7y3IKwWj4t4pg0cWRfHG7otP/7CRQgzJ1MGGxAyauzunLzGwrdekZxb2Kc/R6uxC4VIkEdjS91jU1kX5bSz3I5H4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-20T21:35:06Z"
    mac: ENC[AES256_GCM,data:5hGCbnoEbo5XAQSPD7ABr6zeTA39iidTbaVzUqc30vJ+Jf9enCv92td6PdLAFVzPYXC86TNaMfnG7gJHJZ2EPa1rAXq42K5cNzIZabiYLw8YMXTDyR+NGuhMne9t7UT2tluf84kEO5eOI8rcyIjEa2zl+YypzHVrIljkpgBopYg=,iv:2IBGXqheoXAurmMdYqc6yGyzC5psJluUBy3axTQ86k8=,tag:wAZNv1sx9sbeAqOwGRMgsw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
