jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:Zn7hRLFRpdZAlxVcmbTSoJH3d0wjMDXe2g==,iv:BVkoQxZFyS/DWcErb0Lwk2F9Y6TanczfWh4SNC5qT6k=,tag:p7ho3IkRatq4pN31YChJlg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-20T21:30:03Z"
          enc: CiQA471gaiKEpgrD76UKdb8XyJ7ttgNo62gQ1UyfPS1+Jswy9J8SSQBxTImx/10rDthe7G3lN59QK1CqTZdP/rKHOW0kz7dyGtM3VCZ1lk4IgVMjXz+wFLrmuruck2a60uVhjWlOqj5/xA0tw789iuw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-20T21:35:29Z"
    mac: ENC[AES256_GCM,data:7br3iAr3WSyPe4+96+8iNtHXdahfOsQIioTYxPU6GgTZrOvE7y52+zGTAZG6PTQsYrpTCofXqoXDr4NmvJDHxJ9ivgGYKA9aq1wrKsJr3LE4/T+kXbrArLsiomYoQqGUUYYbK/0E3jlddLcceHWd0NGUcZXuQeHsILPy6mDWLEM=,iv:UiirCl4uIUcvHmumfwY+jQoeUHEJJ2sF2hxa9G9gIpI=,tag:D3t1yxbtV0fAKETWem2yZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
