jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:aFFCjfjulWt2BnmxCqVNk7fe/qeYFiTgeQ==,iv:pR6q3asE8PO4YgB000nvuvCRrRdoFv5OhPqnx8SW5Fw=,tag:fpZ4MP0UjY1Bq2RKx9M/nw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:K0DZ8kCVJlKN2b8Pq4OoZev48hnyXStEAdnUbHRyslPjZaauoiKqEEeW+ysnrZRdkacDY9fhQAsYq1cJBIf8Kw==,iv:e0xlHPbSoj2Kt6I/v4KfwOVXsBqxWBz8zpbsHRklV/0=,tag:538/xkVU32M5iUD/V6pD6g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:29:02Z"
          enc: CiQA471gapdQ3LNjLc4QUjJFxFdiaFossoLC1FNST4LyRxfqiOUSSQAtv98x+hHTwD/TJvmith/JB7rSs5G8MdKNTGWWqXLW+JUJEhMwJoD1dkyrRYzRiGxgp1vUUIYfZlmj1TFlXc0lHHJqapGWes4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:29:03Z"
    mac: ENC[AES256_GCM,data:Byqlo/i7ql6iH9FA3n6gn92nwP3wBH4Dipq/P0rIjIdLY2ZTZXnaIVmYGBKa1fxhGm3RjvxC/dLqzxCLaBsgRbYgYYqUo7mvLmWh7D0oKSRo9TpZcVOnHPgbGiALOGSlP9MLEN/zVJ1KujZhG5vQAB8upQFbegVgj0SYZiExJUo=,iv:1EvMknv5Pwnddgq4B9ARqNsHJoLxmTFYoROWehxEJvg=,tag:x9H6heC7J4BIDnGS6fTL6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
