jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:g3gu,iv:I5tzTp+8hxUYLVbsLOrAkfRm6S6w+EcRC3ysFIjOa5A=,tag:xM1dRBoO8rDhCsKXg9g4Tg==,type:str]
                client_secret: ENC[AES256_GCM,data:gmLb,iv:XXdCnpPn+PGXtPWZyeOZe/+YAJAiHYmL+BQEfFwdrn4=,tag:JpEZ612WgpwS2gdfXJNJVg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-11-20T21:30:03Z"
          enc: CiQA471gaiKEpgrD76UKdb8XyJ7ttgNo62gQ1UyfPS1+Jswy9J8SSQBxTImx/10rDthe7G3lN59QK1CqTZdP/rKHOW0kz7dyGtM3VCZ1lk4IgVMjXz+wFLrmuruck2a60uVhjWlOqj5/xA0tw789iuw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-20T21:30:03Z"
    mac: ENC[AES256_GCM,data:KF4+riaRGefQZQux7kXrzcqCj9991b+rtM4UTeOfKIs+VxfjFAmwuNATcYgT46EcnInKLX1nhvdS18WlTuGKAhL8Q2CDAB8RIqy8i0o5NLBWJQIOIT9wxnRbjBqRNwkxZM+goGXW8x5yXgzPItq+wIvZhryrLPFk0w6qDPJ1aPc=,iv:tSZuPEgK7FqHUlW68juZNVtNRZz+O1As8x5jfhtHp3U=,tag:GGYcYI8Wlvm7xgMlxzv/CQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
