nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.183.114.2

jupyterhub:
  custom:
    homepage:
      # gitRepoBranch: "username-and-password-homepage"
      gitRepoBranch: "main"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Folsom Lake College
          logo_url: https://flc.losrios.edu/flc/shared/img/admin/logos-icons/flc-desktop-logo.svg
          url: https://www.flc.losrios.edu/
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2025-12-22

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2025-12-22
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        allowed_idps:
          http://google.com/accounts/o8/id:
            default: true
            username_derivation:
              username_claim: "email"
            allowed_domains:
              - apps.losrios.edu
              - flc.losrios.edu
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - mukarra@flc.losrios.edu
          - w1475529@apps.losrios.edu
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 6d61d3c15d47
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: base-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 512M
      limit: 1G
