nfsPVC:
  nfs:
    shareName: folsomlake/staging
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Folsom Lake College
          logo_url: https://flc.losrios.edu/flc/shared/img/admin/logos-icons/flc-desktop-logo.svg
          url: https://www.flc.losrios.edu/
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - folsomlake-staging.jupyter.cal-icor.org
    tls:
      - secretName: tls-cert
        hosts:
          - folsomlake-staging.jupyter.cal-icor.org
  hub:
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - sknapp
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - mukarra@flc.losrios.edu
          - w1475529@apps.losrios.edu
