nfsPVC:
  enabled: true
  nfs:
    serverIP: 34.118.238.48
  dirsizeReporter:
    enabled: false

jupyterhub:
  custom:
    homepage:
      gitRepoBranch: "username-and-password-homepage"
      gitRepoUrl: "https://github.com/cal-icor/default-hub-homepage"
      templateVars:
        org:
          name: Cal-ICOR Rstudio Workshop
          logo_url: https://www.cal-icor.org/images/logos/cal-icor.png
          url: https://cal-icor.org
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2026-06-30

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2026-06-30
    config:
      JupyterHub:
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        admin_users:
          # infrastructure
          - jedwin321@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sknapp@berkeley.edu
          - jedwin321@berkeley.edu
          - denero
          - denero@berkeley.edu
          - yijunge
          - rylo
          - sknapp
          - felder
          - balajialwar
          - gmerritt
          - eric_vandusen@berkeley.edu
          - ericvd@berkeley.edu
          - sean.smorris@berkeley.edu
          - sean.smorris
          - jedwin321@berkeley.edu
  singleuser:
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/rstudio-user-image
      tag: 41736a10a2cb
    defaultUrl: "/rstudio"
    extraFiles:
      # DH-216
      remove-exporters:
        mountPath: /etc/jupyter/jupyter_notebook_config.py
        stringData: |
          c.QtPDFExporter.enabled = False
          c.QtPNGExporter.enabled = False
          c.WebPDFExporter.enabled = False
      jupyter-shiny-proxy:
        mountPath: /etc/jupyter/jupyter_server_config.py
        stringData: |
          c.JupyterShinyProxy.site_dir = "ShinyApps"
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      hub.jupyter.org/pool-name: user-pool-2026-07-07
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "{username}"
      extraVolumeMounts:
        # RStudio can't write session files to anywhere except ~/.rstudio -
        # only way to change that is by setting $HOME. So instead, we just
        # bind mount a fresh directory on top of ~/.rstudio!
        - name: home
          mountPath: /home/jovyan/.rstudio
          subPath: '{username}/.r-hub-rstudio'
    memory:
      guarantee: 512M
      limit: 1G
