jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:s5BvMZsZx1Iq0OMoPMUHkAPC0vO7ajr0NtG+3gXAWTyK/m7JfEY9IipsDiZxggmXcOnD,iv:owFYX+n8LIBeWWAt8wjL1jFKhsKiG0Yl/a00vui/D7Q=,tag:6Mt1UvIZI97sXj5e2YbSAw==,type:str]
                client_secret: ENC[AES256_GCM,data:550TyyRCZkSj6jqC6Vjxrd+wgHQZzQTbmwExsfA6z7Cws8DRLor4Aa5rekCv1Se/2Gdon7EoJfbz4W6EmGuTHGLpxKn0z4REpUwr6GDofkWd9M3WUYg=,iv:RThS1Y2AObX4RGxV9wRAD2VCP3bkwA9Xvj430vm9Hvk=,tag:BKOIxf8jyWqP/o9nKH67nw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:rD5DIfn664805Fn0MgUzu9sXa8c3QZ+hfcIZ2CbsHDbdLIsDi/t8eQFs75Zk+v6TjGelK0k3eSSJ4jtrndW3FA==,iv:zmce6mng++NFkKadCQ4nzRrfOoECgkgxe+CIjBsWvyE=,tag:IJCZrbS2tIz96P56PTOR3g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:12Z"
          enc: CiQA471gaoY1zmy2BbSFuAoT5MSD3VvZpYK8fPx9dd1vevLuw+8SSQAtv98xnJGOeyVDXOyR2Hc+rrgNwdjjN4Q9+OCBRFLySM4c+rTtAtapL0JegA4Aj0yLhkhAeCz+D6EqYMA0Q6KNIHKg+NT9JQI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:12Z"
    mac: ENC[AES256_GCM,data:izoBKG8+gUygG80uUu1Myu6TzITi18YkOKTCWxfR0L4v4liMFGQBMzG2fVOmpteU9njIDNmxqNsCjqQTZQzboAGTzzYHvN82mFVdnJbPBglYADghdUHofd88ZFZeWsxOvVoBkikZq0rhBoi5vzPiffbktSQ/d+rzNW3g28mRjkc=,iv:5fFlR7RorgMsSZO2AInIvORMjdM5UE8do8z2a0/LAXE=,tag:iFmc6UbGAW++cPOrS2JYaA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
