jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:9hEghn0ryLibpyuSVqtgfxHfkYArjPxp9o4bIBph6u2/72/B08CkuT0dAD9EzN4dX9Z1,iv:mdhDoSyxNh2HoKOwuJKVZxrJlZrLip+KJDbAnuodv4Y=,tag:7i4q7xYB2IlKgIzeDzdSVg==,type:str]
                client_secret: ENC[AES256_GCM,data:jCp0CtQLE2CWdy+fWy9gjy63Py5CXbPPS3P4ZhhwXg0Bnfw0xPLbv+VKlDk0/VCADTnf1aSuQ2nepWY5EgfbqDOwaaUA2g6ohPF1+Lls6R2rkuMqiKk=,iv:sRKRUpnl6HijgEM8PTm8a2NSqsdwtUR0oolgB0gqb+w=,tag:rriBoSKKpr/fpsXAh4VT8w==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:xZeNWSxdFAZB5C6wUoiqJKrWBJ0NGMuDm5edXl+fxSzUUlPEeP2Wl3efOsl2nnhJ/MvsNChAdPkjXJJXgCqNBQ==,iv:iYoAoxS109xzbGV+Meqok/YEO5E/+68xBBuqd6FTs0Y=,tag:vYiGVdN+mSVXhKVfOmhqUA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:14Z"
          enc: CiQA471gahdz9xR2Drtsnatplou2tHGwMNWAgmd13NUBgBUuPWkSSQAtv98xRcHikRa1RnvE7U/A3R0dq+MFSzz3X3Nj9kMi3pb1b8Ug3ySHsS4idcGmj+sPf74XS6oluasmwTNtsu+3OCAmDpVKu6w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:14Z"
    mac: ENC[AES256_GCM,data:hCzq19dk9XWR1jaymzkNAJ3Pdg92AkM4X7jiUn1zYf9U4Jsh+T+D20Ep2XzrMOvatuw4Cbyf6vkBE/65dRDLfHVPl8T9Hhb3eI4/u+XRPDOsu0n1vCkOb2x6dMfc4BNRXhfw8Zmjv939ZdBqERztP+vldrr6vUt9B5GbDeiqU+E=,iv:dF3PeaqVukCdv5VCbPX6kruVAkH27BjQ/26wb+3cKBI=,tag:WmHy3IEsmVMrZ8/i8qJ7/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
