jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:pOFeA6312QgbiCtXnSBqQXHgpaEM2bWDKQ==,iv:zsqxT/dGMrBrlDyH+ZYDELH1CGUykfrEmrugR4DW2tQ=,tag:0gmM+rS6M55ymDOqnSEM3A==,type:str]
                #ENC[AES256_GCM,data:Vr5Inm99iyAZFQvjT/yJ,iv:VAIz4ztDrD5AmvonvaJy6rkHqCLhV9Q3cSjmeXkNg3c=,tag:D7+rGgercJ7MGw6A7RmzJg==,type:comment]
                #ENC[AES256_GCM,data:SxiPr5cN5MkiaAnTV+PHQqBRl1QP78xk3X+c2vzFi/aKiuFAYC/wgNL6H/6YNQFsdUuJUveha+HJ52iBOJYDPHcFVx0WmgLJ,iv:I285h0d51msxPYbV7gqdemtwH3qaD2jKtoMiDIxHJtc=,tag:9+VgpfP0ynlJE0f9MlBsQw==,type:comment]
                #ENC[AES256_GCM,data:3fx7fA0x7FK6TlvQsf0NOq3g8ZoHIQJnwV1OnRijBg==,iv:V70E9nRuKCgmV/uoc2e2HJLVsWAyn17gmM4WulwGrUo=,tag:9IkyH7CqlzCnnatF0HQlMA==,type:comment]
                #ENC[AES256_GCM,data:RJwuI6Wdx+vCySKDlc/iBZd6wXKYuBPpdBwwPK9lY3t7lrOAmqyI9XlvZEtv0WD5SD72ax/8Jw==,iv:+2LjXVKZnW8iZ8XXGTO4VptbvdUv9Mk1apRooYAJgus=,tag:90hVcx/woiAzVEznhckhow==,type:comment]
                #ENC[AES256_GCM,data:t/0y/xHCsUR8PCc=,iv:GiVuoQEDLI90+Toz9cjSbZKoqeCLrWy/CEDgLEO2FpM=,tag:EgSNy5tZV4t99gsZA9ryfQ==,type:comment]
                #ENC[AES256_GCM,data:Ch45X9pEBFioSELGuMfyo5edWHuN9pOgai4U,iv:AkOk7eq92wcmAbaqbG7j4P1gOMueyP9xLpFVPHtPrvo=,tag:2qenS0/wlUTgjrAaa2yUnQ==,type:comment]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:01Z"
          enc: CiQA471gahTVRILUBuiM6zFon98BdwvVtW4vKxrbighvsybf+dgSSQAjg8vZh9CHA7jFDyIGE2+LPWcqYi9lDJs3J1U6W+sAZ3EnQ+U1NGD6JVn6M+YT9MzahoOA1W16FypgT2JmoaQ386Y+FX/S7NM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-28T21:38:30Z"
    mac: ENC[AES256_GCM,data:8bqiUOkKcQZdYp1vL2V8yP4N1tfnvwlv9xD1RgYoJl0YJU1a8e5UqszVo0+5T8PnPm/mE3y4k9lb2EP/djKnzeHvsSIixETd/9uK/QazL9w7WiPbDli4A8oVg+LqCBsoJsf+mDy1OvLmnFkuuD8mks8qmrruKjTBas6/MOSYj1w=,iv:DJmAYdCWxotHh1cl1zYTt5PoCfERXn/dCCVxUfaeg6I=,tag:2X21I67a/bEq3s40wA2JcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
