jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:3VWMpsVLujyhppboH9jXysfZG3k=,iv:ygdjIiXMp4wHcMWqkCVvQMZ+SnlrtohQ7Uvid9UZ+3Q=,tag:fQrwIL5hZzGIPrPA1TXjcQ==,type:str]
                client_secret: ENC[AES256_GCM,data:0JoOnzYx7FQuytpF1HdfbILDmu2Ei0UEQ+QBVFU/jaRltkl43ziuag==,iv:YO695LpRh1CGdrpYSDbeqBMfWSObuMMA0I7PdtC9c3Q=,tag:O0tTKC62h7eLtN+NiR1SPg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-01T01:16:34Z"
          enc: CiQA471gatpDazqVt8ZzqisU3SxX1Ylp32vE3O7ARs48eHU5ZOoSSQAjg8vZHwVuba2Fs7KtcdJ7uDiZjb0+EelUqQNK2SMWmkGA0lujHDRNTChNRKYlVR/8a2IkBMggpyzPVC2CE2f3eKRjyEWOl5k=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-01T01:16:35Z"
    mac: ENC[AES256_GCM,data:39344RqTsuOw1YUmReiE5JlbValuoC5m0KYRbvrJseNZurwW4nTvKfspTl40mJXT40/aZnpbbo3nCXzFp5NxIep3Gz6UE0f+TVhSTG1+Quuv0yR9etxB4bo+6geT/+te/OcrqjZLjeU/krO29D3tONDh7ha99FQ7scSnMpyQNgI=,iv:aKOUq+8C9ZKCQkk7+4cOr62FPidV0uThn3MGxSTLgFQ=,tag:xfbf/lsWfwHbOaCDrYrRiw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
