jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:9U4zktwevVOqky4KC2ga6hvGYrM=,iv:TmiOXR6giCBgyW4M9bRkaM7ggVbjGTQvYZ5OlZ1gfvw=,tag:sw1buoZEMpZgmEvZwahlqw==,type:str]
                client_secret: ENC[AES256_GCM,data:Rx2SXJDf4YJ6N0lMJxT5oKO3BwkGpihgaoOmCiQS5mubH8PqMLRqTw==,iv:x2swhZZnU90VjGyYTLuw4AcidqPrqknD2ECJPskLAvU=,tag:Phu/VUTFE7+n85Ck+AFnsQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-05-01T01:18:25Z"
          enc: CiQA471gav24+iAYasiu7BHHPRAlBUk+MKTAYnFA5beFm4nkiMESSQAjg8vZ9uubF23xOKTXGUXF/tq7+X+jzdzIBWM6UXg9ymZ9m8sIyxubLmktqfHCYNgdqvlUrMdaX9+VVzgvhJBeUxHUUMlHMkw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-01T01:18:25Z"
    mac: ENC[AES256_GCM,data:kgEuv5WSh2HUYy7YNooEPnls4TEU9KTjFF0Oh8DYE3xZpuzvO0tF2VEg507G2ICUfOPX+9VLZlmkUIb41JkShCLuJVsk0xubFepreDrRIPW2bMwEoYLwdOxVHZeK3hGoo0mfTox7q75rX5PJv9u0UWPsxoCIrBODjf/Gfxew9OQ=,iv:iTZwLQ/6XIJ5muAV1wRFQE/v/cd2Beu3aAbnSmFbiOA=,tag:nZ2DIfePVrNOZufPnuMeUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
