jupyterhub:
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:2s5OJC8BDGmq7R3K7OgnmY01q8P5rXyYtA==,iv:hlBFsGE3TWKIoniwgGvcoHtJ/xWRFRhqM2fNc0laBWg=,tag:hB9sjbNFyb1Lz3e54ay1/Q==,type:str]
                #ENC[AES256_GCM,data:bHLdXpx6Y4P3w8eSSQyz,iv:Plp6nEzTRJsXbdh/zBAYvbjRUOJMKwg1EBzmf/fuqYE=,tag:kJTlSOTI67YW4IOlQLwKVg==,type:comment]
                #ENC[AES256_GCM,data:2MDy6EJWzMKGKfC/gwsr/KzxfJoEm1UfiucE2TOp9HvlZrdFkwWshKWLMBy/iqIz/uj6Rsd/gwYnjRATlx/d2P8/u7mJa6Qq,iv:llX+Kef9igL69sbt2KzKQz8UiqJXdTCBudkmuQNOUPo=,tag:s1a/S/tv7ClyackYStaO0A==,type:comment]
                #ENC[AES256_GCM,data:0fhY9HWQXKa4a0nEVOrZUePCG7BmjGrLgGajqajsXg==,iv:dM7ZoEOUvifiDgWCF68cWJ8XMjYwttXQyvLPdFaKRng=,tag:+4DmhOLK5tOrn7rnAoFhAQ==,type:comment]
                #ENC[AES256_GCM,data:ySnDGGuo5106WEsn3+D0kKYtAgLzOWsJG9pZRchFZmrbOsDYNy5uOQItp+94irhwgAknbYdVDQ==,iv:QGDXvyTt00I7scFJGUy9iBzrlJwkeacg5wZp3kMMB7c=,tag:8/AempdyJn8uqqRHLJI6Yw==,type:comment]
                #ENC[AES256_GCM,data:ZeS3oh1pK8rKa0g=,iv:+AC9WEan7EJIqODAufZsmCDmgpKnwOYpgncVNvtiI84=,tag:6krcqi20g4AtGf9lOoXJ2w==,type:comment]
                #ENC[AES256_GCM,data:MBIPqmE+0f4TEABKUo+Sq8iWCxN0P1rtfu+x,iv:XlizIEN8t2P3GVPyr68BvNFDV4fIbcc2QdTM77Zgob0=,tag:DK9mWf5EN/521TxUtdGplw==,type:comment]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-11T22:38:10Z"
          enc: CiQA471galV3Nb08FwjIQCr9rbKoYmepm/0xHcBky/yWU6RvR0cSSQAjg8vZVH4fuARRFlMVqnxnb4aSdXDxaoPtWBuRFCM/HS769qVml6AQLK3NMfVi/ALRD3MmV1ZE8XSwdnEaBzhPPe+p1/BuTRs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-28T21:38:02Z"
    mac: ENC[AES256_GCM,data:MbOPNDP6OoWrRfz2ceOdllpv/PWQ7OeBhJo8c2DjbzWpM3JIB/+rWuTxqNZwYL/igpYTASOtv4/v9SLksBgCRZucOfJn8HhJij/PuAUqVk2IAxS02rjheJ/RkQMhbxP3OXPdy+6eUYY7kOQyzOi8l9VlNaxxX04LaTARVKwd7j0=,iv:pskOuKMMdkhs16vDc4NL4uW5nyHtjHri1fwLI0n/gZ8=,tag:kweS6EHqIFpj2zNV/9RJ+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
