jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:q5VxJHd0ZBxdQQF6R0zlH+UfOZ2KOqEPjs8o4A==,iv:lSZXWph1UDNvCUvrLFO8A4UcWy6T1TJG9AEf/PCmsu8=,tag:O+reDIdW+CZ/kmKknjO1yw==,type:str]
                client_secret: ENC[AES256_GCM,data:H6bMwjHClGQWUyFa6mo/9PnBRjssYZEm5TpGlg==,iv:7ClUPdm+g+fCZO/Y2/qRcDYNU8RWbdyyPNf6IurDV3I=,tag:ewQT1IXiRbr5GwzZfbb7Qg==,type:str]
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:HiZghUQ6+nmfT52Afxe8O4Y56g==,iv:z2NWoIi0zPCEfIFcpTeb7PCoIV+/Rr2OlWDr8utEPn0=,tag:3YOnyX4J1zkgGFU7Kr5Yaw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-29T00:35:07Z"
          enc: CiQA471gag5TnfBGoE+eCfNSyByIqyCZ1iA17Rh59btqPhjzwdwSSQDKo3g/qNLbls/4fL7YcFU+7rVAuGVIwjds4bF/GVDTQSRomjscbxPOStcYlL2ybD5Hurt7Y07DraGuLyzZu3U93BElQ0b/FE4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-29T00:35:08Z"
    mac: ENC[AES256_GCM,data:4nyJy4qTsdO4C7SxPG2JkRRR2hL5ymoOXioNw10nkhOSEbJRhgXmpMMdkWBdNxfHSMBfviQgnuE/xqPujh7uEVAq9mgI7bXkPT0NqTK10bH4lGNhiyAi0eDGGrI3zSUZumuCifnxYy7ATlgyVyW3vp6nzbUgZYkNHoxmQME3KeI=,iv:0fzSlZL2iXDukBznlWSut98pw1uxeQvBDAFH4DSvUeg=,tag:tG8ze8J/kw36hnKyq22bbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
