jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:y0X54FsaHDuozGGRtyfO8TintsCfIFLrK0m38Q==,iv:iY0CeRj7EkiC7pP5UHz42oslRRU4me1QGjWHWNyP4SY=,tag:gWcqbLPbMdOa9Olte6rN1Q==,type:str]
                client_secret: ENC[AES256_GCM,data:wsRcb6ldfXJ2iEPbuRXs3Ob9W6xIEhzU223+Uw==,iv:1INLJ7enp8cMnXhLEhIlOrnc4gy4skMGy24TFhgBzcc=,tag:N0UyrQ9h0kOz45HLpWdeBw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-29T00:33:13Z"
          enc: CiQA471gauyotNql4b+Zy5185hzv5sVHXLGGk/KjWtoXDM6jeiESSQDKo3g/2c2XuObb4Tys1XwJ53Keklv7v9oqFFGPbHbdMgDdygt4UXp+AgsBtl4yrKV6zVWFRkOQYohH+/Rnm7cJvgBHoraDphY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-29T00:33:13Z"
    mac: ENC[AES256_GCM,data:X2DqzSkto2iymlSrCgmicocBUYKwHNe4+6p2slhftIzutiF7VbbiYvb45m5aOmbDkiwPrqpwqY8bVr39t7NBf2bvUHoE+rrlYIEsZi0ayMCTHDup51KFIMKbNUFrFoQNsoNuCmxgkJ9PFuDnVNkD1t3h4bpj+4bfdnxqjr1anx0=,iv:woeRuMUSHhLTse0tl18cNVtSZZltEzemIRgP5OzE2Ac=,tag:rdARgH9fE6aqEs04CKWW6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
