jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:q5VxJHd0ZBxdQQF6R0zlH+UfOZ2KOqEPjs8o4A==,iv:lSZXWph1UDNvCUvrLFO8A4UcWy6T1TJG9AEf/PCmsu8=,tag:O+reDIdW+CZ/kmKknjO1yw==,type:str]
                client_secret: ENC[AES256_GCM,data:H6bMwjHClGQWUyFa6mo/9PnBRjssYZEm5TpGlg==,iv:7ClUPdm+g+fCZO/Y2/qRcDYNU8RWbdyyPNf6IurDV3I=,tag:ewQT1IXiRbr5GwzZfbb7Qg==,type:str]
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:HiZghUQ6+nmfT52Afxe8O4Y56g==,iv:z2NWoIi0zPCEfIFcpTeb7PCoIV+/Rr2OlWDr8utEPn0=,tag:3YOnyX4J1zkgGFU7Kr5Yaw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:+BrCzIycwc98Tu+tFcMv//pTlNYH0XTg02DF4s3Cc30rSd4HCF4LempAB0CkvlXUeG6w2cq+BYCjPjTH6M7fmg==,iv:34j7JZXM7cZbJtpKquAGKnZCOWtVPJkLobi85uXRIgo=,tag:AowTaFz7t+gPjiSpu+0SkQ==,type:str]
sops:
    gcp_kms:
        - created_at: "2026-07-29T00:35:07Z"
          enc: CiQA471gag5TnfBGoE+eCfNSyByIqyCZ1iA17Rh59btqPhjzwdwSSQDKo3g/qNLbls/4fL7YcFU+7rVAuGVIwjds4bF/GVDTQSRomjscbxPOStcYlL2ybD5Hurt7Y07DraGuLyzZu3U93BElQ0b/FE4=
          resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
    lastmodified: "2026-07-29T16:30:43Z"
    mac: ENC[AES256_GCM,data:juUmQcn27FV1e7PuEMn56C0xIFv2tV7Ubmrekko9aCeldB95rr3YncryumOd4c7KrwEnquhXRiewxAk7G29cbkwrovoNuOzNP6Vnb523GUwEwsLcTncxkxhEQKt2/xtkxBU/Fnbu3cdHLhdnhSahwmF+r6mlr1kD9zrr+dH3r3M=,iv:aKBLhaWvqe7n/SzyIaM0Xsj3/j1jRHF5dsNNrO5eOlk=,tag:CiWAS54YTakmKVprjMXPbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
