jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:1wEJ1HMBcM7RVZKGQMrGTq9c+RymjkKTH/wyv3bhS4l6Dvho7t1j0Ip7IOk8dpD8r5QA,iv:omxva0OXHYnKi8tqHGgUjU0ac7uhzH9uNC8ivF3EAak=,tag:xhCKv4IH1VoG6XNeNBeKjg==,type:str]
                client_secret: ENC[AES256_GCM,data:M8kE+upAMXoVElDcTCuBKwGceMp9dPO3KWyq3NNhwpvXvwHfeN6v8TkRY2jhZa5d3rLKIvDif2R8b3vjjeoH3p7LuilJf70OlKrY7BUKwsKQVoTY2G0=,iv:+IymhPLrVx9zhxNBK06olNECpXRZsxVM31iME/vxAY0=,tag:uPPjcQLmjZ27DYM/KOJdAw==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:C15H07UKaxUBQOGUiyl5IEdhtC72CM++MNMuzKL6n3udimcpHxHe/JcO9UVWOXI7kJfU43yk06gY4TG4GhwO0A==,iv:dnBJAt6KTJ9LG0nTHCBHR0iAaYlACf0X2HO6VOHkOPE=,tag:yB1ReUdVMcW336n08FBDnw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:27:34Z"
          enc: CiQA471gamriCo85FSsgQRcGKkKci31UGsS5JJADR04/OF7LTbcSSQAtv98x7WORDk0Ry3okd8ipwdoiG5tjZlBY7+5ImbgZaBKNmL7X0krYTRHFtY1oPvitwc9AF1L5Hqv0EJXfmBAlhUibe3KtI0M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:27:35Z"
    mac: ENC[AES256_GCM,data:lbbz5AM0kIJIULKSnFBQHlbhNsRGSnLxf+J9mmDfdHm+7Me3U7x9Ajswr0cv7+bxVuAkVYq/mOZGvJfwOwi4g0u8RaTZZ3OFBJpDzJ+OTMofr9CifbwChAOgLxA/vy9yX9e/gjgRKt6IVbkTDK713d6ilbDYMxLJyxXgadMSRoc=,iv:nS2qI5JBN+wNAN4BsjmVFBcONTUzNJ39/gizb5LG/V0=,tag:+GpZG99iCvIeWY34sxRAUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
