jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:ynBs4J+I6Y42z5Sf/pPYXqUcaMjMq4FPhPnt++074igs3sOpYnckL9ZIMu9pWzQD530=,iv:ibaX184v4jx/jKi8QLRaNE5w9HuDqxXLyYfYQc9gN5M=,tag:bRxzyppuEkvEdqLsXGS0DQ==,type:str]
                client_secret: ENC[AES256_GCM,data:8k9W4nBR+FAHhP13tnRQIU63GL0tMUYkFq86Z4xldv38wuEi94onFA2nhI+3w1GHFLf8CTe8KsmF/OwWIwTtgllp70tz1niZGok3WfKTp5BarV9DKS8=,iv:rQzrXAaTfSsMzwpZ+2a8vTumyTmKjzqWVhlFGeCSKQI=,tag:ncdAa9TF4G0TFLToCU6Pwg==,type:str]
        services:
            cloudbank-pilot-hub-users:
                apiToken: ENC[AES256_GCM,data:WHqJQxXLcyMfzg+3dWM0SaNQ6czFMxs0MfHhBZdr6aAPu5H3S6xC94iAdQ8lO5W0c1Jc0rmVcRQSbCrP4irm/A==,iv:rZZNYG1Zo5LvEXO6+DhgONmOdQaHpc/gPV9wczeyBaA=,tag:hIejUv26AcbL/3UM5cmcrA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2026-07-07T21:28:19Z"
          enc: CiQA471gasSIsUyUN2zkN1u1IRjSTN15NHQZCOzr6Jl/qWQXQ8MSSQAtv98xsDbEq/OSAY9wFN9+1PRvfczZpBYsLVlyOFBrG9/YTsUW9joBkLFTTjR9kOtgX6F1st58TXfxaVRnPySb9XCHadqfFGI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-07T21:28:20Z"
    mac: ENC[AES256_GCM,data:Cn6/4BSMtwW00/1t1pASnHv17rfVJPKoSYR1UDksHmqUesj3KJEKUskdSJknWQ2wCOXaqbo0mqS3MMkEVMgW9t3/klX7t3BgAYF2VkphRpl7NefCx7zAnwKkrf+mylMKX63MrBzgtnlEXatWvLnkLxCgaOpyY6UmTJdgA7GMXmM=,iv:GckWgo4TUolgmDWazAlVKHU29YV70T6IncQtN9lNvto=,tag:qlFpmnaiMrrnIg4zwIpbSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
