jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:4MalixzqktwODIGWMruKUYMWmFP1EsorqHApSywy2FFEm2PT8VZqT/zsFOo0ULvKHPY=,iv:GYVq/7RdVIyvKF1doqi1x+EO2QfMUaB6dHae+dub+M8=,tag:TyNS9Lt8ztxq7qFEXGrI0A==,type:str]
                client_secret: ENC[AES256_GCM,data:vlmV7YIQnGegJGm1rbPk61FPZKm4gu/oby0gDssSWgY5SV34MdlsqsSSYwpG9WWabXP2L0GEsruoR3JvekhLUbY82MwfEhUqV4tqtJa8gplmqK/KzCw=,iv:Qs5d5dFyj6KkOWM2/mbyyETYdIah3eNSMp0GcpINHgk=,tag:mI8Wgtl22/zE9WjZsw37Tw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-06-09T21:41:20Z"
          enc: CiQA471gamM946ssQIc7W00sk4/VltOuNL/5BebS/eIdxqBwaqcSSQA0woZQOE4jBKtlQ8Q9IGfHrq1GqevHCgqiKAcKrub8jkNdzM+41eYXAQnvcsI/AMAr5PqvHmZ3cUIqM4vsOyU7pa9R/DlSyt4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-09T21:41:21Z"
    mac: ENC[AES256_GCM,data:pjPoBuUef4joN9fyLWTtBCQHwWePg8MJqgds5ycXTSKSyMsBIvqIPbW+bru2fm/IiilZoFsiVWFjjEe+Ptmsya0mDXU8iPnieYK823Q6a0iL+J49wURS+uwHFcN6Xsu7VfKnJn0rZcPFX66pWqwvOTuekcOy3fJMuplZ/Y6eCns=,iv:DnpeniD2y93guzvdIy8um2v45dIUivYeWkxREEq3r6o=,tag:bua1mWVCDdQqZfnPFJw/ig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
