jupyterhub:
    #ENC[AES256_GCM,data:Ao4gNPWzpYUii1k2nOt+,iv:ydqIPCDD4mU1QT4T6MB3GpZV+O88b6jgPABVc8apX9s=,tag:D5tH4lFW7yeGJmbDRw1n1A==,type:comment]
    #ENC[AES256_GCM,data:KScV7er0NGkH4yC7eQlc,iv:/bu9UPT8Le+WNsBS+Ql6svL6msqAQAJqTxBNhcuEERw=,tag:r09337eQv4+En8TeKeEuvw==,type:comment]
    #ENC[AES256_GCM,data:CPRRYGdR+uqbSYXAgcufLus7qrEUrZZ/kksAJU6+LWUgoIkcwhEJoRhM2/eC6JX+Sm56khh0mwPr1A==,iv:eNarpb84yA32remYlySKXmsTExuX6G/T41CNejtPElM=,tag:3c8YXsXFCSCLEklSHwTHwA==,type:comment]
    hub:
        config:
            DummyAuthenticator:
                password: ENC[AES256_GCM,data:NRyY5HyglflmuIUqqmITrUJ4L+8CufqljQ==,iv:KsC1NvYDg+ZM7UuhALey74mzZocnGtDw+Us2jpjZDAY=,tag:0RKxBvrGg9xc2hMK2e2XSQ==,type:str]
                #ENC[AES256_GCM,data:QhaIfQ1Q/hwZL+639Ozm,iv:Zc7bCwoZ1Srv8cBe8TNJ6r3Gwvc5Qx45IrRKPE7YYVU=,tag:jYpWffGsfjYH4HBQIiPrIQ==,type:comment]
                #ENC[AES256_GCM,data:IUsLtx9TZkfQtZIWctb+MkEelgmcDwzhKdqlolGlz7ttUvYC8soyhbxC1JCsEtQotzLpzNMCJ2xodfucJr5ESJiosUk6u/pd,iv:2K1XMI7gVgl+tc/jLRYMEBINr+72i9romKPlN260XMc=,tag:PeRPKHhh0FkM4KXRYpg/BQ==,type:comment]
                #ENC[AES256_GCM,data:eWhU9PiXDKtirfgI2hJNgsajUuEeJd1erSN7fG/tIw==,iv:i8X8faaLJgXU9TgrEXMpYyLJEds4TUAhd7W7mBlO6F0=,tag:zDNjiJFJw75f5J8DQkubmQ==,type:comment]
                #ENC[AES256_GCM,data:hWifjPiyjxT9/bgtlmqGbw8kdqTUGIoFaKDxCFq6F+YcdHydxDz6ercVVv7l63vxFI6HlJGI4Q==,iv:m6wuUAnKjUTVWXTi4xKoQ3XHD6d9WVrh+ndQ1/iGXX4=,tag:F16eeiWnUfXOUQkWkkobfQ==,type:comment]
                #ENC[AES256_GCM,data:G4jRRtW/TbOem0U=,iv:D1W4vE06cf+Zi4rhjLXOx4ry2chUV+cU7C3g7R86T9I=,tag:Fa330L32eFFyluxwK1L1cA==,type:comment]
                #ENC[AES256_GCM,data:JFHafweOukdEapfeHLc78Wb+zaYiJuwPN0qn,iv:Zm2MeL+Pf+iGEcydE8uBGnOIqbPT42yfbftt6TtY2xA=,tag:zF1SeEkaIwDUiorYyINaIQ==,type:comment]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/cal-icor-hubs/locations/global/keyRings/jupyterhubs/cryptoKeys/sops
          created_at: "2025-04-25T21:34:00Z"
          enc: CiQA471galwWWwZ/ZXwW7+566jHEaKNaSjnnYRYUb/mFNSQmXIUSSQAjg8vZliK91DIi89Y4tCNrKUQrQgO43UEoc7Cw0ho5fNC7tBDck0Q8kyvittTq7ALoSW5Ff6WairkfN/HtglXMOp1JjEjK4mo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-07-01T20:50:32Z"
    mac: ENC[AES256_GCM,data:/oBKIKsLkhFjrFJXR3wXZsQ+ZLnZmibsJfNJu7iu4wWAsCMzfSZJn1HKKf3FOif+E7vOoZpXkUdZjLpnMtdr8K6e+YKDDN7zQOkFqkC1DJAEbp5UUtSzi2yUeRxCzXsUmn+iZrXhcGT0yVGnlWKspucx2Pi/uQgCj3sca+dykw4=,iv:lp34ziKFMEslrUwbdi+KS/3fgfpLFfljOKhSB2ARFpg=,tag:4FlVmYdPZa8xva/MpR3CpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
