name: "Lint workflow files on pull requests"
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/*.yaml"
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install yamllint
        run: pip install yamllint==1.35.1

      - name: Lint YAML files
        run: yamllint --no-warnings .

      - uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d
