name: Deploy jupyterhub-home-nfs helm chart
# use echo ${VAR##*: } to get the value of a variable that is a string with a colon in it
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the hub repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1  # OR "2" -> To retrieve the preceding commit.
          sparse-checkout: |
            jupyterhub-home-nfs/
            deployments/jupyter/secrets/

      - name: Check if the jupyterhub-home-nfs helm chart needs to be deployed
        run: |
          echo "PR labels: ${{ steps.pr-labels.outputs.labels }}"
          for label in $(echo -e "${{ steps.pr-labels.outputs.labels }}"); do
            if [[ "$label" == jupyterhub-home-nfs-deployment ]]; then
              echo "Deploying jupyterhub-home-nfs charts!"
              echo "DEPLOY=1" >> $GITHUB_ENV
            fi
          done

      - name: Auth to gcloud
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GKE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Google Cloud SDK
        if: ${{ env.DEPLOY }}
        uses: google-github-actions/setup-gcloud@v3
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install SOPS
        if: ${{ env.DEPLOY }}
        run: |
          mkdir -p ${HOME}/bin
          curl -sSL https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64 -o ${HOME}/bin/sops
          chmod 755 ${HOME}/bin/sops
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Store SOPS secret in a file
        if: ${{ env.DEPLOY }}
        run: |
          cat << EOF > ${HOME}/sops.key
          ${{ secrets.SOPS_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/sops.key" >> $GITHUB_ENV

      - name: Activate credentials for cluster
        if: ${{ env.DEPLOY }}
        run: |
          sops -d -i deployments/jupyter/secrets/gke-key.json
          gcloud auth \
            activate-service-account \
            --key-file deployments/jupyter/secrets/gke-key.json
          gcloud container clusters \
            --region=us-central1 --project=cal-icor-hubs \
            get-credentials spring-2025

      - name: Deploy jupyterhub-home-nfs helm chart
        if: ${{ env.DEPLOY }}
        run: |
          helm dep up jupyterhub-home-nfs
          helm upgrade --install \
          --namespace jupyterhub-home-nfs \
          --create-namespace jupyterhub-home-nfs \
          --values jupyterhub-home-nfs/values.yaml \
          jupyterhub-home-nfs
