name: Deploy support helm chart
# use echo ${VAR##*: } to get the value of a variable that is a string with a colon in it
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  determine-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check-labels.outputs.deploy }}
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if the support helm chart needs to be deployed
        id: check-labels
        run: |
          echo "PR labels: ${{ steps.pr-labels.outputs.labels }}"
          deploy=false
          for label in $(echo -e "${{ steps.pr-labels.outputs.labels }}"); do
            if [[ "$label" == support-deployment ]]; then
              deploy=true
            fi
          done
          echo "Deploy support chart: ${deploy}"
          echo "deploy=${deploy}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: determine-deploy
    if: needs.determine-deploy.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the image repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Auth to gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GKE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install SOPS
        uses: ./.github/actions/install-sops

      - name: Activate credentials for cluster
        run: |
          sops -d -i deployments/jupyter/secrets/gke-key.json
          gcloud auth \
            activate-service-account \
            --key-file deployments/jupyter/secrets/gke-key.json
          gcloud container clusters \
            --region=us-central1 --project=cal-icor-hubs \
            get-credentials spring-2025

      - name: Login to GAR
        run: |
          helm registry login \
            -u _json_key --password-stdin https://us-central1-docker.pkg.dev \
            < deployments/jupyter/secrets/gke-key.json

      - name: Deploy support helm chart
        run: |
          sops -d -i support/secrets.yaml
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm dep up support
          helm upgrade \
            --install --wait --create-namespace \
            --namespace=support \
            support support/ \
            -f support/secrets.yaml
