name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  apply-labels:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
